---
title: "Optimisation de temps d'exécution en R"
linkTitle: "Optimisation temps exécution R"
author: "Sophie Baillargeon, Université Laval"
date: "2019-04-01"
weight: 2
slug: "optim_temps_r"
categories: ["cours_2019-04-09"]
categories_weight: 1
lastmodifierdisplayname : "Sophie Baillargeon"
lastmodifieremail: "sophie.baillargeon@mat.ulaval.ca"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
  blogdown::html_page:
    toc: true
header-includes:
- \usepackage[french]{babel}
- \frenchbsetup{StandardLayout}
- \hypersetup{colorlinks=true, urlcolor = {blue}, linkcolor = {blue}}
editor_options: 
  chunk_output_type: console
---





<div id="TOC">
<ul>
<li><a href="#outils-danalyse-de-la-performance-dun-programme-r">Outils d’analyse de la performance d’un programme R</a><ul>
<li><a href="#fonction-system.time">Fonction <code>system.time</code></a></li>
<li><a href="#package-microbenchmark">Package <code>microbenchmark</code></a></li>
<li><a href="#fonctions-rprof-et-summaryrprof">Fonctions <code>Rprof</code> et <code>summaryRprof</code></a></li>
<li><a href="#package-profvis">Package <code>profvis</code></a></li>
<li><a href="#comparaison-de-temps-dexecution-avec-la-fonction-microbenchmark">Comparaison de temps d’exécution avec la fonction <code>microbenchmark</code></a></li>
</ul></li>
<li><a href="#strategies-doptimisation-du-temps-dexecution">Stratégies d’optimisation du temps d’exécution</a><ul>
<li><a href="#truc-1-utiliser-des-fonctions-optimisees">Truc 1 : Utiliser des fonctions optimisées</a></li>
<li><a href="#truc-2-faire-seulement-ce-qui-est-necessaire">Truc 2 : Faire seulement ce qui est nécessaire</a></li>
<li><a href="#truc-3-exploiter-les-calculs-matriciels-et-vectoriels">Truc 3 : Exploiter les calculs matriciels et vectoriels</a></li>
<li><a href="#truc-4-eviter-les-allocations-de-memoire-inutiles">Truc 4 : Éviter les allocations de mémoire inutiles</a><ul>
<li><a href="#objets-de-dimension-croissante">Objets de dimension croissante :</a></li>
<li><a href="#modification-delements-dans-un-data-frame">Modification d’éléments dans un data frame</a></li>
</ul></li>
<li><a href="#truc-5-faire-du-calcul-en-parallele">Truc 5 : Faire du calcul en parallèle</a></li>
<li><a href="#truc-6-reprogrammer-en-c-ou-c-les-bouts-de-code-les-plus-lents">Truc 6 : Reprogrammer en C ou C++ les bouts de code les plus lents</a></li>
</ul></li>
<li><a href="#synthese">Synthèse</a></li>
<li><a href="#references">Références</a></li>
</ul>
</div>

<hr />
<p>Lorsque nous écrivons du code, notre but premier est évidemment que ce code fonctionne correctement. Après avoir vérifié que le code <a href="https://stt4230.rbind.io/programmation/tests_exceptions_r/">produit le résultat escompté et gère correctement les exceptions</a>, nous devrions, selon les <a href="https://stt4230.rbind.io/amelioration_code/bonnes_pratiques_r/">bonnes pratiques</a>, nous assurer que le code est facile à maintenir (écriture, compréhension et réutilisation aisées). Si notre code rencontre toutes les conditions énumérées ci-dessus, mais que son temps d’exécution est long, nous devrions envisager de le rendre plus rapide. Cette amélioration pourrait faire la différence entre un programme peu ou pas utilisé et un programme fréquemment utilisé. Cependant, n’oublions pas qu’il est inutile d’optimiser le temps d’exécution d’un programme roulant déjà suffisamment rapidement.</p>
<p>Pour réduire le temps d’exécution d’un programme, il faut d’abord cerner la partie du programme responsable des lenteurs. Pour ce faire, il est conseillé d’utiliser des outils qui analysent la performance du code. Après avoir cerné les instructions problématiques, il faut les modifier de façon à effectuer le calcul plus rapidement. Certains outils d’analyse de performance sont présentés dans ce qui suit. Ensuite, nous verrons des stratégies d’optimisation de temps d’exécution.</p>
<div id="outils-danalyse-de-la-performance-dun-programme-r" class="section level1">
<h1>Outils d’analyse de la performance d’un programme R</h1>
<p>Une analyse de la performance d’un programme informatique est appelée profilage de code (en anglais <em>code profiling</em>). Il est possible de profiler l’utilisation du processeur et l’utilisation de la mémoire. Nous nous concentrerons ici sur le profilage de l’utilisation du processeur, qui vise principalement à évaluer le temps d’exécution d’un programme. Le R de base propose deux outils pour évaluer le temps d’exécution d’un programme R :</p>

<ul>
<li>la fonction <code>system.time</code>,</li>
<li>les fonctions <code>Rprof</code> et <code>summaryRprof</code>.</li>
</ul>
<p>Cependant, ces fonctions ne sont parfois pas suffisantes. Les packages suivants nous seront aussi utiles :</p>
<ul>
<li><code>microbenchmark</code> et</li>
<li><code>profvis</code>.</li>
</ul>
<p>Pour illustrer l’utilisation de ces fonctions, nous allons utiliser un exemple tiré de <a href="http://www.biostat.jhsph.edu/~rpeng/docs/interface.pdf">Peng et de Leeuw, (2002)</a>. Nous allons étudier les temps d’exécution de fonctions R ayant pour but d’estimer la fonction de densité d’une variable aléatoire par la méthode du noyau à partir d’observations de la variable aléatoire. De l’information sur cette méthode, appelée en anglais <em>Kernel density estimation</em>, peut être trouvée sur la page Wikipédia suivante : <a href="https://fr.wikipedia.org/wiki/Estimation_par_noyau" class="uri">https://fr.wikipedia.org/wiki/Estimation_par_noyau</a>.</p>
<p>Il existe en fait déjà une fonction dans le package <code>stats</code> pour faire de l’estimation de densité par noyau. Il s’agit de la fonction <code>density</code>. Voici un exemple de ce qu’il est possible de réaliser avec cette fonction.</p>
<pre class="r"><code>dens &lt;- density(faithful$eruptions)  # faithful est un jeu de données du package datasets
hist(faithful$eruptions, freq = FALSE, ylab = &quot;densité&quot;, cex.main = 0.9,
     main = &quot;Densité empirique des durées des éruptions du geyser Old Faithful&quot;)
lines(dens)</code></pre>
<p><img src="/amelioration_code/optim_temps_r_2019_files/figure-html/unnamed-chunk-1-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Un histogramme est aussi une méthode d’estimation de densité. Ici, nous avons superposé une courbe de densité estimée par la méthode du noyau (aussi appelée densité Kernel) à un histogramme.</p>
<p>Nous allons écrire une version moins puissante de la fonction <code>density</code>. L’estimation de densité par noyau au point <span class="math inline">\(x\)</span> se fait par la formule suivante :
<span class="math display">\[\hat{f}(x) = \frac{1}{nh} \sum_{i = 1}^n K \left( \frac{x - x_i}{h} \right)\]</span>
où <span class="math inline">\(x_i\)</span> pour <span class="math inline">\(i=1, 2, \ldots, n\)</span> sont les observations, <span class="math inline">\(K\)</span> est une fonction noyau (en anglais <em>kernel</em>) à définir et <span class="math inline">\(h\)</span> est un paramètre de lissage (parfois appelée fenêtre). Plus la valeur de <span class="math inline">\(h\)</span> est grande, plus la courbe obtenue est lisse.</p>
<p>La fonction <code>density</code> permet l’utilisation de plusieurs fonctions noyau via l’argument <code>kernel</code>. Nous allons plutôt nous restreindre au noyau gaussien, qui est en fait la fonction de densité d’une distribution normale standard. Nous allons donc utiliser la fonction <code>dnorm</code> pour évaluer la fonction <span class="math inline">\(K\)</span> dans la formule ci-dessus.</p>
<p>Voici la première fonction proposée.</p>
<pre class="r"><code>#&#39; Estimation de densité par noyau gaussien
#&#39;
#&#39; Version 1 : utilisation de 2 boucles imbriquées
#&#39;
#&#39; @param x vecteur numérique contenant les observations
#&#39; @param xpts vecteur numérique contenant les points en lesquels l&#39;estimation de la 
#&#39;             densité doit être effectuée
#&#39; @param h nombre réel &gt; 0 : la valeur du paramètre de lissage
#&#39;
#&#39; @return vecteur numérique contenant la densité estimée en tous les points de xpts
#&#39;
ksmooth1 &lt;- function(x, xpts, h) 
{
  dens &lt;- double(length(xpts))
  n &lt;- length(x)
  for(i in 1:length(xpts)) {
    ksum &lt;- 0
    for(j in 1:length(x)) {
      d &lt;- xpts[i] - x[j]
      ksum &lt;- ksum + dnorm(d / h)
    }
    dens[i] &lt;- ksum / (n * h)
  }
  dens
}</code></pre>
<p>Des <a href="https://stt4230.rbind.io/packages/devel_packages_r/#comment-ecrire-de-la-documentation-avec-roxygen2">tags <code>roxygen2</code></a> sont utilisés pour documenter la fonction. Cependant, les commentaires <code>roxygen2</code> écrits ici ne formeraient pas une fiche d’aide complète. Ce n’est pas un problème puisque nous n’avons pas l’intention de créer un package avec cette fonction.</p>
<p>Dans la fonction <code>ksmooth1</code>, le premier argument, nommé <code>x</code>, n’est pas équivalent au <span class="math inline">\(x\)</span> de la formule. Le <span class="math inline">\(x\)</span> de la formule représente un point en lequel nous souhaitons faire l’estimation. Son équivalent dans la fonction <code>ksmooth1</code> est donc un élément du vecteur <code>xpts</code>. Ce sont les <span class="math inline">\(x_i\)</span> de la formule que nous retrouvons dans le vecteur <code>x</code>. Dans la boucle, ce vecteur <code>x</code> est parcouru en utilisant l’indice <code>j</code>. Alors, en fait, <code>x[j]</code> dans le corps de la fonction représente un <span class="math inline">\(x_i\)</span> dans la formule. Le code aurait pu coller davantage à la notation dans la formule pour être encore plus clair, mais j’ai choisi de le conserver tel qu’il a été proposé dans <a href="http://www.biostat.jhsph.edu/~rpeng/docs/interface.pdf">Peng et de Leeuw, (2002)</a>.</p>
<div id="fonction-system.time" class="section level2">
<h2>Fonction <code>system.time</code></h2>
<p>Si nous donnons en entrée à la fonction <code>ksmooth1</code> un vecteur d’observations <code>x</code> de longueur 10000, mesurons combien de temps prendra l’évaluation d’un appel à la fonction. Pour ce faire, utilisons d’abord la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/system.time.html">fonction <code>system.time</code></a>.</p>
<pre class="r"><code># Simulation des observations
x &lt;- rnorm(10000)
# Points pour lesquels nous souhaitons estimer la densité
xpts &lt;- seq(from = -4, to = 4, length.out = 17)
xpts</code></pre>
<pre><code>##  [1] -4.0 -3.5 -3.0 -2.5 -2.0 -1.5 -1.0 -0.5  0.0  0.5  1.0  1.5  2.0  2.5  3.0  3.5  4.0</code></pre>
<pre class="r"><code># Estimation de la densité
temps1 &lt;- system.time(dens1 &lt;- ksmooth1(x = x, xpts = xpts, h = 1))</code></pre>
<p>Il faut donner en entrée à <code>system.time</code> une instruction R, contenant ou non une affectation, ou encore des instructions R encadrées d’accolades. Cet ensemble d’instruction(s) est appelé <em>expression</em>. La fonction retourne le temps, en secondes, d’utilisation du CPU (<em>Central Processing Unit</em>) pour l’évaluation de l’expression. Le terme « évaluation » a ici la même signification que « exécution ».</p>
<p>Ici, j’obtiens les temps suivants :</p>
<pre class="r"><code>temps1</code></pre>
<pre><code>##    user  system elapsed 
##    0.33    0.00    0.41</code></pre>
<p>Les trois temps dans une sortie produite par <code>system.time</code> peuvent être définis ainsi :</p>
<ul>
<li><code>user</code> : temps écoulé par le logiciel R (<em>calling process</em>) pour évaluer l’expression;</li>
<li><code>system</code> : temps écoulé par le système d’exploitation de notre ordinateur, mais pour le compte du logiciel R, pendant l’évaluation de l’expression;</li>
<li><code>elapsed</code> : temps total écoulé entre la soumission de l’expression et le retour du résultat (possiblement plus grand que la somme des deux autres temps, car le système a peut-être dû accorder du temps à d’autres processus actifs sur l’ordinateur pendant l’évaluation de l’expression)</li>
</ul>
<p>Les temps d’exécution obtenus dépendent des spécifications de l’ordinateur utilisé, en particulier de la puissance de son CPU. De plus, nous n’obtiendrons probablement pas exactement les mêmes si nous évaluons à nouveau l’expression. Il y a une petite variation normale du temps d’exécution, causée notamment par les autres processus utilisant le CPU de notre ordinateur au moment où la commande est lancée.</p>
</div>
<div id="package-microbenchmark" class="section level2">
<h2>Package <code>microbenchmark</code></h2>
<p>Pour évaluer plus précisément le temps d’évaluation d’une expression, il est préférable de l’évaluer plusieurs fois, puis de calculer le temps moyen ou médian d’évaluation. La médiane est la statistique que je recommande d’utiliser ici, car elle est robuste aux valeurs extrêmes.</p>
<p>Le <a href="https://CRAN.R-project.org/package=microbenchmark">package <code>microbenchmark</code></a> s’utilise comme suit :</p>
<pre class="r"><code>library(microbenchmark)
microbenchmark(dens1 &lt;- ksmooth1(x = x, xpts = xpts, h = 1), unit = &quot;ms&quot;)</code></pre>
<pre><code>## Unit: milliseconds
##                                          expr      min       lq     mean   median
##  dens1 &lt;- ksmooth1(x = x, xpts = xpts, h = 1) 147.8901 156.9427 160.7611 159.2118
##        uq      max neval
##  162.9824 203.0739   100</code></pre>
<p>Ici, la fonction <code>microbenchmark</code> du package du même nom a été utilisée. Par défaut, cette fonction évalue 100 fois l’expression. Dans la commande précédente, nous avons fourni la valeur <code>"ms"</code> à l’argument <code>unit</code>. Le temps a donc été mesuré en millisecondes. Nous aurions pu aller jusqu’à des unités aussi petites que des nanosecondes, ce qui est impossible avec la fonction <code>system.time</code>.</p>
<p>Le premier argument fourni dans l’appel à la fonction <code>microbenchmark</code> précédent est l’expression dont le temps d’évaluation est à mesurer, comme dans l’appel à la fonction <code>system.time</code>. Cependant, nous verrons plus loin que la fonction <code>microbenchmark</code> accepte en entrée plusieurs expressions, dont les temps d’exécution sont à comparer, alors que la fonction <code>system.time</code> est limitée au chronométrage d’une expression à la fois.</p>
<p>Notons que nous pouvons considérer ici que la fonction <code>ksmooth1</code> a d’abord été testée. Nous supposons donc qu’elle retourne un résultat valide. Voici d’ailleurs ce qu’elle retourne pour l’exemple précédent.</p>
<pre class="r"><code># Résultat obtenu
dens1</code></pre>
<pre><code>##  [1] 0.00528655 0.01313148 0.02912885 0.05758210 0.10111527 0.15730969 0.21644590
##  [8] 0.26309910 0.28228630 0.26711825 0.22276588 0.16366340 0.10594109 0.06046127
## [15] 0.03045198 0.01354740 0.00532605</code></pre>
<pre class="r"><code># Graphique
hist(x, freq=FALSE, ylab = &quot;densité&quot;, cex.main = 0.9,
     main = &quot;Densité empirique d&#39;un échantillon aléatoire tiré d&#39;une distribution N(0,1)&quot;)
lines(xpts, dens1)</code></pre>
<p><img src="/amelioration_code/optim_temps_r_2019_files/figure-html/unnamed-chunk-6-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="fonctions-rprof-et-summaryrprof" class="section level2">
<h2>Fonctions <code>Rprof</code> et <code>summaryRprof</code></h2>
<p>Les fonctions <code>system.time</code> et <code>microbenchmark</code> sont bien pratiques pour évaluer un temps global d’exécution. Cependant, elles ne nous aident pas à identifier les parties du corps de la fonction <code>ksmooth1</code> qui sont les plus lentes. Pour ce faire, nous pouvons utiliser les fonctions <a href="http://stat.ethz.ch/R-manual/R-devel/library/utils/html/Rprof.html"><code>Rprof</code></a> et <a href="http://stat.ethz.ch/R-manual/R-devel/library/utils/html/summaryRprof.html"><code>summaryRprof</code></a>.</p>
<p>Pour utiliser ces fonctions, il faut ajouter la commande <code>Rprof()</code> avant le bout de code à minuter et ajouter <code>Rprof(NULL)</code> après le bout de code.</p>
<p>Pour faire un exemple avec la fonction <code>ksmooth1</code>, nous allons d’abord créer un nouveau vecteur d’observations et un nouveau vecteur de points en lesquels effectuer une estimation.</p>
<pre class="r"><code>x_long &lt;- rnorm(250000)
xpts_long &lt;- seq(from = -4, to = 4,length.out = 101)</code></pre>
<p>Ces vecteurs sont plus longs que les anciens afin que l’appel à la fonction prenne plus de temps à être évalué, ce qui permettra à <code>Rprof</code> de mieux analyser la performance du code.</p>
<pre class="r"><code>Rprof(interval = 0.01)
dens1 &lt;- ksmooth1(x = x_long, xpts = xpts_long, h = 1)
Rprof(NULL)</code></pre>
<p>Un fichier a est créé dans notre répertoire de travail. Il se nomme par défaut <em>Rprof.out</em>, mais nous pouvons changer ce nom avec l’argument <code>filename</code> de la fonction <code>Rprof</code>. Toutes les 0.01 seconde (argument <code>interval</code>), R a écrit dans ce fichier le nom de la fonction ou des fonctions dont un appel est en cours d’évaluation.</p>
<p>Typiquement, nous n’allons pas voir directement le contenu de ce fichier. Nous en affichons plutôt un résumé avec la fonction <code>summaryRprof</code> comme suit :</p>
<pre class="r"><code>summaryRprof(&quot;Rprof.out&quot;)</code></pre>
<pre><code>## $by.self
##            self.time self.pct total.time total.pct
## &quot;ksmooth1&quot;     12.26    50.12      24.46    100.00
## &quot;dnorm&quot;        12.20    49.88      12.20     49.88
## 
## $by.total
##            total.time total.pct self.time self.pct
## &quot;ksmooth1&quot;      24.46    100.00     12.26    50.12
## &quot;dnorm&quot;         12.20     49.88     12.20    49.88
## 
## $sample.interval
## [1] 0.01
## 
## $sampling.time
## [1] 24.46</code></pre>
<p>Dans cette sortie, les éléments <code>by.self</code> et <code>by.total</code> contiennent les mêmes valeurs, mais pas dans le même ordre (colonnes interchangées). Les colonnes <code>total.time</code> et <code>total.pct</code> réfèrent au temps total passé à l’évaluation de l’appel à une fonction. Pour les colonnes <code>self.time</code> et <code>self.pct</code>, le temps d’évaluation des appels de fonctions imbriqués dans l’appel de la fonction en question est retiré du temps total.</p>
<p>Dans l’exemple, la commande <code>dens1 &lt;- ksmooth1(x = x_long, xpts = xpts_long, h = 1)</code> prend un total de 24.46 secondes à être évaluée. Cette commande comprend une assignation et un appel à la fonction <code>ksmooth1</code>. Les assignations simples ne sont pas retracées par <code>Rprof</code>, car il s’agit d’appels à un opérateur interne. Elles n’apparaissent donc pas dans la sortie de <code>summaryRprof</code>. Ici, les 24.46 secondes du temps total d’exécution sont 24.46 secondes à évaluer un appel à la fonction <code>ksmooth1</code>.</p>
<p>Évaluer un appel à la fonction <code>ksmooth1</code> signifie évaluer le corps de la fonction avec les valeurs d’arguments fournis en entrée. De l’évaluation du corps de la fonction <code>ksmooth1</code>, seul l’appel à la fonction <code>dnorm</code> apparaît dans la sortie de <code>summaryRprof</code>. Les appels aux autres fonctions ou opérateurs sont ici tellement rapides qu’ils n’ont pas été détectés par <code>Rprof</code>. Le temps passé à évaluer les appels à la fonction <code>dnorm</code> est de 12.20 secondes. Ainsi, le <code>self.time</code> de <code>ksmooth1</code> est 24.46 - 12.20 = 12.26 secondes.</p>
<p>Afin de mieux expliquer l’interprétation de la sortie de <code>summaryRprof</code>, voyons aussi un autre exemple qui produit une sortie un peu plus longue.</p>
<pre class="r"><code># Facteur généré aléatoirement pour l&#39;exemple
fac_long &lt;- sample(x = 1:10, size = length(x_long), replace = TRUE)

# Profilage du temps d&#39;exécution d&#39;un appel à aggregate avec les données simulées
Rprof(interval = 0.01)
res &lt;- aggregate(x = x_long, by = list(fac_long), FUN = median)
Rprof(NULL)

# Résumé de la sortie de Rprof
summaryRprof(&quot;Rprof.out&quot;)</code></pre>

<pre><code>## $by.self
##                         self.time self.pct total.time total.pct
## &quot;.row_names_info&quot;            0.07    29.17       0.07     29.17
## &quot;anyDuplicated.default&quot;      0.07    29.17       0.07     29.17
## &quot;as.character.factor&quot;        0.04    16.67       0.04     16.67
## &quot;aggregate.data.frame&quot;       0.01     4.17       0.24    100.00
## &quot;[.data.frame&quot;               0.01     4.17       0.09     37.50
## &quot;&lt;Anonymous&gt;&quot;                0.01     4.17       0.01      4.17
## &quot;factor&quot;                     0.01     4.17       0.01      4.17
## &quot;levels&lt;-.factor&quot;            0.01     4.17       0.01      4.17
## &quot;unique.default&quot;             0.01     4.17       0.01      4.17
## 
## $by.total
##                         total.time total.pct self.time self.pct
## &quot;aggregate.data.frame&quot;        0.24    100.00      0.01     4.17
## &quot;aggregate&quot;                   0.24    100.00      0.00     0.00
## &quot;aggregate.default&quot;           0.24    100.00      0.00     0.00
## &quot;[.data.frame&quot;                0.09     37.50      0.01     4.17
## &quot;[&quot;                           0.09     37.50      0.00     0.00
## &quot;.row_names_info&quot;             0.07     29.17      0.07    29.17
## &quot;anyDuplicated.default&quot;       0.07     29.17      0.07    29.17
## &quot;anyDuplicated&quot;               0.07     29.17      0.00     0.00
## &quot;dim&quot;                         0.07     29.17      0.00     0.00
## &quot;dim.data.frame&quot;              0.07     29.17      0.00     0.00
## &quot;ncol&quot;                        0.07     29.17      0.00     0.00
## &quot;FUN&quot;                         0.06     25.00      0.00     0.00
## &quot;lapply&quot;                      0.06     25.00      0.00     0.00
## &quot;as.character.factor&quot;         0.04     16.67      0.04    16.67
## &quot;as.character&quot;                0.04     16.67      0.00     0.00
## &quot;&lt;Anonymous&gt;&quot;                 0.01      4.17      0.01     4.17
## &quot;factor&quot;                      0.01      4.17      0.01     4.17
## &quot;levels&lt;-.factor&quot;             0.01      4.17      0.01     4.17
## &quot;unique.default&quot;              0.01      4.17      0.01     4.17
## &quot;as.factor&quot;                   0.01      4.17      0.00     0.00
## &quot;do.call&quot;                     0.01      4.17      0.00     0.00
## &quot;levels&lt;-&quot;                    0.01      4.17      0.00     0.00
## &quot;match&quot;                       0.01      4.17      0.00     0.00
## &quot;sort&quot;                        0.01      4.17      0.00     0.00
## &quot;split&quot;                       0.01      4.17      0.00     0.00
## &quot;split.default&quot;               0.01      4.17      0.00     0.00
## &quot;unique&quot;                      0.01      4.17      0.00     0.00
## 
## $sample.interval
## [1] 0.01
## 
## $sampling.time
## [1] 0.24</code></pre>
<p>Dans cet exemple, les éléments <code>by.self</code> et <code>by.total</code> ne contiennent pas les mêmes lignes. Les fonctions dont les <code>self.time</code> sont nuls n’apparaissent pas dans l’élément <code>by.self</code>. Nous voyons aussi que les lignes sont ordonnées en ordre décroissant de <code>self.time</code> dans l’élément <code>by.self</code> et en ordre décroissant de <code>total.time</code> dans l’élément <code>by.total</code>.</p>
<p>Nous constatons que le code de la méthode <code>aggregate.data.frame</code> fait appel à un grand nombre de fonctions. Nous n’analyserons pas cette sortie davantage ici. Mentionnons seulement que les méthodes de la fonction générique <code>aggegate</code> ne sont pas vraiment conçues pour être rapides.</p>
</div>
<div id="package-profvis" class="section level2">
<h2>Package <code>profvis</code></h2>
<p>Pour identifier encore plus facilement les lignes les plus lentes de notre code, nous allons utiliser le <a href="https://CRAN.R-project.org/package=profvis">package <code>profvis</code></a>. Voici un exemple de son utilisation.</p>
<pre class="r"><code>library(profvis)
profvis({
  ksmooth1 &lt;- function(x, xpts, h) 
  {
    dens &lt;- double(length(xpts))
    n &lt;- length(x)
    for(i in 1:length(xpts)) {
      ksum &lt;- 0
      for(j in 1:length(x)) {
        d &lt;- xpts[i] - x[j]
        ksum &lt;- ksum + dnorm(d / h)
      }
      dens[i] &lt;- ksum / (n * h)
    }
    dens
  }
  dens1 &lt;- ksmooth1(x = x_long, xpts = xpts_long, h = 1)
})</code></pre>
<p>Pour obtenir le détail du temps d’exécution par ligne du corps d’une de nos fonctions, il faut fournir, dans l’appel à la fonction <code>profvis</code>, le code définissant la fonction en plus de l’instruction appelant la fonction. Remarquez les accolades nécessaires lorsque l’expression à profiler s’étend sur plus d’une ligne. Le résultat obtenu est ouvert dans une fenêtre indépendante, dont voici une copie :</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-12"></span>
<img src="fig/profvis.png" alt="Fenêtre de profilage ouverte par l'exemple  d'appel à la fonction profvis précédent" width="100%" />
<p class="caption">
Figure 1: Fenêtre de profilage ouverte par l’exemple d’appel à la fonction profvis précédent
</p>
</div>
<p>RStudio intègre particulièrement bien la fenêtre affichant les résultats d’un appel à la fonction <code>profvis</code>. La figure précédente ne montre qu’un des deux onglets de cette fenêtre, soit l’onglet <code>Flame Graph</code>. La fonction <code>profvis</code> profile à la fois l’utilisation de la mémoire (colonne <code>Memory</code>) et du temps d’exécution (colonne <code>Time</code>). Nous nous intéressons ici seulement à la colonne <code>Time</code>.</p>
<p>Dans cet exemple, c’est la deuxième boucle, celle imbriquée dans la première, qui prend du temps à être évaluée. Et dans cette boucle, les appels à la fonction <code>dnorm</code> sont particulièrement lents. N’oublions pas qu’ici <code>dnorm</code> est appelé au total <code>length(xpts_long)</code> <span class="math inline">\(\times\)</span> <code>length(x_long)</code> fois (101 <span class="math inline">\(\times\)</span> 250000 = 25 250 000 fois dans l’exemple).</p>
<p>Le site web suivant documente l’utilisation du package <code>profvis</code> : <a href="http://rstudio.github.io/profvis/index.html" class="uri">http://rstudio.github.io/profvis/index.html</a>.</p>
</div>
<div id="comparaison-de-temps-dexecution-avec-la-fonction-microbenchmark" class="section level2">
<h2>Comparaison de temps d’exécution avec la fonction <code>microbenchmark</code></h2>
<p>Étudions maintenant la performance d’une autre fonction d’estimation de densité par noyau gaussien tirée de <a href="http://www.biostat.jhsph.edu/~rpeng/docs/interface.pdf">Peng et de Leeuw, (2002)</a>. Le corps de cette fonction ne contient aucune boucle. Il fait plutôt du calcul vectoriel en utilisant, notamment, la fonction <code>outer</code>.</p>
<pre class="r"><code>#&#39; Estimation de densité par noyau gaussien
#&#39;
#&#39; Version 2 : utilisation de calcul vectoriel seulement
#&#39;
#&#39; mêmes arguments et même sortie que ksmooth1
#&#39;
ksmooth2 &lt;- function(x, xpts, h) 
{
  n &lt;- length(x)
  D &lt;- outer(x, xpts, &quot;-&quot;)
  K &lt;- dnorm(D / h)
  dens &lt;- colSums(K) / (h * n)
}</code></pre>
<p>Assurons-nous d’abord que cette fonction retourne exactement les mêmes valeurs que <code>ksmooth1</code>.</p>
<pre class="r"><code>dens1 &lt;- ksmooth1(x = x, xpts = xpts, h = 1)
dens2 &lt;- ksmooth2(x = x, xpts = xpts, h = 1)
all.equal(dens1, dens2)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>C’est bien le cas.</p>
<p>Comparons maintenant le temps d’exécution de cette fonction à celui de <code>ksmooth1</code>.</p>
<pre class="r"><code>microbenchmark(dens1 = ksmooth1(x = x, xpts = xpts, h = 1), 
               dens2 = ksmooth2(x = x, xpts = xpts, h = 1),
               unit = &quot;ms&quot;)</code></pre>
<pre><code>## Unit: milliseconds
##   expr      min       lq      mean    median       uq      max neval
##  dens1 154.2305 160.7595 184.38763 165.99625 180.6229 512.2439   100
##  dens2  13.0907  13.5470  15.82822  13.82005  16.9286  41.8499   100</code></pre>
<p>Dans cet appel à la fonction <code>microbenchmark</code>, les deux instructions à comparer sont fournies en deux arguments distincts. Grâce à l’argument <code>...</code> de la <a href="https://www.rdocumentation.org/packages/microbenchmark/versions/1.4-4/topics/microbenchmark">fonction <code>microbenchmark</code></a>, cette fonction peut prendre autant d’expressions à chronométrer que souhaité.</p>
<p>Débuter ces expressions par une assignation avec l’opérateur <code>=</code> aide à alléger l’affichage des résultats. Le nom fourni à gauche de l’opérateur <code>=</code> pour une expression est celui utilisé pour identifier l’expression dans la sortie.</p>
<p>La fonction <code>ksmooth2</code> est environ 12 fois plus rapide que la fonction <code>ksmooth1</code>. Cependant, elle utilise beaucoup plus de mémoire. Une matrice de dimension <code>length(x)</code> par <code>length(xpts)</code> est créée par la fonction. R impose une limite sur la taille des objets créés (pour plus de détails voir la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html">fiche d’aide <code>help("Memory-limits")</code></a>). Ainsi, la fonction <code>ksmooth2</code> retourne une erreur sur mon ordinateur si je lui donne en entrée des arguments <code>x</code> et <code>xpts</code> trop grands, par exemple :</p>
<pre class="r"><code>x_test &lt;- rnorm(1000000)
xpts_test &lt;- seq(from = -4, to = 4, length.out = 1000000)
test_memoire &lt;- ksmooth2(x = x_test, xpts = xpts_test, h = 1)</code></pre>
<pre><code>## Error: cannot allocate vector of size 7450.6 Gb</code></pre>
<p>alors que la fonction <code>ksmooth1</code> est capable de traiter ces vecteurs.</p>
<pre class="r"><code># Attention, long à exécuter
test_memoire &lt;- ksmooth1(x = x_test, xpts = xpts_test, h = 1)</code></pre>
<p>Il y donc un compromis à gérer entre le temps d’exécution et la quantité de mémoire utilisée pour faire des calculs. Un programme peut être très rapide, mais créer un objet potentiellement de taille trop grande pour être stocké en mémoire. Étant donné que notre priorité est un code fonctionnel, il faut s’assurer de ne pas aller au-delà des limites de la mémoire de notre ordinateur. Alors, dans l’optimisation du temps d’exécution, il ne faut pas oublier de garder le contrôle sur la taille des objets créés par notre programme.</p>
</div>
</div>
<div id="strategies-doptimisation-du-temps-dexecution" class="section level1">
<h1>Stratégies d’optimisation du temps d’exécution</h1>
<p>Il y a différentes stratégies utiles à connaître pour écrire du code R rapide. Voici une énumération de ces stratégies, qui sont présentées dans les sous-sections suivantes.</p>
<ol style="list-style-type: decimal">
<li>Utiliser des fonctions optimisées</li>
<li>Faire seulement ce qui est nécessaire</li>
<li>Exploiter les calculs matriciels et vectoriels</li>
<li>Éviter les allocations de mémoire inutiles</li>
<li>Faire du calcul en parallèle</li>
<li>Reprogrammer en C ou C++ les bouts de code les plus lents</li>
</ol>
<div id="truc-1-utiliser-des-fonctions-optimisees" class="section level2">
<h2>Truc 1 : Utiliser des fonctions optimisées</h2>
<p>Lorsque nous devons effectuer une tâche pour laquelle une fonction optimisée en temps de calcul existe déjà, il est préférable d’utiliser cette fonction. R est un logiciel libre. Le partage de code fait partie de la philosophie première du logiciel. Et cette réutilisation peut nous faire économiser beaucoup de temps.</p>
<p>Par exemple, R possède déjà une fonction pour l’estimation de densité par noyau. Est-ce que la fonction <code>density</code>, provenant du package <code>stats</code>, est plus rapide que la fonction <code>ksmooth1</code>?</p>
<p>Premièrement, convainquons-nous que les deux fonctions peuvent effectuer le même calcul. La commande suivante :</p>
<pre class="r"><code>dens1 &lt;- ksmooth1(x = x, xpts = xpts, h = 1)</code></pre>
<p>lance pratiquement le même calcul que cette commande :</p>
<pre class="r"><code>densd &lt;- density(x = x, bw = 1, kernel = &quot;gaussian&quot;,
                 from = -4, to = 4, n = 17)</code></pre>
<p>Rappelons que <code>xpts</code> avait été défini comme suit :</p>
<pre class="r"><code>xpts &lt;- seq(from = -4, to = 4, length.out = 17)</code></pre>
<p>d’où le choix des valeurs fournies aux arguments <code>from</code>, <code>to</code> et <code>n</code> de <code>density</code>.</p>
<p>Comparons maintenant les valeurs obtenues.</p>
<pre class="r"><code>all.equal(dens1, densd$y)</code></pre>
<pre><code>## [1] &quot;Mean relative difference: 0.0009598587&quot;</code></pre>
<p>Il y a de très petites différences ente les valeurs, parce que le paramètre de lissage <code>h</code> de <code>ksmooth1</code> n’est pas tout à fait définit comme le paramètre <code>bw</code> de la fonction <code>density</code>. Cependant, ces différences sont tellement petites que nous pouvons tout de même considérer que les deux fonctions effectuent le même calcul.</p>
<p>Comparons les temps d’exécution des deux fonctions.</p>
<pre class="r"><code>microbenchmark(densd = density(x = x, bw = 1, kernel = &quot;gaussian&quot;, from = -4, to = 4, n = 17), 
               dens1 = ksmooth1(x = x, xpts = xpts, h = 1),
               unit = &quot;ms&quot;)</code></pre>
<pre><code>## Unit: milliseconds
##   expr      min        lq       mean   median        uq      max neval
##  densd   0.4644   0.50315   0.652796   0.6049   0.65055   3.3861   100
##  dens1 157.2973 163.58380 184.591883 169.0898 181.23480 415.1592   100</code></pre>
<p>La fonction <code>density</code> retourne presque instantanément le résultat, alors que la fonction <code>ksmooth1</code> doit rouler pendant plusieurs secondes pour effectuer une estimation en 17 points, à partir de 10000 observations.</p>
<p>Le coeur du calcul de la fonction <code>density</code> est effectué par du code en langage C. C’est pour cette raison qu’elle est à ce point plus rapide que la fonction <code>ksmooth1</code>. Nous allons y revenir au truc 6.</p>
</div>
<div id="truc-2-faire-seulement-ce-qui-est-necessaire" class="section level2">
<h2>Truc 2 : Faire seulement ce qui est nécessaire</h2>
<p>L’idée derrière ce truc est simplement de ne pas alourdir un code d’évaluations inutiles.</p>
<p>Par exemple, si nous voulons calculer la somme des valeurs dans chacune des colonnes d’une matrice, la fonction <code>colSums</code> est plus rapide que la fonction <code>apply</code>.</p>
<pre class="r"><code>mat &lt;- matrix(x_long, nrow = 100, ncol = 1000)
microbenchmark(
  colSums(mat), 
  apply(mat, 2, sum))</code></pre>
<pre><code>## Unit: microseconds
##                expr    min   lq     mean  median      uq     max neval
##        colSums(mat)   64.3   90  128.645  111.15  124.50  1104.2   100
##  apply(mat, 2, sum) 1443.6 1985 2924.217 2699.35 3150.25 12298.7   100</code></pre>
<p>Ce résultat s’explique par le fait que la fonction <code>colSums</code> est spécialisée dans la tâche que nous cherchions à effectuer. Son code est simplifié, par rapport au code de <code>apply</code> qui peut appliquer n’importe quelle fonction sur n’importe quelle dimension d’un array. Nous pourrions aussi dire que la fonction <code>colSums</code> est une fonction optimisée.</p>
<p>C’est ce truc, de faire seulement ce qui est nécessaire, qui pousse certains programmeurs R à ne pas utiliser la fonction <code>return</code> pour retourner la sortie de leurs fonctions. L’appel à la fonction <code>return</code> amène une évaluation de plus à effectuer, sans être nécessaire. Pour faire un test, ajoutons un appel à la fonction <code>return</code> à la fin de la fonction <code>ksmooth2</code>.</p>
<pre class="r"><code>ksmooth2return &lt;- function(x, xpts, h) 
{
  n &lt;- length(x)
  D &lt;- outer(x, xpts, &quot;-&quot;)
  K &lt;- dnorm(D / h)
  dens &lt;- colSums(K) / (h * n)
  return(dens)
}</code></pre>
<p>Maintenant, comparons les temps d’exécution des fonctions <code>ksmooth2</code> et <code>ksmooth2return</code>.</p>
<pre class="r"><code>microbenchmark(dens2 = ksmooth2(x = x, xpts = xpts, h = 1), 
               dens2return = ksmooth2return(x = x, xpts = xpts, h = 1),
               unit = &quot;us&quot;, times = 1000)</code></pre>
<pre><code>## Unit: microseconds
##         expr     min       lq     mean   median       uq     max neval
##        dens2 12844.6 13666.65 15392.46 13869.25 16642.45 56117.9  1000
##  dens2return 12760.4 13662.35 15543.10 13900.65 16643.60 64322.3  1000</code></pre>
<p>La fonction <code>ksmooth2return</code> est effectivement légèrement plus lente que la fonction <code>ksmooth2</code>. Mais la différence entre les temps d’exécution médians des deux fonctions est à peine de l’ordre de quelques microsecondes. Alors d’autres programmeurs R préfèrent utiliser <code>return</code>, même s’il ralentit très légèrement les fonctions, dans le but d’avoir un code le plus clair possible.</p>
</div>
<div id="truc-3-exploiter-les-calculs-matriciels-et-vectoriels" class="section level2">
<h2>Truc 3 : Exploiter les calculs matriciels et vectoriels</h2>
<p>Nous avons déjà vu qu’en effectuant des calculs matriciels et vectoriels en R, comme dans la fonction <code>ksmooth2</code>, nous arrivons à faire un calcul beaucoup plus rapidement qu’avec une boucle, comme dans la fonction <code>ksmooth1</code>. Le calcul matriciel ou vectoriel en R est optimisé pour être très rapide. Il faut cependant faire attention à l’utilisation de la mémoire.</p>
<p>Nous aurions aussi pu coder la fonction <code>ksmooth</code> ainsi.</p>
<pre class="r"><code>#&#39; Estimation de densité par noyau gaussien
#&#39;
#&#39; Version 3 : utilisation d&#39;une boucle et d&#39;un calcul vectoriel
#&#39;
#&#39; mêmes arguments et même sortie que ksmooth1
#&#39;
ksmooth3 &lt;- function(x, xpts, h) 
{
  n &lt;- length(x)
  dens &lt;- double(length(xpts))
  for(i in 1:length(xpts)) {
    dens[i] &lt;- sum(dnorm((xpts[i] - x)/h)) / (n * h)
  }
  dens
}</code></pre>
<p>Cette version remplace la deuxième boucle par un calcul vectoriel.</p>
<p>Nous aurions même pu procéder comme suit.</p>
<pre class="r"><code>#&#39; Estimation de densité par noyau gaussien
#&#39;
#&#39; Version 4 : utilisation d&#39;une fonction de la famille des
#&#39;             apply et d&#39;un calcul vectoriel
#&#39;
#&#39; mêmes arguments et même sortie que ksmooth1
#&#39;
ksmooth4 &lt;- function(x, xpts, h) 
{
  n &lt;- length(x)
  sapply(
    X = xpts,
    FUN = function(xpts_i) {
      sum(dnorm((xpts_i - x) / h)) / (n * h)
    }
  )
}</code></pre>
<p>Cette version remplace la seule boucle restante par l’utilisation d’une fonction de la famille des <code>apply</code>.</p>
<p>Ces deux nouvelles versions effectuent bien le même calcul que <code>ksmooth1</code>.</p>
<pre class="r"><code>dens1 &lt;- ksmooth1(x = x, xpts = xpts, h = 1)
dens3 &lt;- ksmooth3(x = x, xpts = xpts, h = 1)
dens4 &lt;- ksmooth4(x = x, xpts = xpts, h = 1)

all.equal(dens1, dens3)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>all.equal(dens1, dens4)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Comparons maintenant les temps d’exécution des quatre versions de <code>ksmooth</code> écrites jusqu’à maintenant.</p>
<pre class="r"><code>microbenchmark(unit = &quot;ms&quot;,
              doubleBoucle_v1 = ksmooth1(x = x, xpts = xpts, h = 1), 
  calculVectorielSeulement_v2 = ksmooth2(x = x, xpts = xpts, h = 1),
   boucleEtCalculVectoriel_v3 = ksmooth3(x = x, xpts = xpts, h = 1),
    applyEtCalculVectoriel_v4 = ksmooth4(x = x, xpts = xpts, h = 1))</code></pre>
<pre><code>## Unit: milliseconds
##                         expr      min        lq      mean    median       uq      max neval
##              doubleBoucle_v1 149.6830 158.17820 168.65424 161.35360 166.6637 283.9634   100
##  calculVectorielSeulement_v2  12.8570  13.22960  14.13334  13.61015  13.9142  22.3728   100
##   boucleEtCalculVectoriel_v3  12.3001  12.43515  13.00858  12.56965  13.1963  18.4680   100
##    applyEtCalculVectoriel_v4  12.3428  12.48855  13.29448  12.72855  13.3075  25.3553   100</code></pre>
<p>Nous constatons que les deux dernières versions sont encore plus rapides que la version 2!</p>
<p>Ce qu’il faut retenir de ces exemples est ceci :</p>
<ul>
<li><p><strong>Le code le plus rapide n’est pas toujours celui que nous croyons</strong>. Il est parfois difficile de prédire quel bout de code sera le plus rapide. Ici, nous aurions pu croire que le calcul totalement vectoriel (<code>ksmooth2</code>) serait plus rapide qu’une boucle jumelée à un calcul vectoriel (<code>ksmooth3</code>). Pourtant, <code>ksmooth3</code> est légèrement plus rapide que <code>ksmooth2</code>. Il est donc toujours recommandé, lors de l’optimisation du temps d’exécution d’une fonction, d’essayer les différentes programmations possibles et de mesurer leurs temps d’exécution.</p></li>
<li><p><strong>Les fonctions de la famille des <code>apply</code> ne sont pas nécessairement plus rapides qu’une boucle</strong>. Ces fonctions cachent littéralement des boucles et ne représentent pas une sorte de calcul vectoriel. Leur utilisation est recommandée principalement parce qu’elles mènent à du code plus court et plus clair selon plusieurs programmeurs R, pas à du code nécessairement plus rapide.</p></li>
</ul>
</div>
<div id="truc-4-eviter-les-allocations-de-memoire-inutiles" class="section level2">
<h2>Truc 4 : Éviter les allocations de mémoire inutiles</h2>
<p>Allouer de l’espace dans la mémoire d’un ordinateur est une opération coûteuse en temps. À chaque fois qu’un nouvel objet est créé, une allocation en mémoire est effectuée.</p>
<p>Deux opérations plutôt anodines sont à éviter dans une boucle R, car elles provoquent une allocation en mémoire et ralentissent donc beaucoup la boucle. Il s’agit de :</p>

<ol style="list-style-type: decimal">
<li>l’utilisation d’un objet de dimension croissante,</li>
<li>l’assignation de valeur(s) à un ou des éléments d’un data frame.</li>
</ol>
<div id="objets-de-dimension-croissante" class="section level3">
<h3>Objets de dimension croissante :</h3>
<p>Un objet de dimension croissante est, par exemple, une matrice à laquelle nous ajoutons, à chaque itération d’une boucle, une ligne avec <code>rbind</code> ou une colonne avec <code>cbind</code>, comme le fait l’instruction suivante :</p>
<pre class="r"><code>matrice &lt;- rbind(matrice, nouvelleLigne)</code></pre>
<p>Avec un vecteur, une instruction similaire ferait plutôt appel à la fonction <code>c</code> ou <code>append</code> comme suit :</p>
<pre class="r"><code>vecteur &lt;- c(vecteur, nouvelElement)</code></pre>
<p>Le problème avec ces assignations est qu’elles modifient la dimension d’un objet. L’objet ne requière donc plus la même quantité d’espace mémoire. Il ne serait pas une bonne idée de simplement utiliser les cases mémoires adjacentes pour agrandir l’objet, car ces cases mémoires sont potentiellement utilisées pour stocker d’autres objets R ou n’importe quelle valeur nécessaire à un processus en cours d’exécution sur l’ordinateur. L’ordinateur doit plutôt complètement déplacer l’objet dans de nouvelles cases mémoire qu’il sait être inutilisées afin de ne pas entrer en conflit avec quoi que ce soit. Ainsi, avec les commandes précédentes, nous avons peut-être l’impression de modifier le contenu de certaines cases mémoire alors qu’en réalité nous provoquons une nouvelle allocation de mémoire.</p>
<p><strong>Exemple</strong> :</p>
<p>Simulons une expérience aléatoire pour compter le nombre de fois qu’un dé doit être tiré afin d’atteindre une somme des valeurs obtenues supérieure ou égale à 50000. Nous voulons conserver en mémoire toutes les valeurs obtenues.</p>
<p>La première fonction que nous allons créer pour simuler cette expérience va utiliser un objet de dimension croissante pour garder une trace des résultats.</p>
<pre class="r"><code>sommeDe1 &lt;- function(sommeVisee = 50000){
  somme &lt;- 0
  resultats &lt;- integer(length = 0)  # ou resultats &lt;- NULL
  while(somme &lt; sommeVisee) {
    tirage &lt;- sample(1:6, size = 1)
    somme &lt;- somme + tirage
    resultats &lt;- c(resultats, tirage)
  }
  resultats
}</code></pre>
<p>La deuxième fonction que nous allons créer pour simuler cette expérience va plutôt utiliser un grand objet de taille fixe pour stocker les résultats.</p>
<pre class="r"><code>sommeDe2 &lt;- function(sommeVisee = 50000){
  somme &lt;- 0
  resultats &lt;- integer(sommeVisee)
  i &lt;- 0
  while(somme &lt; sommeVisee) {
    tirage &lt;- sample(1:6, size = 1)
    somme &lt;- somme + tirage
    i &lt;- i + 1
    resultats[i] &lt;- tirage
  }
  resultats[1:i]
}</code></pre>
<p>Nous ne savons pas d’avance combien de lancés du dé devront être effectués pour atteindre une somme de <code>sommeVisee</code>, mais nous savons que ce sera au maximum <code>sommeVisee</code> lancés, puisque le plus petit résultat du lancé d’un dé est 1. Ainsi, nous créons d’abord un très grand vecteur, de longueur <code>sommeVisee</code>, et nous allons modifier les éléments de ce vecteur à chaque itération de la boucle (une itération = un lancé de dé). Nous modifions d’abord le premier élément puis le deuxième et ainsi de suite, grâce à l’indicateur de position <code>i</code> que nous incrémentons de 1 à chaque itération. À la fin, nous retournons seulement les éléments du vecteur de résultat qui ont été modifiés.</p>
<p>Comparons les temps d’exécution des deux fonctions.</p>
<pre class="r"><code>microbenchmark(sommeDe1(), sommeDe2(), unit = &quot;ms&quot;)</code></pre>
<pre><code>## Unit: milliseconds
##        expr      min        lq      mean   median        uq      max neval
##  sommeDe1() 237.1290 242.97985 262.69391 246.1635 256.13745 542.7847   100
##  sommeDe2()  54.4905  56.97385  61.77169  58.1141  60.10935 116.0421   100</code></pre>
<p>Nous constatons donc qu’en termes de temps de calcul, il est préférable de créer un très grand objet, de le remplir, puis de mettre de côté les éléments inutilisés que de faire croître la taille d’un objet. C’est de la préallocation de mémoire. Par contre, encore là, il y a une limite à la grandeur de l’objet qui peut être créé.</p>
</div>
<div id="modification-delements-dans-un-data-frame" class="section level3">
<h3>Modification d’éléments dans un data frame</h3>
<p>Lorsque nous modifions les éléments d’un objet R dans une boucle, comme nous avons fait dans la fonction <code>sommeDe2</code> par l’instruction suivante :</p>
<pre class="r"><code>resultats[i] &lt;- tirage</code></pre>
<p>la modification s’effectue sans réallocation de mémoire à chaque itération si :</p>
<ul>
<li>l’objet en question est un objet atomique (vecteur, matrice ou array) ou une liste;</li>
<li>la valeur assignée est du même type que les éléments de l’objet initialisé (dans le cas d’un objet atomique).</li>
</ul>
<p>Pour nous en convaincre, faisons quelques tests en utilisant la fonction <code>tracemem</code> qui affiche un message à chaque fois qu’un objet est copié en mémoire.</p>
<p>Voici une boucle qui modifie les éléments d’une matrice.</p>
<pre class="r"><code>matrice &lt;- matrix(integer(20), 4, 5)
tracemem(matrice)</code></pre>
<pre><code>[1] &quot;&lt;0000000019C9B820&gt;&quot;</code></pre>
<pre class="r"><code>for (i in 1:5){
  matrice[, i] &lt;- 1:4
}</code></pre>
<pre><code>tracemem[0x0000000019c9b820 -&gt; 0x0000000019f53170]: </code></pre>
<pre class="r"><code>untracemem(matrice)</code></pre>
<p>L’objet <code>matrice</code> est copié une seule fois, au début de la boucle, mais pas à chaque itération.</p>
<p>Nous observons le même comportement avec une liste.</p>
<pre class="r"><code>liste &lt;- vector(mode = &quot;list&quot;, length = 5)
tracemem(liste)</code></pre>
<pre><code>[1] &quot;&lt;000000001A2DC048&gt;&quot;</code></pre>
<pre class="r"><code>for (i in 1:5){
  liste[[i]] &lt;- 1:4
}</code></pre>
<pre><code>tracemem[0x000000001a2dc048 -&gt; 0x0000000019d88738]: </code></pre>
<pre class="r"><code>untracemem(liste)</code></pre>
<p>Cependant, R se comporte différemment lors de la modification d’un élément dans un data frame</p>
<pre class="r"><code>df &lt;- as.data.frame(matrix(integer(20), 4, 5))
tracemem(df)</code></pre>
<pre><code>[1] &quot;&lt;0000000019B7D730&gt;&quot;</code></pre>
<pre class="r"><code>for (i in 1:5){
  df[, i] &lt;- 1:4
}</code></pre>
<pre><code>tracemem[0x0000000019b7d730 -&gt; 0x0000000018e92818]: 
tracemem[0x0000000018e92818 -&gt; 0x0000000018e92950]: [&lt;-.data.frame [&lt;- 
tracemem[0x0000000018e92950 -&gt; 0x0000000018e929b8]: [&lt;-.data.frame [&lt;- 
tracemem[0x0000000018e929b8 -&gt; 0x0000000018e92a20]: 
tracemem[0x0000000018e92a20 -&gt; 0x0000000018e92b58]: [&lt;-.data.frame [&lt;- 
tracemem[0x0000000018e92b58 -&gt; 0x0000000018e92bc0]: [&lt;-.data.frame [&lt;- 
tracemem[0x0000000018e92bc0 -&gt; 0x0000000018e92c28]: 
tracemem[0x0000000018e92c28 -&gt; 0x000000001a2ab810]: [&lt;-.data.frame [&lt;- 
tracemem[0x000000001a2ab810 -&gt; 0x000000001a2ab878]: [&lt;-.data.frame [&lt;- 
tracemem[0x000000001a2ab878 -&gt; 0x000000001a2ab8e0]: 
tracemem[0x000000001a2ab8e0 -&gt; 0x000000001a2aba18]: [&lt;-.data.frame [&lt;- 
tracemem[0x000000001a2aba18 -&gt; 0x000000001a2aba80]: [&lt;-.data.frame [&lt;- 
tracemem[0x000000001a2aba80 -&gt; 0x000000001a2abae8]: 
tracemem[0x000000001a2abae8 -&gt; 0x000000001a2abc20]: [&lt;-.data.frame [&lt;- 
tracemem[0x000000001a2abc20 -&gt; 0x000000001a2abc88]: [&lt;-.data.frame [&lt;- </code></pre>
<pre class="r"><code>untracemem(df)</code></pre>
<p>À chaque itération de cette boucle, l’objet <code>df</code> est recopié 3 fois. Ces allocations de mémoire répétées prennent du temps.</p>
<p>Reprenons l’exemple de la simulation d’une expérience aléatoire pour compter le nombre de fois qu’un dé doit être tiré afin d’atteindre une somme des valeurs obtenues supérieure ou égale à 50000. Voici deux autres fonctions réalisant cette expérience, qui diffèrent seulement par le type de l’objet utilisé pour stocker les résultats. La fonction <code>sommeDe3</code> utilise une matrice et la fonction <code>sommeDe4</code> un data frame. Quelle fonction est la plus rapide?</p>
<pre class="r"><code># En utilisant une matrice pour stocker les résultats
sommeDe3 &lt;- function(sommeVisee = 50000){
  resultats &lt;- matrix(NA, ncol = 2, nrow = sommeVisee)
  # Colonne 1 : numéro de l&#39;itération
  resultats[, 1] &lt;- 1:sommeVisee
  # Boucle
  somme &lt;- 0
  i &lt;- 0
  while(somme &lt; sommeVisee) {
    tirage &lt;- sample(1:6, size = 1)
    somme &lt;- somme + tirage
    i &lt;- i + 1
    # Colonne 2 : résultat obtenu au lancé du dé
    resultats[i, 2] &lt;- tirage
  }
  resultats[1:i, ]
}

# En utilisant un data frame pour stocker les résultats
sommeDe4 &lt;- function(sommeVisee = 50000){
  resultats &lt;- as.data.frame(matrix(NA, ncol = 2, nrow = sommeVisee))
  # Colonne 1 : numéro de l&#39;itération
  resultats[, 1] &lt;- 1:sommeVisee
  # Boucle
  somme &lt;- 0
  i &lt;- 0
  while(somme &lt; sommeVisee) {
    tirage &lt;- sample(1:6, size = 1)
    somme &lt;- somme + tirage
    i &lt;- i + 1
    # Colonne 2 : résultat obtenu au lancé du dé
    resultats[i, 2] &lt;- tirage
  }
  resultats[1:i, ]
}

microbenchmark(sommeDe3(), sommeDe4(), unit = &quot;ms&quot;)</code></pre>
<pre><code>## Unit: milliseconds
##        expr      min        lq     mean   median        uq       max neval
##  sommeDe3()  55.5756  59.02365  63.6488  61.0856  65.25895  111.2359   100
##  sommeDe4() 779.3537 824.60140 886.2946 857.8143 911.84030 1481.3662   100</code></pre>
<p>Ici, l’utilisation du data frame est environ 12 fois plus lente que l’utilisation d’une matrice!</p>
<p>Bref, autant que possible, il vaut mieux <strong>éviter d’utiliser une data frame pour stocker des résultats générés dans une boucle</strong>.</p>
<p>La lenteur des opérations de manipulation de data frame est bien connue en R. Des alternatives plus rapides existent, notamment les objets de classe <code>data.table</code> offerts par le <a href="https://CRAN.R-project.org/package=data.table">package <code>data.table</code></a>. Ce package avait été mentionné dans les notes sur les <a href="https://stt4230.rbind.io/manipulation_donnees/structures_r/#le-data-table">structures de données en R</a>.</p>
<!---
## Truc 6 : Utiliser de la compilation en bytecode

La compilation en bytecode (en anglais *byte code compilation*) consiste en une étape de compilation intermédiaire entre les instructions-machine et le code source. En R, le package `compiler` permet de faire facilement de la compilation en bytecode. Ce package vient avec l'installation de base de R (il est donc déjà installé pour vous, comme la package `parallel`).

En fait, depuis la version 3.4.0 de R, de la compilation bytecode est réalisée par défaut, dès que possible, sans que l'utilisateur ait à appeler lui-même une fonction du package `compiler`. Pour illustrer les gains apportés par la compilation en bytecode, commençons par demander à R de ne pas en réaliser par défaut avec la commande suivante.


```r
library(compiler)
enableJIT(0)
```

Retournons à l'exemple des fonctions `ksmooth` pour estimer une densité par la méthode du noyau pour illustrer la compilation bytecode. Nous allons créé des versions « bytecode compilées » de notre fonction originale, `ksmooth1`, et de notre fonction la plus rapide `ksmooth3`. 


```r
ksmooth1_byte <- cmpfun(ksmooth1)
ksmooth3_byte <- cmpfun(ksmooth3)
```

Maintenant, comparons les temps d'exécution de ces fonctions avec leurs versions non « bytecode compilées ».


```r
microbenchmark(unit = "ms",
       dens_ksmooth1 = ksmooth1(x = x, xpts = xpts, h = 1), 
  dens_ksmooth1_byte = ksmooth1_byte(x = x, xpts = xpts, h = 1),
       dens_ksmooth3 = ksmooth3(x = x, xpts = xpts, h = 1),
  dens_ksmooth3_byte = ksmooth3_byte(x = x, xpts = xpts, h = 1))
```

```
## Unit: milliseconds
##                expr      min        lq      mean    median        uq      max neval
##       dens_ksmooth1 151.2961 159.01115 170.44773 163.00770 168.63725 340.6391   100
##  dens_ksmooth1_byte 148.2453 158.09170 168.83802 161.77770 167.29900 296.2068   100
##       dens_ksmooth3  12.2958  12.39965  12.76138  12.51180  12.79205  16.3856   100
##  dens_ksmooth3_byte  12.3091  12.39385  12.81442  12.50635  12.76155  17.1500   100
```

Bon, cette technique n'est pas magique, mais c'est mieux que rien. Avec à peu près aucun effort de programmation (seul un appel à fonction `cmpfun` a été nécessaire), nous avons réduit de moitié le temps d'exécution de la double boucle dans `ksmooth1`. Par contre, avec du calcul vectoriel, cette technique n'apporte pas toujours de gain en temps d'exécution, comme nous pouvons le constater avec la fonction `ksmooth3`.

Le R core team cherche toujours à rendre R le plus rapide possible. Effectuer de la compilation bytecode par défaut est un exemple de modification du logiciel qui l'a rendu plus rapide. Redonnons à R son comportement par défaut avec la commande suivante.


```r
enableJIT(3)
```

--->
</div>
</div>
<div id="truc-5-faire-du-calcul-en-parallele" class="section level2">
<h2>Truc 5 : Faire du calcul en parallèle</h2>
<p>Une importante technique pour réaliser des calculs informatiques plus rapidement est le calcul en parallèle. Il s’agit d’un type de calcul qui, dans sa version la plus simple,</p>
<ul>
<li>brise un long calcul en petits blocs de calcul indépendants;</li>
<li>réalise ces blocs de calcul sur plusieurs unités de calcul, simultanément (donc en parallèle);</li>
<li>rassemble à la fin tous les résultats.</li>
</ul>
<p>Les unités de calcul utilisées peuvent être localisées sur CPU (pour <em>Central Processing Unit</em>) ou sur GPU (pour <em>Graphical Processing Unit</em>). Nous pouvons exploiter différentes unités sur une seule machine ou encore sur plusieurs noeuds de calcul dans une grappe de serveurs.</p>
<p>Je vais réaliser un exemple dans lequel je vais exploiter tous les coeurs du CPU de mon ordinateur.</p>
<p>Il existe un très grand nombre de packages R pour réaliser du calcul en parallèle (<a href="https://cran.r-project.org/web/views/HighPerformanceComputing.html" class="uri">https://cran.r-project.org/web/views/HighPerformanceComputing.html</a>). Un de ces packages vient avec l’installation de R. Il s’agit du package <code>parallel</code>. Ce package est donc déjà installé sur votre ordinateur si R y est installé. Cependant, le package n’est pas chargé par défaut lors de l’ouverture d’une nouvelle session R. Chargeons-le.</p>
<pre class="r"><code>library(parallel)</code></pre>
<p>Tout d’abord, voyons combien de coeurs compte mon ordinateur.</p>
<pre class="r"><code>detectCores()</code></pre>
<pre><code>## [1] 4</code></pre>
<p>Il compte 4 coeurs logiques.</p>
<p>Maintenant, si nous travaillons sous Windows, il faut d’abord établir une connexion entre R est les différents coeurs avec la fonction <code>makeCluster</code>.</p>
<pre class="r"><code>coeurs &lt;- detectCores()
grappe &lt;- makeCluster(coeurs - 1)
grappe</code></pre>
<pre><code>## socket cluster with 3 nodes on host &#39;localhost&#39;</code></pre>
<p>Notons que la première fois que j’ai soumis cette commande, Windows m’a demandé une autorisation.</p>
<p>Remarquons aussi que je n’ai utilisé que 3 des 4 coeurs disponibles sur mon ordinateur dans le but de laisser un coeur libre pour les autres processus actifs.</p>
<p>Ensuite, je vais comparer la fonction <code>ksmooth4</code>, qui utilise <code>sapply</code>, à une autre version de <code>ksmooth</code> qui utilise la version parallèle du <code>sapply</code>, offerte par le package <code>parallel</code>, nommée <code>parSapply</code>.</p>
<pre class="r"><code>#&#39; Estimation de densité par noyau gaussien
#&#39;
#&#39; Version 5 : utilisation de parSapply et d&#39;un calcul vectoriel
#&#39;
#&#39; mêmes arguments et même sortie que ksmooth1
#&#39;
ksmooth5 &lt;- function(grappe, x, xpts, h)
{
  n &lt;- length(x)
  parSapply(
    cl = grappe,
    X = xpts,
    FUN = function(xpts_i) {
      sum(dnorm((xpts_i - x) / h)) / (n * h)
    }
  )
}</code></pre>
<p>Ces fonctions effectuent bien le même calcul.</p>
<pre class="r"><code>dens4 &lt;- ksmooth4(x = x, xpts = xpts, h = 1)
dens5 &lt;- ksmooth5(grappe = grappe, x = x, xpts = xpts, h = 1)

all.equal(dens4, dens5)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Laquelle est la plus rapide?</p>

<pre class="r"><code>microbenchmark(unit = &quot;ms&quot;,
     sapply_v4 = ksmooth4(x = x, xpts = xpts, h = 1), 
  parSapply_v5 = ksmooth5(grappe = grappe, x = x, xpts = xpts, h = 1))</code></pre>
<pre><code>## Unit: milliseconds
##          expr     min       lq     mean   median      uq     max neval
##     sapply_v4 16.5854 17.42565 18.64925 18.05075 18.9691 33.6488   100
##  parSapply_v5  7.9927  8.76185  9.91989  9.15605  9.8572 26.8664   100</code></pre>
<p>Le calcul en parallèle a permis de réduire un peu le temps d’exécution. Même si 3 coeurs ont été exploités, le calcul n’est pas 3 fois plus rapide, car :</p>
<ul>
<li>mon ordinateur possède en fait 2 coeurs physiques, chacun séparé en 2 coeurs logiques (pour un total de 4 coeurs logiques), et des coeurs logiques ne sont pas aussi rapides que des coeurs physiques;</li>
<li>toutes les communications entre les coeurs et R requièrent aussi un peu de temps.</li>
</ul>
<p>Une fois le calcul terminé, il est recommandé de fermer les connexions entre R et les coeurs de calcul avec la fonction <code>stopCluster</code>.</p>
<pre class="r"><code>stopCluster(grappe)</code></pre>
<p>Nous aurions pu aller chercher une amélioration plus importante du temps de calcul en utilisant plus d’unités de calcul. Le département de mathématiques et de statistique possède une grappe de calcul pouvant être utilisée par les étudiants du département pour faire du calcul en parallèle. <a href="http://www.calculquebec.ca/fr/">Calcul Québec</a> gère aussi des supercalculateurs pour le calcul en parallèle utilisable gratuitement par tout chercheur (et ses étudiants) admissible aux subventions provenant des conseils de recherche canadiens, à la condition d’avoir obtenu des accès aux ressources : <a href="http://www.calculquebec.ca/fr/acces-aux-ressources" class="uri">http://www.calculquebec.ca/fr/acces-aux-ressources</a>. Finalement, plusieurs plateformes de <a href="https://fr.wikipedia.org/wiki/Cloud_computing"><em>cloud computing</em></a> permettent d’utiliser des serveurs de calculs à faible coût (par exemple <a href="https://aws.amazon.com">Amazon Web Services</a>, <a href="https://azure.microsoft.com">Microsoft Azure</a>, <a href="https://cloud.google.com/">Google Cloud Platform</a>).</p>
<p>Lancer des calculs en parallèle sur une grappe de calcul ne s’effectue pas tout à fait comme le lancement de calculs en parallèle sur une seule machine. La communication avec la grappe s’effectue typiquement via des protocoles SSH et les programmes R se lancent en mode batch grâce à la commande <code>Rscript</code>. Ce sujet ne sera pas couvert ici, car il est plutôt complexe et la mise en oeuvre de calculs en parallèle dépend des ressources à notre disposition. Pour plus d’informations, je vous réfère à un document que j’ai écrit sur le sujet, qui est disponible ici : <a href="https://stt4230.rbind.io/autre_materiel/calcul_parallele_r/" class="uri">https://stt4230.rbind.io/autre_materiel/calcul_parallele_r/</a>.</p>
</div>
<div id="truc-6-reprogrammer-en-c-ou-c-les-bouts-de-code-les-plus-lents" class="section level2">
<h2>Truc 6 : Reprogrammer en C ou C++ les bouts de code les plus lents</h2>
<p><em>Note : La matière présentée dans cette section ne sera pas évaluée.</em></p>
<p>Un dernier truc pour rendre du code R plus rapide est de reprogrammer ses bouts les plus lents en C ou C++. Le langage R étant un langage interprété, il n’est pas aussi rapide que du C ou du C++, qui sont des langages plus près du langage machine.</p>
<p>Nous n’utilisons pas ce truc pour réaliser des analyses de données plus rapidement, mais plutôt pour créer une fonction qui réalise rapidement un certain calcul.</p>
<p>Il existe quelques outils pour intégrer du code C ou C++ en R. Un outil très populaire pour intégrer du code C++ en R est le package <code>Rcpp</code> (<a href="http://www.rcpp.org/" class="uri">http://www.rcpp.org/</a>). Le R de base offre pour sa part les fonctions <code>.C</code>, <code>.Call</code> et <code>.External</code> pour ce faire (voir le manuel <a href="http://cran.r-project.org/doc/manuals/r-release/R-exts.html#System-and-foreign-language-interfaces"><em>Writing R Extensions</em>, chapitre 5)</a>. Je vais me contenter ici d’illustrer l’utilisation de la fonction <code>.C</code>, qui est la méthode la plus simple, mais la moins puissante.</p>
<p>La fonction <code>ksmooth1</code> peut être reprogrammée en C comme suit (<a href="http://www.biostat.jhsph.edu/~rpeng/docs/interface.pdf">Peng et de Leeuw, 2002</a>) :</p>

<pre><code>#include &lt;R.h&gt;
#include &lt;Rmath.h&gt;

void kernel_smooth(double *x, int *n, double *xpts,
       int *nxpts, double *h, double *result)
{
 int i, j;
 double d, ksum;

 for(i=0; i &lt; *nxpts; i++) 
 {
  ksum = 0;
  for(j=0; j &lt; *n; j++) 
  {
   d = xpts[i] - x[j];
   ksum += dnorm(d / *h, 0, 1, 0);
  }
  result[i] = ksum / ((*n) * (*h));
 }
}</code></pre>
<p>Du code C destiné à être appelé en R avec la fonction <code>.C</code> se doit de respecter les propriétés suivantes (<a href="http://www.biostat.jhsph.edu/~rpeng/docs/interface.pdf">Peng et de Leeuw, 2002</a>) :</p>
<ul>
<li><p>Les fonctions C appelées en R doivent être de type « void ». Elles doivent retourner les résultats des calculs par leurs arguments.</p></li>
<li><p>Les arguments passés aux fonctions C sont des pointeurs à un nombre ou à un tableau. Il faut donc correctement déréférencer les pointeurs dans le code C afin d’obtenir la valeur d’un élément dont l’adresse est contenue dans le pointeur. Un pointeur est déréférencé en ajoutant <code>*</code> devant celui-ci.</p></li>
<li><p>Il est préférable d’inclure dans tout fichier contenant du code C à être appelé en R le fichier d’en-tête R.h en ajoutant au début du fichier de code C la ligne :</p></li>
</ul>
<pre><code>#include &lt;R.h&gt; </code></pre>
<p>De plus, il est possible d’utiliser en C certaines fonctions mathématiques R en incluant le fichier d’en-tête Rmath.h dans le fichier de code C par la ligne :</p>
<pre><code>#include &lt;Rmath.h&gt;</code></pre>
<p>Les fonctions mathématiques R utilisables en C sont énumérées dans le manuel de R <a href="https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-R-API"><em>Writing R Extensions</em>, chapitre 6</a>.</p>
<ul>
<li>Le fichier contenant le code C doit porter l’extension <em>.c</em>.</li>
</ul>
<p>Une fois le code C écrit, il reste trois étapes à compléter pour intégrer du code C en R avec la fonction <code>.C</code>.</p>
<ol style="list-style-type: decimal">
<li>Compiler le code C afin de créer un objet partagé si nous travaillons sur Linux ou une « bibliothèque de liens dynamiques » (an anglais <em>DLL</em>) si nous travaillons sur Windows ou Mac OS X ;</li>
<li>Charger en R l’objet partagé ou le DLL créé à l’étape précédente avec la fonction <code>dyn.load</code> ;</li>
<li>Appeler en R les fonctions créées dans le code C avec la fonction d’interface <code>.C</code>.</li>
</ol>
<p>Retournons donc à l’exemple. Supposons que le code C ci-dessus se trouve dans le fichier <code>C:/coursR/ksmoothC.c</code>. Dans le <em>terminal</em> sous Linux ou Mac OS X et dans une <em>fenêtre invite de commandes</em> sous Windows, il faut se positionner dans le répertoire contenant le fichier et lancer la commande suivante :</p>
<pre><code>R CMD SHLIB ksmoothC.c</code></pre>
<p>Notez qu’en RStudio, nous pouvons facilement ouvrir un terminal ou une fenêtre invite de commandes par le menu <em>Tools &gt; Shell…</em>.</p>
<p>Cette commande fonctionnera seulement si un compilateur C/C++ est installé sur l’ordinateur. Les <a href="https://stt4230.rbind.io/introduction/installation_r_rstudio/#tools">outils nécessaires au développement de packages R</a> en fournissent un. Si la commande a fonctionné, l’objet partagé ou le DLL sera créé. Sur Windows, il s’agit d’un fichier portant l’extension <em>.dll</em>.</p>
<p>Maintenant, chargeons cet objet en R avec la fonction <code>dyn.load</code>, comme dans cet exemple réalisé sur Windows :</p>
<pre class="r"><code>dyn.load(&quot;C:/coursR/ksmoothC.dll&quot;)</code></pre>
<p>Il ne reste plus qu’à écrire la « fonction R enveloppe », qui appelle la fonction écrite en C, comme dans cet exemple :</p>
<pre class="r"><code>#&#39; Estimation de densité par noyau gaussien
#&#39;
#&#39; Version _C : code C + appel à la fonction .C
#&#39;
#&#39; mêmes arguments et même sortie que ksmooth1
#&#39;
ksmooth_C &lt;- function(x, xpts, h) {
  n &lt;- length(x)
  nxpts &lt;- length(xpts)
  dens &lt;- .C(&quot;kernel_smooth&quot;, as.double(x), as.integer(n),
             as.double(xpts), as.integer(nxpts), as.double(h),
             result = double(length(xpts)))
  dens$result
}</code></pre>
<p>Dans l’appel à la fonction <code>.C</code>, le nom de la fonction doit obligatoirement être entre guillemets. Il est préférable de s’assurer que chaque argument passé à la fonction C est du bon type en appliquant aux arguments une fonction telle <code>as.integer</code>, <code>as.double</code>, <code>as.character</code> ou <code>as.logical</code>.</p>
<p>Est-ce que la fonction <code>ksmooth_C</code> effectue bien le même calcul que <code>ksmooth1</code>?</p>
<pre class="r"><code>dens1 &lt;- ksmooth1(x = x, xpts = xpts, h = 1)
densC &lt;- ksmooth_C(x = x, xpts = xpts, h = 1)

all.equal(dens1, densC)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Oui.</p>
<p>Maintenant, voyons si cette nouvelle version de <code>ksmooth</code> est plus rapide que certaines des autres fonctions que nous avons développées. Comparons aussi <code>ksmooth_C</code> à la fonction <code>density</code></p>
<!--
Le bloc suivant n'est pas évalué, car il provoque une erreur lorsqu'évalué
à partir du doc RMarkdown, mais pas lorsqu'évalué dans la console.
-->
<pre class="r"><code>microbenchmark(unit = &quot;ms&quot;,
  ksmooth1 = ksmooth1(x = x, xpts = xpts, h = 1), 
  ksmooth2 = ksmooth2(x = x, xpts = xpts, h = 1),
  ksmooth3 = ksmooth3(x = x, xpts = xpts, h = 1),
  ksmooth_C = ksmooth_C(x = x, xpts = xpts, h = 1),
  density = density(x = x, bw = 1, kernel = &quot;gaussian&quot;, from = -4, to = 4, n = 17))</code></pre>
<pre><code>## Unit: milliseconds
##       expr        min         lq        mean      median          uq        max neval
##   ksmooth1 160.018944 164.591159 170.1964157 167.9260415 170.7282935 220.236163   100
##   ksmooth2  13.402644  13.713477  15.6816264  14.8917480  16.5846660  61.744760   100
##   ksmooth3  12.471381  12.584219  14.0803544  12.7721640  14.8104705  58.695675   100
##  ksmooth_C  10.264700  10.315124  10.6443776  10.3643150  10.5529655  13.869510   100
##    density   0.513059   0.635065   0.6897806   0.6770265   0.7061175   1.384377   100</code></pre>
<p>La fonction <code>ksmooth_C</code> bat <code>ksmooth1</code> (double boucle), <code>ksmooth2</code> (calcul vectoriel seul avec <code>outer</code>) et <code>ksmooth3</code> (boucle et calcul vectoriel), quoiqu’elle n’est pas beaucoup plus rapide que cette dernière. Cependant, <code>density</code> demeure beaucoup plus rapide que tout ce que nous avons programmé.</p>
<p>Mais pourquoi <code>density</code> est-il tellement plus rapide alors qu’il fait appel à du code C, tout comme <code>ksmooth_C</code>? Premièrement, parce que ce code C est interfacé en R par la fonction <code>.Call</code> plutôt que <code>.C</code>. L’interface <code>.Call</code> est plus compliquée d’utilisation que <code>.C</code>, mais plus efficace. La fonction <code>density</code> est aussi plus rapide parce que son code C a lui aussi été optimisé.</p>
<hr />
</div>
</div>
<div id="synthese" class="section level1">
<h1>Synthèse</h1>
<div id="optimisation-de-temps-dexecution" class="section level4">
<h4>Optimisation de temps d’exécution</h4>
<p>Outils pour analyser la performance d’un programme R :</p>
<ul>
<li>calcul global de temps d’exécution :
<ul>
<li>la fonction <code>system.time</code> (R de base),</li>
<li>la fonction <code>microbenchmark</code> (package du même nom);</li>
</ul></li>
<li>calcul plus détaillé de temps d’exécution :
<ul>
<li>par fonction appelée (<em>call stack</em>) : les fonctions <code>Rprof</code> et <code>summaryRprof</code> (R de base),</li>
<li>par ligne de code : la fonction <code>profvis</code> (package du même nom).</li>
</ul></li>
</ul>
<p><strong>Conseil</strong> : comparaison de différentes options<br />
<span class="math inline">\(\longrightarrow\)</span> Le code le plus rapide n’est pas toujours celui que nous croyons.</p>
</div>
<div id="strategies-doptimisation-du-temps-dexecution-1" class="section level4">
<h4>Stratégies d’optimisation du temps d’exécution</h4>
<p><strong>Trucs</strong> pour du code R plus rapide :</p>
<ol style="list-style-type: decimal">
<li>Utiliser des fonctions optimisées</li>
<li>Faire seulement ce qui est nécessaire</li>
<li>Exploiter les calculs matriciels et vectoriels</li>
<li>Éviter les allocations de mémoire inutiles</li>
<li>Faire du calcul en parallèle</li>
<li>Reprogrammer en C ou C++ les bouts de code les plus lents</li>
</ol>
<p>Contrainte : <strong>compromis temps d’exécution / mémoire utilisée</strong></p>
<div id="truc-1-utiliser-des-fonctions-optimisees-1" class="section level5">
<h5>Truc 1 : Utiliser des fonctions optimisées</h5>
<p>Profiter du travail des autres</p>
<p>Le web regorge de fonctions R : la distribution de base de R, le CRAN, Bioconductor, etc.</p>
</div>
<div id="truc-2-faire-seulement-ce-qui-est-necessaire-1" class="section level5">
<h5>Truc 2 : Faire seulement ce qui est nécessaire</h5>
<p>Ne pas alourdir son code d’évaluations inutiles</p>
</div>
<div id="truc-3-exploiter-les-calculs-matriciels-et-vectoriels-1" class="section level5">
<h5>Truc 3 : Exploiter les calculs matriciels et vectoriels</h5>
<p>R est optimisé pour le calcul vectoriel</p>
<p>(fonctions de la famille des <code>apply</code> = boucles, pas calcul vectoriel)</p>
</div>
<div id="truc-4-eviter-les-allocations-de-memoire-inutiles-1" class="section level5">
<h5>Truc 4 : Éviter les allocations de mémoire inutiles</h5>
<p>Allouer de l’espace dans la mémoire d’un ordinateur = opération coûteuse en temps</p>
<p>Opérations à éviter dans une boucle R :</p>
<ol style="list-style-type: decimal">
<li>utilisation d’un objet de dimension croissante,</li>
<li>assignation de valeur(s) dans un data frame.</li>
</ol>
</div>
<div id="truc-5-faire-du-calcul-en-parallele-1" class="section level5">
<h5>Truc 5 : Faire du calcul en parallèle</h5>
<p>Version la plus simple du calcul en parallèle :</p>
<ul>
<li>brise un long calcul en petits blocs de calcul indépendants;</li>
<li>réalise ces blocs de calcul sur plusieurs unités de calcul (coeurs d’un processeur) simultanément (donc en parallèle);</li>
<li>rassemble à la fin tous les résultats.</li>
</ul>
<p>Domaine très large : <a href="https://cran.r-project.org/web/views/HighPerformanceComputing.html" class="uri">https://cran.r-project.org/web/views/HighPerformanceComputing.html</a></p>
<p>Domaine très technique : dépend des ressources à notre portée (CPU versus GPU, plusieurs coeurs sur notre ordinateur, grappe de serveurs de calcul, plateforme de cloud computing, etc.)</p>
<p>Point de départ en R : package <code>parallel</code></p>
</div>
<div id="truc-6-reprogrammer-en-c-ou-c-les-bouts-de-code-les-plus-lents-1" class="section level5">
<h5>Truc 6 : Reprogrammer en C ou C++ les bouts de code les plus lents</h5>
<p>Meilleure solution pour développer une fonction très rapide, pas pour réaliser rapidement des analyses de données.</p>
<ul>
<li>fonction d’interface <code>.C</code>,</li>
<li>fonction d’interface <code>.Call</code> ou <code>.External</code>,</li>
<li>package <code>Rcpp</code> pour l’intégration de code C++.</li>
</ul>
<hr />
</div>
</div>
</div>
<div id="references" class="section level1">
<h1>Références</h1>
<ul>
<li><strong>Outils d’analyse de la performance d’un programme R</strong>
<ul>
<li>package <code>microbenchmark</code> : <a href="https://CRAN.R-project.org/package=microbenchmark" class="uri">https://CRAN.R-project.org/package=microbenchmark</a></li>
<li>Alternatives au package <code>microbenchmark</code> : package <code>bench</code> <a href="https://github.com/r-lib/bench" class="uri">https://github.com/r-lib/bench</a></li>
<li>package <code>profvis</code> : <a href="https://rstudio.github.io/profvis/" class="uri">https://rstudio.github.io/profvis/</a></li>
</ul></li>
</ul>
<p> </p>
<ul>
<li><strong>Optimisation de temps d’exécution</strong>
<ul>
<li>Wickham, H. (2014). <em>Advanced R</em>. CRC Press.
<ul>
<li>Édition 1, Chapitre 17, URL <a href="http://adv-r.had.co.nz/Profiling.html" class="uri">http://adv-r.had.co.nz/Profiling.html</a></li>
<li>Édition 2, Chapitre 24, URL <a href="https://adv-r.hadley.nz/perf-improve.html#code-organisation" class="uri">https://adv-r.hadley.nz/perf-improve.html#code-organisation</a></li>
</ul></li>
<li>Matloff, N. (2011). <em>The Art of R Programming : A Tour of Statistical Software Design</em>, No Starch Press. Chapitre 14.</li>
<li>Adler, J. (2012). <em>R in a Nutshell</em>, Second edition. O’Reilly. Chapitre 24.</li>
<li><a href="http://www.noamross.net/blog/2014/4/16/vectorization-in-r--why.html" class="uri">http://www.noamross.net/blog/2014/4/16/vectorization-in-r--why.html</a></li>
</ul></li>
</ul>
<p> </p>
<ul>
<li><strong>Interfacer du code dans un autre langage (en particulier C ou C++)</strong>
<ul>
<li>Peng, R. D., &amp; de Leeuw, J. (2002). An Introduction to the .C Interface to R. UCLA: Academic Technology Services, Statistical Consulting Group. URL <a href="http://www.biostat.jhsph.edu/~rpeng/docs/interface.pdf" class="uri">http://www.biostat.jhsph.edu/~rpeng/docs/interface.pdf</a></li>
<li>R Core Team (2018). <em>Writing R Extensions</em>. R Foundation for Statistical Computing. Chapitre 5. URL <a href="http://cran.r-project.org/doc/manuals/r-release/R-exts.html#System-and-foreign-language-interfaces" class="uri">http://cran.r-project.org/doc/manuals/r-release/R-exts.html#System-and-foreign-language-interfaces</a></li>
<li>Matloff, N. (2011). <em>The Art of R Programming : A Tour of Statistical Software Design</em>, No Starch Press. Chapitre 15.</li>
<li>Utilisation du package <code>Rcpp</code> :
<ul>
<li><a href="http://www.rcpp.org/" class="uri">http://www.rcpp.org/</a></li>
<li>Wickham, H. (2014). <em>Advanced R</em>. CRC Press. Chapitre 19. URL <a href="http://adv-r.had.co.nz/Rcpp.html" class="uri">http://adv-r.had.co.nz/Rcpp.html</a></li>
</ul></li>
</ul></li>
</ul>
<p> </p>
<ul>
<li><strong>Calcul en parallèle</strong>
<ul>
<li><a href="https://stt4230.rbind.io/autre_materiel/calcul_parallele_r/" class="uri">https://stt4230.rbind.io/autre_materiel/calcul_parallele_r/</a></li>
<li>McCallum, E., &amp; Weston, S. (2011). <em>Parallel R</em>. O’Reilly.</li>
<li>Matloff, N. (2011). <em>The Art of R Programming : A Tour of Statistical Software Design, No Starch Press</em>. Chapitre 16.</li>
</ul></li>
</ul>
</div>
