---
title: "Prétraitement de données en R"
author: "Sophie Baillargeon, Université Laval"
date: "2019-01-25"
weight: 3
slug: "pretraitement_donnees_r"
categories: ["cours_2019-02-05"]
categories_weight: 1
lastmodifierdisplayname : "Sophie Baillargeon"
lastmodifieremail: "sophie.baillargeon@mat.ulaval.ca"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
  blogdown::html_page:
    toc: true
header-includes:
- \usepackage[french]{babel}
- \frenchbsetup{StandardLayout}
- \hypersetup{colorlinks=true, urlcolor = {blue}, linkcolor = {blue}}
editor_options: 
  chunk_output_type: console
---





<div id="TOC">
<ul>
<li><a href="#transformation-de-variables">Transformation de variables</a><ul>
<li><a href="#modification-ou-ajout-dune-variable-dans-un-data-frame">Modification ou ajout d’une variable dans un data frame</a></li>
<li><a href="#variable-conditionnelle-a-une-autre-avec-la-fonction-ifelse">Variable conditionnelle à une autre avec la fonction <code>ifelse</code></a></li>
<li><a href="#categorisation-dune-variable-numerique">Catégorisation d’une variable numérique</a><ul>
<li><a href="#fonction-cut">Fonction <code>cut</code> :</a></li>
<li><a href="#fonction-ave">Fonction <code>ave</code> :</a></li>
</ul></li>
<li><a href="#normalisation-de-valeurs-numeriques">Normalisation de valeurs numériques</a><ul>
<li><a href="#fonction-scale">Fonction <code>scale</code></a></li>
</ul></li>
<li><a href="#manipulation-de-chaines-de-caracteres">Manipulation de chaînes de caractères</a><ul>
<li><a href="#fonction-paste">Fonction <code>paste</code> :</a></li>
<li><a href="#fonction-nchar">Fonction <code>nchar</code> :</a></li>
<li><a href="#fonctions-toupper-tolower-et-casefold">Fonctions <code>toupper</code>, <code>tolower</code> et <code>casefold</code> :</a></li>
<li><a href="#fonction-strsplit">Fonction <code>strsplit</code> :</a></li>
<li><a href="#fonction-substr">Fonction <code>substr</code> :</a></li>
<li><a href="#fonctions-sub-et-gsub">Fonctions <code>sub</code> et <code>gsub</code> :</a></li>
<li><a href="#fonctions-grep-et-grepl">Fonctions <code>grep</code> et <code>grepl</code> :</a></li>
<li><a href="#fonction-chartr">Fonction <code>chartr</code> :</a></li>
<li><a href="#fonction-iconv">Fonction <code>iconv</code> :</a></li>
</ul></li>
<li><a href="#manipulation-de-dates">Manipulation de dates</a><ul>
<li><a href="#fonctions-as.date-et-sys.getlocale">Fonctions <code>as.Date</code> et <code>Sys.getlocale</code></a></li>
<li><a href="#fonctions-difftime-et-sys.date">Fonctions <code>difftime</code> et <code>Sys.Date</code></a></li>
<li><a href="#fonction-format">Fonction <code>format</code></a></li>
</ul></li>
</ul></li>
<li><a href="#manipulation-de-jeux-de-donnees">Manipulation de jeux de données</a><ul>
<li><a href="#fusion-de-donnees">Fusion de données</a><ul>
<li><a href="#concatenation-dobservations-lignes">Concaténation d’observations (lignes)</a></li>
<li><a href="#concatenation-de-variables-colonnes">Concaténation de variables (colonnes)</a></li>
<li><a href="#fusion-par-association---la-fonction-merge">Fusion par association - la fonction <code>merge</code></a></li>
</ul></li>
<li><a href="#modification-de-lordre-des-donnees">Modification de l’ordre des données</a><ul>
<li><a href="#fonction-rev">Fonction <code>rev</code> :</a></li>
<li><a href="#fonction-sort">Fonction <code>sort</code> :</a></li>
<li><a href="#fonction-order">Fonction <code>order</code> :</a></li>
<li><a href="#fonction-arrange-du-package-dplyr">Fonction <code>arrange</code> du package <code>dplyr</code></a></li>
</ul></li>
<li><a href="#changement-de-mise-en-forme-de-jeux-de-donnees">Changement de mise en forme de jeux de données</a><ul>
<li><a href="#transposition-avec-la-fonction-t">Transposition avec la fonction <code>t</code></a></li>
<li><a href="#comparaison-des-mises-en-forme-large-et-longue">Comparaison des mises en forme large et longue</a></li>
<li><a href="#transformation-entre-les-mises-en-forme-large-et-longue-avec-les-fonctions-stack-et-unstack">Transformation entre les mises en forme large et longue avec les fonctions <code>stack</code> et <code>unstack</code></a></li>
<li><a href="#transformation-entre-les-mises-en-forme-large-et-longue-avec-la-fonction-reshape">Transformation entre les mises en forme large et longue avec la fonction <code>reshape</code></a></li>
<li><a href="#transformation-entre-les-mises-en-forme-large-et-longue-avec-les-fonctions-gather-et-spread-du-package-tidyr">Transformation entre les mises en forme large et longue avec les fonctions <code>gather</code> et <code>spread</code> du package <code>tidyr</code></a></li>
<li><a href="#exemples-supplementaires-de-changement-de-mise-en-forme">Exemples supplémentaires de changement de mise en forme</a></li>
</ul></li>
</ul></li>
<li><a href="#synthese">Synthèse</a></li>
<li><a href="#references">Références</a></li>
</ul>
</div>

<hr />
<p>Maintenant que nous savons comment créer un objet contenant les données que nous voulons analyser, il nous reste un volet à couvrir dans la manipulation de données en R : le prétraitement des données. Ce prétraitement est défini ici comme étant toutes les étapes nécessaires pour rendre des données prêtes à être fournies en entrée à une certaine fonction, par exemple une fonction pour produire un graphique ou ajuster un modèle. Dans la grande majorité des cas, les données importées doivent être adaptées afin d’être utilisables. Préparer des données peut impliquer :</p>
<ul>
<li>nettoyer les données (repérer et corriger des erreurs);</li>
<li>modifier les observations d’une variable;</li>
<li>créer de nouvelles variables;</li>
<li>mettre en commun des jeux de données;</li>
<li>réordonner des observations;</li>
<li>modifier la mise en forme d’un jeu de données;</li>
<li>etc.</li>
</ul>
<p>Voici comment réaliser certains de ces prétraitements en R.</p>
<hr />
<div id="transformation-de-variables" class="section level1">
<h1>Transformation de variables</h1>
<p>Un grand nombre de transformations de variables usuelles peuvent être facilement réalisées en R, par exemple les transformations suivantes :</p>
<ul>
<li>conversion de format de données,</li>
<li>modification de chaînes de caractères (p. ex. remplacement ou retrait des caractères, modification de la casse (majuscule ou minuscule))</li>
<li>extraction d’une sous-chaîne de caractères,</li>
<li>changement de libellés pour les niveaux d’un facteur,</li>
<li>regroupement des niveaux d’un facteur,</li>
<li>transformation mathématique de variables numériques (p. ex. normalisation de valeurs),</li>
<li>arrondissement ou troncature de valeurs numériques,</li>
<li>etc.</li>
</ul>
<p>Une transformation de variables peut résulter en une modification des variables dans un jeu de données ou en la création de nouvelles variables à partir de celles existantes.</p>
<p>Supposons ici que nous travaillons avec un jeu de données stocké dans un data frame R. Les colonnes du data frame représentent des variables. Pour illustrer les transformations présentées, nous utiliserons le jeu de données <code>cars</code> du package <code>dataset</code>. Il s’agit d’un petit jeu de données à 50 observations et 2 variables.</p>
<pre class="r"><code>str(cars)</code></pre>
<pre><code>## &#39;data.frame&#39;:    50 obs. of  2 variables:
##  $ speed: num  4 4 7 7 8 9 10 10 10 11 ...
##  $ dist : num  2 10 4 22 16 10 18 26 34 17 ...</code></pre>
<p>Il s’agit d’observations prises sur des voitures. La distance parcourue (variable <code>dist</code>) par ces voitures entre le moment d’un freinage et l’atteinte d’une immobilisation complète a été mesurée. La vitesse de déplacement (variable <code>speed</code>) des voitures tout juste avant de freiner a aussi été mesurée.</p>
<p>Nous allons travailler sur une copie de ce jeu de données afin de ne pas modifier le jeu de données original.</p>
<pre class="r"><code>cars2 &lt;- cars</code></pre>
<div id="modification-ou-ajout-dune-variable-dans-un-data-frame" class="section level2">
<h2>Modification ou ajout d’une variable dans un data frame</h2>
<p>Pour remplacer une variable dans un data frame par une transformation de celle-ci, il suffit d’assigner le nouveau vecteur ou facteur contenant les observations de la variable transformée à la colonne contenant la variable à modifier.</p>
<p>Par exemple, dans le jeu de données <code>cars</code>, la distance est exprimée en pieds. Supposons que nous voulons transformer l’échelle de mesure de cette variable pour des mètres. Cette transformation est effectuée par une simple opération mathématique : la multiplication par un facteur de conversion. Ce facteur de conversion est ici 0.3048, car un pied est l’équivalent de 0.3048 mètre.</p>
<pre class="r"><code>cars2$dist * 0.3048</code></pre>
<p>Pour modifier la variable sans en créer une nouvelle, il suffit d’assigner le vecteur contenant les données pour la variable transformée à la colonne qui contenait la variable d’origine.</p>
<pre class="r"><code>cars2$dist &lt;- cars2$dist * 0.3048</code></pre>
<p>Nous savons que l’instruction <code>cars2$dist</code>, servant à identifier la colonne à modifier, aurait pu être écrite de bien d’autres façons, notamment :</p>
<ul>
<li><code>cars2[[&quot;dist&quot;]]</code></li>
<li><code>cars2[, &quot;dist&quot;]</code></li>
<li><code>cars2[, 2]</code></li>
<li>etc.</li>
</ul>
<p>Je considère cependant que l’opérateur <code>$</code> procure la syntaxe la plus simple pour un remplacement de variable dans un data frame. Le jeu de données <code>cars2</code> a été modifié comme suit.</p>
<pre class="r"><code>str(cars2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    50 obs. of  2 variables:
##  $ speed: num  4 4 7 7 8 9 10 10 10 11 ...
##  $ dist : num  0.61 3.05 1.22 6.71 4.88 ...</code></pre>
<p>La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/transform.html">fonction <code>transform</code></a> offre une autre façon d’écrire ce genre d’assignation. La commande suivante produit le même résultat que <code>cars2$dist &lt;- cars2$dist * 0.3048</code>.</p>
<pre class="r"><code>cars2 &lt;- transform(cars2, dist = dist * 0.3048)</code></pre>
<p>Il faut donner comme premier argument à la fonction <code>transform</code> le data frame dans lequel nous souhaitons effectuer une transformation de variable. Les arguments suivants sont des assignations de nouvelles valeurs. Dans ces assignations, il est possible de référer aux colonnes du data frame par leur nom sans les précéder de <code>nom_du_data_frame$</code> et sans les encadrer de guillemets, comme avec la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/subset.html">fonction <code>subset</code></a>, vue dans le <a href="https://stt4230.rbind.io/manipulation_donnees/structures_r/#fonctions-dextraction">cours sur les structures de données en R</a>.</p>
<p>Plutôt que d’écraser une colonne d’un data frame en la remplaçant par un autre objet, comme nous venons de le faire, il sera souvent préférable d’ajouter les nouvelles variables créées tout en conservant les anciennes. Dans ce cas, il suffit de concaténer les nouvelles variables au data frame avec la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/cbind.html">fonction <code>cbind</code></a> ou <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/data.frame.html"><code>data.frame</code></a>, ou d’assigner les nouvelles variables à des colonnes portant des noms qui ne sont pas initialement présents dans le data frame. Par exemple, pour ajouter une variable contenant la distance exprimée en mètres au data frame <code>cars2</code>, nous pourrions procéder comme suit.</p>
<pre class="r"><code>cars2 &lt;- cars  # pour repartir avec la version originale du jeu de données
cars2$dist_m &lt;- cars2$dist * 0.3048
head(cars2)</code></pre>
<pre><code>##   speed dist dist_m
## 1     4    2 0.6096
## 2     4   10 3.0480
## 3     7    4 1.2192
## 4     7   22 6.7056
## 5     8   16 4.8768
## 6     9   10 3.0480</code></pre>
<p>Étant donné que le jeu de données <code>cars2</code> ne contenait pas à l’origine de colonne nommée <code>dist_m</code>, une nouvelle colonne portant ce nom a été créée et ajoutée après les colonnes déjà présentes dans le data frame. La même tâche aurait pu être effectuée en utilisant la commande <code>data.frame</code> comme suit.</p>
<pre class="r"><code>cars2 &lt;- cars  # encore pour repartir avec la version originale du jeu de données
cars2 &lt;- data.frame(cars2, dist_m = cars2$dist * 0.3048)</code></pre>
<p>La fonction <code>transform</code> permet aussi d’ajouter de nouvelles variables par une assignation à un nouveau nom de colonne.</p>
<p>Il y a souvent plusieurs façons de réaliser une même tâche en R. Personnellement, je tends à adopter la façon qui présente le meilleur compromis entre un code le plus facile à comprendre possible et un code le plus court possible.</p>
</div>
<div id="variable-conditionnelle-a-une-autre-avec-la-fonction-ifelse" class="section level2">
<h2>Variable conditionnelle à une autre avec la fonction <code>ifelse</code></h2>
<p>La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/ifelse.html">fonction <code>ifelse</code></a> est souvent utile pour transformer des variables. Cette fonction prend comme premier argument un vecteur de valeurs logiques. Cet argument est nommé <code>test</code>. Elle retourne en sortie un vecteur de même longueur que <code>test</code>. Ce vecteur est formé des valeurs dans le deuxième argument (<code>yes</code>) aux positions pour lesquelles <code>test</code> comporte une valeur <code>TRUE</code>, et des valeurs dans le troisième argument (<code>no</code>) aux autres positions. Voici un petit exemple pour comprendre le fonctionnement de cette fonction.</p>
<pre class="r"><code>ifelse(test = c(TRUE, FALSE, FALSE, TRUE),
       yes = c(1, 2, 3, 4),
       no = c(-1, -2, -3 , -4))</code></pre>
<pre><code>## [1]  1 -2 -3  4</code></pre>
<p>Par exemple, supposons que nous souhaitons créer une nouvelle variable dans le jeu de données <code>cars2</code> contenant la vitesse en km/heure plutôt qu’en miles/heure, mais dans laquelle les valeurs de distance en miles à l’heure inférieures à 10 sont ramenées à des valeurs manquantes. Nous pourrions créer cette variable comme suit (1.60934 est le facteur de conversion entre un mile à l’heure et un kilomètre à l’heure).</p>
<pre class="r"><code>cars2$speed_km &lt;- ifelse(test = cars$speed &lt; 10, yes = NA, no = cars$speed * 1.60934)
head(cars2, n = 10)</code></pre>
<pre><code>##    speed dist  dist_m speed_km
## 1      4    2  0.6096       NA
## 2      4   10  3.0480       NA
## 3      7    4  1.2192       NA
## 4      7   22  6.7056       NA
## 5      8   16  4.8768       NA
## 6      9   10  3.0480       NA
## 7     10   18  5.4864 16.09340
## 8     10   26  7.9248 16.09340
## 9     10   34 10.3632 16.09340
## 10    11   17  5.1816 17.70274</code></pre>
<p>Dans cet exemple, la valeur fournie au deuxième argument (<code>yes</code>) n’est pas un vecteur de même longueur que les valeurs fournies aux arguments <code>test</code> et <code>no</code>. R applique donc la règle de recyclage pour transformer <code>NA</code>, qui est en fait un vecteur de longueur 1, en un vecteur contenant <code>length(cars$speed) =</code> 50 valeurs <code>NA</code>.</p>
<p>Il est même possible d’imbriquer plusieurs appels à la fonction <code>ifelse</code>, comme dans cet exemple.</p>
<pre class="r"><code>cars2$speed_catego &lt;- ifelse(
  test = cars2$speed &lt; 10, 
  yes = &quot;moins de 10&quot;,
  no = ifelse(
    test = cars2$speed &gt;= 20, 
    yes = &quot;20 ou plus&quot;, 
    no = &quot;entre 10 et 20&quot;
  )
)
str(cars2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    50 obs. of  5 variables:
##  $ speed       : num  4 4 7 7 8 9 10 10 10 11 ...
##  $ dist        : num  2 10 4 22 16 10 18 26 34 17 ...
##  $ dist_m      : num  0.61 3.05 1.22 6.71 4.88 ...
##  $ speed_km    : num  NA NA NA NA NA ...
##  $ speed_catego: chr  &quot;moins de 10&quot; &quot;moins de 10&quot; &quot;moins de 10&quot; &quot;moins de 10&quot; ...</code></pre>
<p>Voici un extrait du jeu de données pour mieux comprendre de quoi a l’air la nouvelle variable créée.</p>
<pre class="r"><code>cars2[c(5:7,38:40), c(&quot;speed&quot;, &quot;speed_catego&quot;)]</code></pre>
<pre><code>##    speed   speed_catego
## 5      8    moins de 10
## 6      9    moins de 10
## 7     10 entre 10 et 20
## 38    19 entre 10 et 20
## 39    20     20 ou plus
## 40    20     20 ou plus</code></pre>
<p>Nous avons catégorisé la variable <code>speed</code> en 3 catégories. Il existe cependant de meilleures façons de faire ce genre de tâche, présentées dans la section suivante.</p>
</div>
<div id="categorisation-dune-variable-numerique" class="section level2">
<h2>Catégorisation d’une variable numérique</h2>
<p>Parfois, nous avons besoin de rendre catégorique une variable numérique. Les agences de statistiques officielles, par exemple Statistique Canada, font souvent de telles catégorisations avant de rendre des données publiques afin qu’il ne soit plus possible d’identifier les individus auquels réfèrent les données. Il s’agit d’une technique courante d’anonymisation de données. Ainsi, ils peuvent donner accès à des données tout en respectant les règlements concernant la confidentialité des données.</p>
<div id="fonction-cut" class="section level3">
<h3>Fonction <code>cut</code> :</h3>
<p>La principale fonction pour catégoriser une variable numérique en R est la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/cut.html">fonction <code>cut</code></a>. En voici un exemple d’utilisation.</p>
<pre class="r"><code>cars2$speed_catego2 &lt;- cut(cars$speed, breaks = c(-Inf, 10, 20, Inf), right = FALSE)</code></pre>
<pre class="r"><code>str(cars2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    50 obs. of  6 variables:
##  $ speed        : num  4 4 7 7 8 9 10 10 10 11 ...
##  $ dist         : num  2 10 4 22 16 10 18 26 34 17 ...
##  $ dist_m       : num  0.61 3.05 1.22 6.71 4.88 ...
##  $ speed_km     : num  NA NA NA NA NA ...
##  $ speed_catego : chr  &quot;moins de 10&quot; &quot;moins de 10&quot; &quot;moins de 10&quot; &quot;moins de 10&quot; ...
##  $ speed_catego2: Factor w/ 3 levels &quot;[-Inf,10)&quot;,&quot;[10,20)&quot;,..: 1 1 1 1 1 1 2 2 2 2 ...</code></pre>
<p>La nouvelle variable obtenue est un facteur, avec des niveaux aux libellés différents de ceux de la variable <code>speed_catego</code>.</p>
<pre class="r"><code>cars2[c(5:7,38:40), c(&quot;speed&quot;, &quot;speed_catego&quot; , &quot;speed_catego2&quot;)]</code></pre>
<pre><code>##    speed   speed_catego speed_catego2
## 5      8    moins de 10     [-Inf,10)
## 6      9    moins de 10     [-Inf,10)
## 7     10 entre 10 et 20       [10,20)
## 38    19 entre 10 et 20       [10,20)
## 39    20     20 ou plus     [20, Inf)
## 40    20     20 ou plus     [20, Inf)</code></pre>
<p>Nous aurions pu contrôler ces libellés avec l’argument <code>labels</code> de la fonction <code>cut</code>.</p>
</div>
<div id="fonction-ave" class="section level3">
<h3>Fonction <code>ave</code> :</h3>
<p>Si nous souhaitions remplacer les identifiants des nouvelles catégories par une statistique calculée sur les valeurs observées dans chaque catégorie, nous utiliserions la <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/ave.html">fonction <code>ave</code></a>, comme dans cet exemple.</p>
<pre class="r"><code>cars2$speed_catego3 &lt;- ave(cars2$speed, cars2$speed_catego, FUN = mean)</code></pre>
<pre class="r"><code>cars2[c(5:7,38:40),c(&quot;speed&quot;, &quot;speed_catego&quot;, &quot;speed_catego2&quot;, &quot;speed_catego3&quot;)]</code></pre>
<pre><code>##    speed   speed_catego speed_catego2 speed_catego3
## 5      8    moins de 10     [-Inf,10)       6.50000
## 6      9    moins de 10     [-Inf,10)       6.50000
## 7     10 entre 10 et 20       [10,20)      14.53125
## 38    19 entre 10 et 20       [10,20)      14.53125
## 39    20     20 ou plus     [20, Inf)      22.16667
## 40    20     20 ou plus     [20, Inf)      22.16667</code></pre>
<p>La valeur de la nouvelle variable <code>speed_catego3</code> est la moyenne des vitesses observées dans chacune des catégories définies par la variable <code>speed_catego</code>.</p>
</div>
</div>
<div id="normalisation-de-valeurs-numeriques" class="section level2">
<h2>Normalisation de valeurs numériques</h2>
<p>La normalisation permet de ramener les mesures de différentes variables sur une même échelle.</p>
<div id="fonction-scale" class="section level3">
<h3>Fonction <code>scale</code></h3>
<p>La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/scale.html">fonction <code>scale</code></a> permet de normaliser par colonne les valeurs numériques dans une matrice ou un data frame.</p>
<p>Par exemple, revenons au jeu de données <code>cars</code> d’origine. Les valeurs pour les deux variables dans le jeu de données <code>cars</code> ne sont pas sur la même échelle. En effet, leurs moyennes et écarts-types empiriques ne sont pas similaires. Utilisons la fonction <code>apply</code>, vue dans le cours sur les <a href="https://stt4230.rbind.io/calculs/calculs_base_r/#fonction-apply">calculs de base en R</a>, pour calculer ces statistiques par variable (= par colonne).</p>
<pre class="r"><code># moyennes par variable
apply(cars, MARGIN = 2, FUN = mean)</code></pre>
<pre><code>## speed  dist 
## 15.40 42.98</code></pre>
<pre class="r"><code># écarts-types par variable
apply(cars, MARGIN = 2, FUN = sd)</code></pre>
<pre><code>##     speed      dist 
##  5.287644 25.769377</code></pre>
<p>Une normalisation couramment employée consiste à soustraire de valeurs leur moyenne, puis à diviser ces différences par l’écart-type des valeurs d’origine. Cette normalisation est parfois appelée standardisation. Les valeurs sont centrées et réduites. En notation statistique, la formule pour obtenir cette normalisation est la suivante :</p>
<center>
<p><span class="math inline">\(z_i = \frac{x_i - \bar{x}}{\sigma_x}\)</span></p>
</center>
<p>Standardisons les valeurs du jeu de donnes <code>cars</code> avec la fonction <code>scale</code>.</p>
<pre class="r"><code>cars_standard &lt;- scale(cars)</code></pre>
<p>Les valeurs dans chacune des colonnes de <code>cars_standard</code> ont une moyenne de 0 et un écart-type de 1. Elles sont donc sur la même échelle.</p>
<pre class="r"><code># moyennes par variable
round(apply(cars_standard, MARGIN = 2, FUN = mean), digits = 5)</code></pre>
<pre><code>## speed  dist 
##     0     0</code></pre>
<pre class="r"><code># écarts-types par variable
apply(cars_standard, MARGIN = 2, FUN = sd)</code></pre>
<pre><code>## speed  dist 
##     1     1</code></pre>
<p>Les arguments <code>center</code> et <code>scale</code> de la fonction <code>scale</code> permettent de contrôler, respectivement, les valeurs soustraites par colonnes et les valeurs par lesquelles les colonnes sont divisées. Il est possible, par exemple, de centrer sans réduire avec <code>center = TRUE</code> et <code>scale = FALSE</code>.</p>
<p>Un autre exemple de normalisation possible avec <code>scale</code> est de ramener les mesures de toutes les variables entre 0 et 1. En notation statistique, la formule pour obtenir cette normalisation est la suivante :</p>
<center>
<p><span class="math inline">\(y_i = \frac{x_i - \min(x)}{\max(x) - \min(x)}\)</span></p>
</center>
<p>Effectuons cette normalisation sur le jeu de données <code>cars</code>.</p>
<pre class="r"><code>minimums &lt;- apply(cars, MARGIN = 2, FUN = min)  # obtention des minimums par variable
maximums &lt;- apply(cars, MARGIN = 2, FUN = max)  # obtention des maximums par variable
cars_01norm &lt;- scale(cars, center = minimums, scale = maximums - minimums)
summary(cars_01norm)</code></pre>
<pre><code>##      speed             dist       
##  Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.3810   1st Qu.:0.2034  
##  Median :0.5238   Median :0.2881  
##  Mean   :0.5429   Mean   :0.3473  
##  3rd Qu.:0.7143   3rd Qu.:0.4576  
##  Max.   :1.0000   Max.   :1.0000</code></pre>
<p><strong>Note</strong> : La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/sweep.html">fonction <code>sweep</code></a> permet aussi de faire simultanément une transformation pour chacune des colonnes d’une matrice. Elle généralise en fait <code>scale</code> en permettant d’effectuer la transformation sur n’importe laquelle des dimensions d’un array. Cette fonction ne sera cependant pas approfondie ici.</p>
</div>
</div>
<div id="manipulation-de-chaines-de-caracteres" class="section level2">
<h2>Manipulation de chaînes de caractères</h2>
<p>D’un langage de programmation à l’autre, les chaînes de caractères ne sont pas manipulées de la même façon. Par exemple, si un objet R contient une chaîne de caractères telle la suivante,</p>
<pre class="r"><code>chaine &lt;- &quot;Bonjour&quot;</code></pre>
<p>il n’est pas possible d’extraire disons la deuxième lettre de la chaîne avec la commande suivante.</p>
<pre class="r"><code>chaine[2]</code></pre>
<pre><code>## [1] NA</code></pre>
<p>Cette commande aurait fonctionné en langage Python. Elle ne fonctionne pas en R, parce que l’objet <code>chaine</code> est un vecteur de longueur 1. L’opérateur d’indiçage <code>[</code> réfère à des éléments d’un objet. L’objet <code>chaine</code> ne contient qu’un seul élément, qui est une chaîne de caractères.</p>
<pre class="r"><code>str(chaine)</code></pre>
<pre><code>##  chr &quot;Bonjour&quot;</code></pre>
<pre class="r"><code>length(chaine)</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>chaine[1]</code></pre>
<pre><code>## [1] &quot;Bonjour&quot;</code></pre>
<p>Cette section initie à quelques fonctions du R de base pour manipuler des vecteurs dont les éléments sont des chaînes de caractères. Toutes ces fonctions travaillent de façon vectorielle. Elles effectuent d’un coup une opération sur tous les éléments d’un vecteur.</p>
<p>Ces fonctions seront illustrées en utilisant le data frame <code>boxoffice</code> créé dans les notes sur <a href="https://stt4230.rbind.io/manipulation_donnees/lecture_ecriture_r/">la lecture et l’écriture dans des fichiers externes à partir de R</a>. Ce data frame est composé de colonnes contenant toutes des éléments de type caractère. Il avait été créé en important des données d’une table HTML sur le web à l’aide des commandes suivantes.</p>
<pre class="r"><code>library(rvest)
url &lt;- &quot;http://pro.boxoffice.com/numbers/all_time&quot;
doc &lt;- read_html(url)
tables &lt;- html_table(doc)
boxoffice &lt;- tables[[1]]</code></pre>
<p>Pour m’assurer que tous aient accès à ces données, j’ai déposé une copie des données datant du 25 janvier 2019 dans le haut de <a href="https://stt4230.rbind.io/manipulation_donnees/pretraitement_donnees_r/">la page web des notes que vous êtes en train de lire</a>. Le fichier contenant les données est en format <code>.rds</code>, il se nomme <code>boxoffice_20190125.rds</code>. Il se trouve dans le fichier compressé <code>pretraitement_donnees_r_2019.zip</code>. Après avoir téléchargé ce fichier sur votre ordinateur, et après l’avoir décompressé pour en extraire <code>boxoffice_20190125.rds</code>, vous pouvez charger les données en R avec le code suivant (en spécifiant le bon chemin d’accès) :</p>
<pre class="r"><code>boxoffice &lt;- readRDS(&quot;C:/coursR/boxoffice_20190125.rds&quot;)</code></pre>
<p>Rappelons-nous qu’il s’agit de données concernant les recettes des films ayant générés le plus de revenus dans les cinémas américains.</p>
<pre class="r"><code>head(boxoffice, n = 3)</code></pre>
<pre><code>##   X1                                    X2           X3           X4
## 1  1 Star Wars: The Force Awakens (Disney) Dec 18, 2015 $936,662,225
## 2  2                          Avatar (Fox) Dec 18, 2009 $760,507,625
## 3  3                Black Panther (Disney) Feb 16, 2018 $700,059,566</code></pre>
<p>Les noms des colonnes du data frame ne sont pas informatifs. Renommons les colonnes du data frame en respectant les noms de colonnes dans la page web d’où il provient.</p>
<pre class="r"><code>colnames(boxoffice) &lt;- c(&quot;Ranking&quot;, &quot;Movie (Distributor)&quot;, &quot;Release Date&quot;, &quot;Gross&quot;)</code></pre>
<div id="fonction-paste" class="section level3">
<h3>Fonction <code>paste</code> :</h3>
<p>La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/paste.html">fonction <code>paste</code></a> sert à concaténer des éléments de vecteurs. Elle retourne toujours un résultat sous le format caractère. Elle n’est pas illustrée ici, car elle a été présentée dans les notes sur les <a href="https://stt4230.rbind.io/manipulation_donnees/structures_r/#les-vecteurs-de-chaines-de-caracteres">structures de données en R</a>.</p>
<p>Notons que la fonction <code>paste0</code> est en quelque sorte une version de la fonction <code>paste</code> avec l’argument <code>sep = &quot;&quot;</code> (aucun caractère comme séparation entre les chaînes de caractères à concaténer).</p>
</div>
<div id="fonction-nchar" class="section level3">
<h3>Fonction <code>nchar</code> :</h3>
<p>La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/nchar.html">fonction <code>nchar</code></a> permet de compter le nombre de caractères dans des chaînes de caractères. Elle a aussi été illustrée dans les notes sur les <a href="https://stt4230.rbind.io/manipulation_donnees/structures_r/#les-vecteurs-de-chaines-de-caracteres">structures de données en R</a>.</p>
</div>
<div id="fonctions-toupper-tolower-et-casefold" class="section level3">
<h3>Fonctions <code>toupper</code>, <code>tolower</code> et <code>casefold</code> :</h3>
<p>Les <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/chartr.html">fonctions <code>toupper</code> et <code>tolower</code></a> transforment tous les caractères alphabétiques en majuscules et en minuscules respectivement.</p>
<pre class="r"><code>extrait &lt;- boxoffice$&quot;Movie (Distributor)&quot;[1:2]
extrait</code></pre>
<pre><code>## [1] &quot;Star Wars: The Force Awakens (Disney)&quot; &quot;Avatar (Fox)&quot;</code></pre>
<pre class="r"><code>toupper(extrait)</code></pre>
<pre><code>## [1] &quot;STAR WARS: THE FORCE AWAKENS (DISNEY)&quot; &quot;AVATAR (FOX)&quot;</code></pre>
<pre class="r"><code>tolower(extrait)</code></pre>
<pre><code>## [1] &quot;star wars: the force awakens (disney)&quot; &quot;avatar (fox)&quot;</code></pre>
<p>La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/chartr.html">fonction <code>casefold</code></a>, utilisée comme exemple de fonction dans les notes sur les <a href="https://stt4230.rbind.io/introduction/base_r/#quest-ce-quune-fonction">concepts de base en R</a>, permet de faire les deux transformations de casse, soit transformer tous les caractères alphabétiques en majuscules (avec l’argument <code>upper = TRUE</code>) ou transformer tous les caractères alphabétiques en minuscules (avec l’argument <code>upper = FALSE</code>).</p>
<pre class="r"><code>casefold(extrait, upper = TRUE)</code></pre>
<pre><code>## [1] &quot;STAR WARS: THE FORCE AWAKENS (DISNEY)&quot; &quot;AVATAR (FOX)&quot;</code></pre>
<pre class="r"><code>casefold(extrait, upper = FALSE)</code></pre>
<pre><code>## [1] &quot;star wars: the force awakens (disney)&quot; &quot;avatar (fox)&quot;</code></pre>
</div>
<div id="fonction-strsplit" class="section level3">
<h3>Fonction <code>strsplit</code> :</h3>
<p>La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/strsplit.html">fonction <code>strsplit</code></a> sépare des chaînes de caractères en sous-chaînes de caractères en coupant lors de la rencontre d’une certaine sous-chaîne de caractères. Tentons d’utiliser cette fonction pour séparer le nom du film du nom du distributeur, qui se retrouvent tous deux dans la colonne <code>&quot;Movie (Distributor)&quot;</code> du data frame <code>boxoffice</code>. Demandons à <code>strsplit</code> de briser le contenu de cette colonne en deux parties : ce qui se trouve avant la parenthèse ouvrante et ce qui se trouve après. Étant donné que le nom du distributeur est toujours placé à la fin de la chaîne de caractères, entre parenthèses, nous réussirons ainsi à isoler les deux éléments.</p>

<pre class="r"><code>resSplit &lt;- strsplit(x = boxoffice$&quot;Movie (Distributor)&quot;, split = &quot;(&quot;, fixed = TRUE)
resSplit[1:2]</code></pre>
<pre><code>## [[1]]
## [1] &quot;Star Wars: The Force Awakens &quot; &quot;Disney)&quot;                      
## 
## [[2]]
## [1] &quot;Avatar &quot; &quot;Fox)&quot;</code></pre>
<p>Par défaut, la fonction considère que la valeur donnée a l’argument <code>split</code> est une <a href="https://fr.wikipedia.org/wiki/Expression_r%C3%A9guli%C3%A8re">expression régulière</a>. Les expressions régulières ne seront pas vues ici. Elles constituent un moyen puissant pour effectuer des recherches dans des chaînes de caractères. L’argument <code>fixed = TRUE</code> demande à <code>strsplit</code> de ne pas considérer l’argument <code>split</code> comme une expression régulière, mais bien de traiter la chaîne de caractères telle qu’elle a été fournie.</p>
<p>Le résultat de la fonction <code>strsplit</code> est toujours une liste de la même longueur que le vecteur assigné à l’argument <code>x</code>. Chaque élément de la liste est un vecteur comprenant les sous-chaînes de caractères obtenues de la séparation. Ici, ces vecteurs ont le plus souvent une longueur de 2. Par exemple pour le premier film du jeu de données, Star Wars: The Force Awakens (Disney), on obtient le vecteur <code>[&quot;Star Wars: The Force Awakens &quot;, &quot;Disney)&quot;]</code>. Par contre, certains titres de film comprennent un élément entre parenthèses de plus, par exemple <code>&quot;The Lion King (1994) (Disney)&quot;</code>. Pour eux, la longueur du vecteur est 3.</p>
<p>La commande suivante permet d’extraire le dernier élément de chacun des vecteurs se trouvant dans <code>resSplit</code>. Elle utilise la fonction <code>sapply</code> vue dans le cours sur les <a href="https://stt4230.rbind.io/calculs/calculs_base_r/#fonctions-lapply-sapply-et-mapply">calculs de base en R</a>.</p>
<pre class="r"><code>distributeur &lt;- sapply(resSplit, tail, n = 1)
distributeur[1:2]</code></pre>
<pre><code>## [1] &quot;Disney)&quot; &quot;Fox)&quot;</code></pre>
</div>
<div id="fonction-substr" class="section level3">
<h3>Fonction <code>substr</code> :</h3>
<p>Afin d’avoir vraiment isolé le nom du distributeur, il ne reste plus qu’à retirer la parenthèse à la fin des chaînes de caractères dans <code>distributeur</code>. La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/substr.html">fonction <code>substr</code></a> permet d’extraire une partie de chaînes de caractères en spécifiant les positions, dans les chaînes, des caractères à conserver.</p>
<pre class="r"><code>distributeur &lt;- substr(x = distributeur, start = 1, stop = nchar(distributeur) - 1)
distributeur[1:2]</code></pre>
<pre><code>## [1] &quot;Disney&quot; &quot;Fox&quot;</code></pre>
<p>Ici nous voulons extraire les caractères de la première position jusqu’à l’avant-dernière position. Celle-ci varie d’une observation à l’autre, c’est pourquoi nous utilisons l’expression <code>nchar(distributeur) - 1</code> pour la calculer.</p>
</div>
<div id="fonctions-sub-et-gsub" class="section level3">
<h3>Fonctions <code>sub</code> et <code>gsub</code> :</h3>
<p>Voyons maintenant comment il est possible de remplacer une sous-chaîne de caractères par une autre. Dans les données <code>boxoffice</code>, les recettes des films comprennent un signe de dollar au début, ainsi que des virgules pour séparer les milliers. À cause de ces caractères, cette colonne ne peut pas être transformée sous un format numérique directement. Nous allons donc retirer ces caractères en les remplaçant par des chaînes de caractères vides. Ensuite, nous pourrons convertir le vecteur au format numérique plutôt que caractère.</p>
<pre class="r"><code>recettes &lt;- boxoffice$Gross
str(recettes)</code></pre>
<pre><code>##  chr [1:1000] &quot;$936,662,225&quot; &quot;$760,507,625&quot; &quot;$700,059,566&quot; ...</code></pre>
<pre class="r"><code>recettes &lt;- sub(pattern = &quot;$&quot;, replacement = &quot;&quot;, x = recettes, fixed = TRUE)
str(recettes)</code></pre>
<pre><code>##  chr [1:1000] &quot;936,662,225&quot; &quot;760,507,625&quot; &quot;700,059,566&quot; &quot;678,815,482&quot; ...</code></pre>
<pre class="r"><code>recettes &lt;- gsub(pattern = &quot;,&quot;, replacement = &quot;&quot;, x = recettes, fixed = TRUE)
str(recettes)</code></pre>
<pre><code>##  chr [1:1000] &quot;936662225&quot; &quot;760507625&quot; &quot;700059566&quot; &quot;678815482&quot; ...</code></pre>
<pre class="r"><code>recettes &lt;- as.numeric(recettes)
str(recettes)</code></pre>
<pre><code>##  num [1:1000] 9.37e+08 7.61e+08 7.00e+08 6.79e+08 6.59e+08 ...</code></pre>
<p>Il est maintenant possible de faire des calculs numériques sur les recettes des films, puisqu’elles sont stockées sous un format numérique.</p>
<p>Les <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/grep.html">fonctions <code>sub</code> et <code>gsub</code></a> servent donc à chercher les occurrences d’un « motif » (argument <code>pattern</code>) dans des chaînes de caractères (argument <code>x</code>), puis à remplacer ces occurrences par un autre motif (argument <code>replacement</code>). La fonction <code>sub</code> remplace seulement la première occurrence de <code>pattern</code>, alors que la fonction <code>gsub</code> remplace toutes les occurrences. Tout comme la fonction <code>strsplit</code>, les fonctions <code>sub</code> et <code>gsub</code> travaillent par défaut avec des motifs exprimés sous forme d’expressions régulières. L’argument <code>fixed = TRUE</code> empêche ce comportement et implique le traitement des motifs comme des chaînes de caractères.</p>
</div>
<div id="fonctions-grep-et-grepl" class="section level3">
<h3>Fonctions <code>grep</code> et <code>grepl</code> :</h3>
<p>Supposons que nous désirions avoir une variable logique prenant la valeur <code>TRUE</code> si la compagnie Disney a distribué le film, <code>FALSE</code> sinon. Nous pourrions utiliser la fonction <code>grepl</code> comme suit pour obtenir cette variable.</p>
<pre class="r"><code>Disney &lt;- grepl(pattern = &quot;Disney&quot;, x = distributeur, fixed = TRUE)
sum(Disney)</code></pre>
<pre><code>## [1] 161</code></pre>
<p>Ainsi, 161 des 1000 films du jeu de données <code>boxoffice</code> ont été distribués par Disney.</p>
<p>Les <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/grep.html">fonctions <code>grep</code> et <code>grepl</code></a> identifient les éléments d’un vecteur de chaînes de caractères (argument <code>x</code>) contenant un certain « motif » (argument <code>pattern</code>). Pour ne pas que ce motif soit traité comme une expression régulière, il faut fournir la valeur <code>TRUE</code> à l’argument <code>fixed</code>. La fonction <code>grep</code> retourne un vecteur numérique contenant les positions dans <code>x</code> des éléments possédant le motif. Comme nous l’avons constaté dans l’exemple précédent, la fonction <code>grepl</code> retourne pour sa part un vecteur logique aussi long que <code>x</code>, contenant la valeur <code>TRUE</code> pour les éléments possédant le motif, <code>FALSE</code> sinon.</p>
<p>Les fonctions <code>sub</code>, <code>gsub</code>, <code>grep</code> et <code>grepl</code> sont toutes documentées dans la même fiche d’aide : <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/grep.html">celle de la fonction <code>grep</code></a>. Quelques autres fonctions de manipulation de chaînes de caractères sont documentées dans cette fiche, mais ne sont pas présentées ici.</p>
</div>
<div id="fonction-chartr" class="section level3">
<h3>Fonction <code>chartr</code> :</h3>
<p>Lorsque nous avons besoin de remplacer une série de caractères par d’autres (chaque caractère de la série ayant une valeur de remplacement spécifique), il est possible de procéder en appelant la fonction <code>gsub</code> séparément pour chaque caractère de la série. Il existe cependant une façon de faire plus rapide : utiliser la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/chartr.html">fonction <code>chartr</code></a>. Il faut fournir à cette fonction une chaîne de caractères comprenant tous les caractères à traduire (argument <code>old</code>). Il faut aussi lui fournir une chaîne de caractères comprenant tous les caractères de remplacement (argument <code>new</code>), en respectant l’ordre des caractères dans le premier vecteur. Finalement, il faut fournir à <code>chartr</code> le vecteur des chaînes de caractères dans lesquelles effectuer les remplacements.</p>
<p>Par exemple, la commande suivante permet de retirer les accents français d’un vecteur de chaînes de caractères.</p>
<pre class="r"><code>chartr(old = &quot;ÀÂÇÈÉÊËÎÏÔÙÛÜàâçèéêëîïôùûü&quot;,
       new = &quot;AACEEEEIIOUUUaaceeeeiiouuu&quot;,
       x = c(&quot;François va à l&#39;École des Pionniers.&quot;, &quot;Où est situé cette école?&quot;))</code></pre>
<pre><code>## [1] &quot;Francois va a l&#39;Ecole des Pionniers.&quot; &quot;Ou est situe cette ecole?&quot;</code></pre>
</div>
<div id="fonction-iconv" class="section level3">
<h3>Fonction <code>iconv</code> :</h3>
<p>Pour la tâche spécifique de retirer des accents, il est en fait encore plus simple d’utiliser la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/iconv.html">fonction <code>iconv</code></a>. Celle-ci permet de convertir l’encodage de chaîne de caractères. Un bon truc pour retirer des accents de chaînes de caractères, peu importe la langue utilisée dans ces chaînes, est de convertir vers l’encodage <code>&quot;ASCII//TRANSLIT&quot;</code>. Voici un exemple.</p>
<pre class="r"><code>iconv(c(&quot;François va à l&#39;École des Pionniers.&quot;, &quot;Où est situé cette école?&quot;), 
      to = &quot;ASCII//TRANSLIT&quot;)</code></pre>
<pre><code>## [1] &quot;Francois va a l&#39;Ecole des Pionniers.&quot; &quot;Ou est situe cette ecole?&quot;</code></pre>
<p>La sortie de cette commande peut varier d’un système d’exploitation à l’autre à l’autre.</p>
</div>
</div>
<div id="manipulation-de-dates" class="section level2">
<h2>Manipulation de dates</h2>
<p>Une des variables de <code>boxoffice</code> est une date : la variable <code>&quot;Release Date&quot;</code> contenant la date de sortie des films. Elle est pour l’instant stockée sous format caractère.</p>
<pre class="r"><code>str(boxoffice$&quot;Release Date&quot;)</code></pre>
<pre><code>##  chr [1:1000] &quot;Dec 18, 2015&quot; &quot;Dec 18, 2009&quot; &quot;Feb 16, 2018&quot; ...</code></pre>
<p>Nous pourrions vouloir compter le nombre d’années écoulées depuis la sortie des films. Pour ce faire, le plus simple est d’utiliser un format de date proposé par R.</p>
<div id="fonctions-as.date-et-sys.getlocale" class="section level3">
<h3>Fonctions <code>as.Date</code> et <code>Sys.getlocale</code></h3>
<p>Nous allons convertir les données dans la colonne <code>&quot;Release Date&quot;</code> dans un format date de R avec la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/as.Date.html">fonction <code>as.Date</code></a>. Cependant, cette conversion fonctionnera uniquement si les paramètres régionaux (en anglais <em>locale</em>) de notre session R sont en anglais, puisque les dates comportent des abréviations de noms de mois en anglais. Ainsi, commençons par vérifier quel paramètre régional pour le temps utilise notre session R avec la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/locales.html">fonction <code>Sys.getlocale</code></a>.</p>
<pre class="r"><code>Sys.getlocale(category = &quot;LC_TIME&quot;)</code></pre>
<pre><code>## [1] &quot;English_Canada.1252&quot;</code></pre>
<p>Dans mon cas, j’utilise un système d’exploitation en anglais. En conséquence, les paramètres régionaux de mes sessions R sont par défaut en anglais. Si ce n’est pas votre cas, il faut d’abord changer le paramètre <code>&quot;LC_TIME&quot;</code> de votre session R pour qu’il s’agisse de l’anglais. Sous Windows, vous pouvez procéder comme suit.</p>
<pre class="r"><code># Sous Windows
Sys.setlocale(&quot;LC_TIME&quot;, locale = &quot;English&quot;)</code></pre>
<p>Les valeurs comprises comme argument <code>locale</code> dépendent du système d’exploitation. Sous un système d’exploitation Mac OS X / OS X / macOS ou Unix / Linux, tentez une des valeurs suivantes : <code>&quot;en_CA&quot;</code>, <code>&quot;en_CA.UTF-8&quot;</code> ou <code>en_CA.utf8</code> (ou la version US de ces valeurs, soit <code>&quot;en_US&quot;</code>, <code>&quot;en_US.UTF-8&quot;</code> ou <code>en_US.utf8</code>).</p>
<pre class="r"><code># Sous Mac OS X / OS X / macOS
Sys.setlocale(&quot;LC_TIME&quot;, locale = &quot;en_CA.UTF-8&quot;)</code></pre>
<p>Une fois s’être assuré d’avoir un paramètre <code>&quot;LC_TIME&quot;</code> en anglais, nous pouvons appeler la fonction <code>as.Date</code> comme suit.</p>
<pre class="r"><code>boxoffice$Date &lt;- as.Date(boxoffice$&quot;Release Date&quot;, format = &quot;%b %d, %Y&quot;)
str(boxoffice[, c(&quot;Release Date&quot;, &quot;Date&quot;)])</code></pre>
<pre><code>## &#39;data.frame&#39;:    1000 obs. of  2 variables:
##  $ Release Date: chr  &quot;Dec 18, 2015&quot; &quot;Dec 18, 2009&quot; &quot;Feb 16, 2018&quot; &quot;Apr 27, 2018&quot; ...
##  $ Date        : Date, format: &quot;2015-12-18&quot; &quot;2009-12-18&quot; ...</code></pre>
<pre class="r"><code>head(boxoffice[, -c(1,4)])</code></pre>
<pre><code>##                     Movie (Distributor) Release Date       Date
## 1 Star Wars: The Force Awakens (Disney) Dec 18, 2015 2015-12-18
## 2                          Avatar (Fox) Dec 18, 2009 2009-12-18
## 3                Black Panther (Disney) Feb 16, 2018 2018-02-16
## 4       Avengers: Infinity War (Disney) Apr 27, 2018 2018-04-27
## 5                   Titanic (Paramount) Dec 19, 1997 1997-12-19
## 6            Jurassic World (Universal) Jun 12, 2015 2015-06-12</code></pre>
</div>
<div id="fonctions-difftime-et-sys.date" class="section level3">
<h3>Fonctions <code>difftime</code> et <code>Sys.Date</code></h3>
<p>Pour calculer le nombre d’années entre aujourd’hui et la date de sortie des films, tentons d’utiliser la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/difftime.html">fonction <code>difftime</code></a>. D’abord, obtenons la date courante avec la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/Sys.time.html">fonction <code>Sys.Date</code></a>.</p>
<pre class="r"><code>aujourdui &lt;- Sys.Date()
aujourdui</code></pre>
<pre><code>## [1] &quot;2019-01-25&quot;</code></pre>
<p>Ensuite, demandons à <code>difftime</code> de calculer la différence, en années, entre aujourd’hui et les dates de sortie des films.</p>
<pre class="r"><code>boxoffice$Age &lt;- difftime(aujourdui, boxoffice$Date, units = &quot;years&quot;)</code></pre>
<pre><code>## Error in match.arg(units) : 
##   &#39;arg&#39; should be one of “auto”, “secs”, “mins”, “hours”, “days”, “weeks”</code></pre>
<p>La fonction <code>difftime</code> ne calcule pas de différence entre des dates en années, d’où l’erreur obtenue. Elle peut cependant calculer cette différence en jours ou en semaines (aussi en secondes, minutes ou heures si les dates comprennent aussi une heure). Pour faire un calcul approximatif, mais presque exact, du nombre d’années écoulées entre aujourd’hui et la sortie des films, nous pourrions d’abord calculer le temps écoulé en jours. Ensuite, nous pourrions diviser ce nombre de jours par 365.25 jours, soit le nombre moyen de jours dans une année.</p>
<pre class="r"><code>boxoffice$Age &lt;- as.numeric(difftime(aujourdui, boxoffice$Date, units = &quot;days&quot;) / 365.25)
head(boxoffice[, -c(1,4)])</code></pre>
<pre><code>##                     Movie (Distributor) Release Date       Date        Age
## 1 Star Wars: The Force Awakens (Disney) Dec 18, 2015 2015-12-18  3.1047228
## 2                          Avatar (Fox) Dec 18, 2009 2009-12-18  9.1033539
## 3                Black Panther (Disney) Feb 16, 2018 2018-02-16  0.9390828
## 4       Avengers: Infinity War (Disney) Apr 27, 2018 2018-04-27  0.7474333
## 5                   Titanic (Paramount) Dec 19, 1997 1997-12-19 21.1006160
## 6            Jurassic World (Universal) Jun 12, 2015 2015-06-12  3.6221766</code></pre>
<p>Cet âge est presque exact. Cependant, il y a une petite erreur due au fait que nous ne savons pas combien il y a eu d’années bissextiles entre aujourd’hui et la date de sortie des films. Une année ne comporte pas 365.25 jours, mais bien 365 ou 366 jours.</p>
</div>
<div id="fonction-format" class="section level3">
<h3>Fonction <code>format</code></h3>
<p>Une date peut se présenter sous plusieurs formats, explicités dans la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/strptime.html">fiche d’aide nommée <code>strptime</code></a>.</p>
<pre class="r"><code>help(strptime)</code></pre>
<p>Grâce à ces différents formats, nous pourrions par exemple extraire le mois de sortie d’un film grâce à la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/strptime.html">fonction <code>format</code></a> comme suit.</p>
<pre class="r"><code>boxoffice$Month &lt;- as.integer(format(boxoffice$Date, &quot;%m&quot;))</code></pre>
<p>Voyons ce que ça donne.</p>
<pre class="r"><code>head(boxoffice[, -c(1,4)])</code></pre>
<pre><code>##                     Movie (Distributor) Release Date       Date        Age Month
## 1 Star Wars: The Force Awakens (Disney) Dec 18, 2015 2015-12-18  3.1047228    12
## 2                          Avatar (Fox) Dec 18, 2009 2009-12-18  9.1033539    12
## 3                Black Panther (Disney) Feb 16, 2018 2018-02-16  0.9390828     2
## 4       Avengers: Infinity War (Disney) Apr 27, 2018 2018-04-27  0.7474333     4
## 5                   Titanic (Paramount) Dec 19, 1997 1997-12-19 21.1006160    12
## 6            Jurassic World (Universal) Jun 12, 2015 2015-06-12  3.6221766     6</code></pre>
<p> </p>
<p><strong>Note</strong> : Il existe d’autres formats de date en R permettant d’inclure l’heure : <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/DateTimeClasses.html"><code>&quot;POSIXlt&quot;</code> et <code>&quot;POSIXct&quot;</code></a>, mais nous n’approfondirons pas ces formats. Seule une petite partie des possibilités de manipulation de dates en R est abordée ici.</p>
<hr />
</div>
</div>
</div>
<div id="manipulation-de-jeux-de-donnees" class="section level1">
<h1>Manipulation de jeux de données</h1>
<p>Nous venons de voir différentes façons de manipuler des variables dans un jeu de données sous forme de data frame. Voyons maintenant différentes manipulations usuelles de jeux de données entiers, soit :</p>
<ul>
<li>la fusion de plusieurs jeux de données,</li>
<li>la modification de l’ordre des observations ou des variables dans un jeu de données,</li>
<li>la modification de la mise en forme de jeux de données.</li>
</ul>
<p>Pour illustrer des manipulations, reprenons le data frame <code>dataEx</code> créé dans le cours <a href="https://stt4230.rbind.io/manipulation_donnees/lecture_ecriture_r/#lecture-de-fichiers">Lecture et écriture dans des fichiers externes à partir de R</a> afin d’illustrer quelques mises en forme de jeux de données.</p>
<pre class="r"><code>de1 &lt;- c(2,3,4,1,2,3,5,6,5,4)
de2 &lt;- c(1,4,2,3,5,4,6,2,5,3)
lanceur &lt;- rep(c(&quot;Luc&quot;, &quot;Kim&quot;), each = 5)
dataEx &lt;- data.frame(de1, de2, lanceur)
# Introduction de valeurs manquantes
dataEx$de2[7] &lt;- NA
dataEx$lanceur[3] &lt;- NA
# Affichage du date frame
dataEx</code></pre>
<pre><code>##    de1 de2 lanceur
## 1    2   1     Luc
## 2    3   4     Luc
## 3    4   2    &lt;NA&gt;
## 4    1   3     Luc
## 5    2   5     Luc
## 6    3   4     Kim
## 7    5  NA     Kim
## 8    6   2     Kim
## 9    5   5     Kim
## 10   4   3     Kim</code></pre>
<div id="fusion-de-donnees" class="section level2">
<h2>Fusion de données</h2>
<p>Fusionner des données signifie ici de mettre en commun deux jeux de données ou plus en un seul jeu de données. Une fusion peut être une simple concaténation, c’est-à-dire une mise bout à bout de lignes ou de colonnes. Elle peut aussi être réalisée par association en tenant compte des observations dans des variables en commun dans les jeux de données à fusionner.</p>
<div id="concatenation-dobservations-lignes" class="section level3">
<h3>Concaténation d’observations (lignes)</h3>
<p>Supposons que nous avons en main deux jeux de données contenant différentes observations pour les mêmes variables. Par exemple, en plus du data frame <code>dataEx</code>, disons que nous avons les observations supplémentaires suivantes.</p>
<pre class="r"><code>supp &lt;- data.frame(de1 = c(2,5), de2 = c(5, 6), lanceur = c(&quot;Luc&quot;, &quot;Kim&quot;))
supp</code></pre>
<pre><code>##   de1 de2 lanceur
## 1   2   5     Luc
## 2   5   6     Kim</code></pre>
<p>Pour concaténer les jeux de données <code>dataEx</code> et <code>supp</code> en un seul jeu de données, nous pourrions utiliser la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/cbind.html">fonction <code>rbind</code></a> comme suit :</p>
<pre class="r"><code>rbind(dataEx, supp)</code></pre>
<pre><code>##    de1 de2 lanceur
## 1    2   1     Luc
## 2    3   4     Luc
## 3    4   2    &lt;NA&gt;
## 4    1   3     Luc
## 5    2   5     Luc
## 6    3   4     Kim
## 7    5  NA     Kim
## 8    6   2     Kim
## 9    5   5     Kim
## 10   4   3     Kim
## 11   2   5     Luc
## 12   5   6     Kim</code></pre>
<p>Il serait maintenant judicieux d’assigner cette concaténation à un nom afin de conserver le résultat obtenu dans un objet. Si nous assignions cet appel à <code>rbind</code> au nom <code>dataEx</code>, nous nous retrouverions à ajouter des observations (soit des lignes) à <code>dataEx</code>. Nous pourrions aussi créer un nouvel objet pour stocker le résultat de la concaténation.</p>
<p><strong>Attention</strong> : Lors d’une concaténation d’observations, il faut manuellement s’assurer que les colonnes des data frames concaténés correspondent (mêmes variables, dans le même ordre).</p>
</div>
<div id="concatenation-de-variables-colonnes" class="section level3">
<h3>Concaténation de variables (colonnes)</h3>
<p>Lorsque nous avons ajouté des variables à un jeu de données dans la section précédente, nous avons réalisé une forme de concaténation de jeux de données en colonnes. Voici une copie de l’exemple réalisé</p>
<pre class="r"><code>cars2 &lt;- cars  # pour repartir avec la version originale du jeu de données
cars2 &lt;- data.frame(cars2, dist_m = cars2$dist * 0.3048)</code></pre>
<p>Dans cette forme de concaténation, le deuxième jeu de données fusionné est constitué d’une seule variable, stockée dans un vecteur, et le résultat de la concaténation remplace le premier jeu de données fusionné.</p>
<p>La concaténation de variables peut être plus générale que ça. Nous pourrions concaténer deux jeux de données contenant chacun plus d’une variable et stocker le résultat de la concaténation dans un nouvel objet.</p>
<p>Par exemple, disons que nous avons un jeu de données contenant des informations sur les lanceurs de dés du jeu de données <code>dataEx</code>.</p>
<pre class="r"><code>dataExLanceurs &lt;- data.frame(lateralite = rep(c(&quot;gaucher&quot;, &quot;droitier&quot;), each = 5),
                             age = rep(c(22, 51), each = 5))
dataExLanceurs</code></pre>
<pre><code>##    lateralite age
## 1     gaucher  22
## 2     gaucher  22
## 3     gaucher  22
## 4     gaucher  22
## 5     gaucher  22
## 6    droitier  51
## 7    droitier  51
## 8    droitier  51
## 9    droitier  51
## 10   droitier  51</code></pre>
<p>Pour concaténer en colonnes les jeux de données <code>dataEx</code> et <code>dataExLanceurs</code>, nous pourrions utiliser la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/cbind.html">fonction <code>cbind</code></a> ou <code>data.frame</code> comme suit.</p>
<pre class="r"><code>cbind(dataEx, dataExLanceurs)</code></pre>
<pre class="r"><code>data.frame(dataEx, dataExLanceurs)</code></pre>
<pre><code>##    de1 de2 lanceur lateralite age
## 1    2   1     Luc    gaucher  22
## 2    3   4     Luc    gaucher  22
## 3    4   2    &lt;NA&gt;    gaucher  22
## 4    1   3     Luc    gaucher  22
## 5    2   5     Luc    gaucher  22
## 6    3   4     Kim   droitier  51
## 7    5  NA     Kim   droitier  51
## 8    6   2     Kim   droitier  51
## 9    5   5     Kim   droitier  51
## 10   4   3     Kim   droitier  51</code></pre>
<p>Le résultat de la concaténation pourrait être assigné à un nom d’objet R existant ou à un nouveau nom, créant du coup un nouvel objet.</p>
</div>
<div id="fusion-par-association---la-fonction-merge" class="section level3">
<h3>Fusion par association - la fonction <code>merge</code></h3>
<p>Une concaténation de variables crée un jeu de données utile seulement si les lignes dans les jeux de données concaténés sont associées aux mêmes individus, dans le même ordre. Par exemple, le résultat que nous venons d’obtenir nous porte à croire que Luc est gaucher et qu’il a 22 ans, et que Kim est droitière et à 51 ans. Mais rien dans le jeu de données <code>dataExLanceurs</code> ne nous disait quelles caractéristiques correspondaient à quels lanceurs. Et la ligne 3 de ce jeu de données est surprenante. Le nom du lanceur est manquant, mais la latéralité et l’âge du lanceur sont connus.</p>
<p>Avec une fusion par concaténation de variables, les risques d’erreurs sont grands. Il est plus prudent de fusionner des jeux de données en s’assurant de spécifier à quel individu (ou unité statistique) réfère chaque ligne, et ce, pour chaque jeu de données. Une fusion par association peut s’effectuer en R avec la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/merge.html">fonction <code>merge</code></a>.</p>
<p>Fusionner des jeux de données par association signifie de mettre en commun des observations de certaines variables en associant correctement les observations selon l’individu auquel elles réfèrent.</p>
<p>Dans l’exemple précédent, nous aurions préféré fusionner le jeu de données <code>dataEx</code> au jeu de données suivant.</p>
<pre class="r"><code>lanceurs &lt;- data.frame(lanceur = c(&quot;Luc&quot;, &quot;Kim&quot;),
                       lateralite = c(&quot;gaucher&quot;, &quot;droitier&quot;),
                       age = c(22, 51))
lanceurs</code></pre>
<pre><code>##   lanceur lateralite age
## 1     Luc    gaucher  22
## 2     Kim   droitier  51</code></pre>
<p>Ce jeu de données indique clairement à quel lanceur sont associées les différentes caractéristiques.</p>
<p>Un fusion par association selon la valeur de la variable <code>lanceur</code> entre les data frames <code>dataEx</code> et <code>lanceurs</code> permettrait d’ajouter des colonnes pour la latéralité et l’âge du lanceur à <code>dataEx</code> de façon plus intelligente et moins risquée que précédemment.</p>
<pre class="r"><code>merge(dataEx, lanceurs, by = &quot;lanceur&quot;, all = TRUE, sort = FALSE)</code></pre>
<pre><code>##    lanceur de1 de2 lateralite age
## 1      Luc   2   1    gaucher  22
## 2      Luc   3   4    gaucher  22
## 3      Luc   1   3    gaucher  22
## 4      Luc   2   5    gaucher  22
## 5      Kim   3   4   droitier  51
## 6      Kim   5  NA   droitier  51
## 7      Kim   6   2   droitier  51
## 8      Kim   5   5   droitier  51
## 9      Kim   4   3   droitier  51
## 10    &lt;NA&gt;   4   2       &lt;NA&gt;  NA</code></pre>
<p>Ici, les deux jeux de données fusionnés contenaient une seule colonne de même nom. La fonction <code>merge</code> aurait donc pu identifier par défaut cette colonne comme étant celle à considérer dans l’association et l’argument <code>by</code> n’aurait pas été nécessaire. Si la ou les colonnes identifiants les individus n’avaient pas porté les mêmes noms dans les deux jeux de données, nous aurions dû spécifier les arguments <code>by.x</code> et <code>by.y</code>.</p>
<p>L’argument <code>sort</code> permet de spécifier à <code>merge</code> si les observations doivent être ordonnées dans la sortie (par défaut elles le sont) selon les valeurs des variables spécifiées dans <code>by</code> (ou <code>by.x</code> et <code>by.y</code>). Dans l’exemple, malgré l’emploi de <code>sort = FALSE</code>, nous constatons que l’observation avec un nom de lanceur manquant a été placée à la fin. Cependant, les observations avec un nom de lanceur non manquant n’ont bel et bien pas été ordonnées.</p>
<p>L’argument <code>all</code> permet quant à lui de spécifier à <code>merge</code> quelles observations doivent être conservées dans la sortie. Par défaut, seules les observations présentes dans les deux jeux de données, ou ne contenant pas de valeurs manquantes pour les variables spécifiées dans <code>by</code>, sont conservées. Selon la <a href="https://en.wikipedia.org/wiki/Join_(SQL)">terminologie des bases de données relationnelles</a>, la fonction <code>merge</code> effectue par défaut une jointure interne (en anglais <em>inner join</em>). Dans l’exemple, nous avons plutôt spécifié <code>all = TRUE</code> afin de conserver toutes les observations des deux jeux de données. Nous avons donc effectué une jointure externe complète (en anglais <em>full outer join</em>). Avec les arguments <code>all.x</code> et <code>all.y</code>, nous aurions aussi pu effectuer des jointure externe gauche ou droite (en anglais <em>left or right outer join</em>).</p>
</div>
</div>
<div id="modification-de-lordre-des-donnees" class="section level2">
<h2>Modification de l’ordre des données</h2>
<p>Il existe différentes fonctions en R pour ordonner les éléments d’un objet.</p>
<div id="fonction-rev" class="section level3">
<h3>Fonction <code>rev</code> :</h3>
<p>Une des fonctions les plus simples pour effectuer un réordonnancement d’éléments est la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/rev.html">fonction <code>rev</code></a>, qui renverse l’ordre des éléments d’un vecteur (ou un facteur).</p>
<pre class="r"><code>dataEx$de1</code></pre>
<pre><code>##  [1] 2 3 4 1 2 3 5 6 5 4</code></pre>
<pre class="r"><code>rev(dataEx$de1)</code></pre>
<pre><code>##  [1] 4 5 6 5 3 2 1 4 3 2</code></pre>
</div>
<div id="fonction-sort" class="section level3">
<h3>Fonction <code>sort</code> :</h3>
<p>Pour effectuer le réordonnancement des éléments d’un vecteur (ou un facteur) selon les valeurs des données en éléments, de façon à replacer les éléments en ordre croissant ou décroissant de valeur, il faut plutôt utiliser la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/sort.html">fonction <code>sort</code></a>. Par exemple, ordonnons des valeurs numériques en ordre décroissant.</p>
<pre class="r"><code>dataEx$de1</code></pre>
<pre><code>##  [1] 2 3 4 1 2 3 5 6 5 4</code></pre>
<pre class="r"><code>sort(dataEx$de1, decreasing = TRUE)</code></pre>
<pre><code>##  [1] 6 5 5 4 4 3 3 2 2 1</code></pre>
<p>Par défaut, l’ordre croissant est retourné. Alors pour obtenir un ordre décroissant, il faut spécifier <code>decreasing = TRUE</code>.</p>
<p>Nous avons vu dans les notes sur les <a href="https://stt4230.rbind.io/calculs/calculs_base_r/#operateurs-de-comparaison">calculs de base en R</a> comment connaître l’ordre utilisé par notre session R pour classer des caractères. Il suffit de fournir à la fonction <code>sort</code> un vecteur contenant tous les caractères possibles, par exemple comme suit (des caractères sont potentiellement manquants ici).</p>
<pre class="r"><code>caracteres_speciaux &lt;- 
  c(&quot;!&quot;, &quot;\&quot;&quot;, &quot;#&quot;, &quot;$&quot;, &quot;%&quot;, &quot;&amp;&quot;, &quot;&#39;&quot;, &quot;(&quot;, &quot;)&quot;, &quot;*&quot;, &quot;+&quot;, &quot;,&quot;, &quot;-&quot;, &quot;.&quot;, &quot;/&quot;, &quot;:&quot;, &quot;;&quot;, 
    &quot;&lt;&quot;, &quot;=&quot;,&quot;&gt;&quot;, &quot;?&quot;, &quot;@&quot;, &quot;[&quot;, &quot;\\&quot;, &quot;]&quot;, &quot;^&quot;, &quot;_&quot;, &quot;{&quot;, &quot;|&quot;, &quot;}&quot;, &quot;~&quot;)
lettres_accentuees &lt;- c(&quot;à&quot;, &quot;â&quot;, &quot;é&quot;, &quot;è&quot;, &quot;ê&quot;, &quot;ë&quot;, &quot;ï&quot;, &quot;î&quot;, &quot;ô&quot;, &quot;ù&quot;, &quot;ü&quot;, &quot;û&quot;, &quot;ç&quot;)
catacteres_ordonnes &lt;- sort(c(caracteres_speciaux, 0:9, letters, LETTERS, 
                              lettres_accentuees, toupper(lettres_accentuees))) 
paste(catacteres_ordonnes, collapse = &quot;&quot;)</code></pre>
<p>Dans cette commande, l’appel à la fonction <code>paste</code> sert uniquement à raccourcir la sortie en mettant bout à bout les caractères ordonnés dans une seule chaîne de caractères. J’obtiens le résultat suivant, qui sera peut-être différent sur votre ordinateur si vous n’avez pas les mêmes paramètres régionaux que moi.</p>
<pre><code>&quot;&#39;-!\&quot;#$%&amp;()*,./:;?@[\\]^_{|}~+&lt;=&gt;0123456789aAàÀâÂbBcCçÇdDeEéÉèÈêÊëËfFgGhHiIîÎïÏjJkKlLmM
nNoOôÔpPqQrRsStTuUùÙûÛüÜvVwWxXyYzZ&quot;</code></pre>
<p>Ordonnons en ordre alphabétique croissant les noms des lanceurs dans le jeu de données <code>dataEx</code>.</p>
<pre class="r"><code>dataEx$lanceur</code></pre>
<pre><code>##  [1] Luc  Luc  &lt;NA&gt; Luc  Luc  Kim  Kim  Kim  Kim  Kim 
## Levels: Kim Luc</code></pre>

<pre class="r"><code>sort(dataEx$lanceur)</code></pre>
<pre><code>## [1] Kim Kim Kim Kim Kim Luc Luc Luc Luc
## Levels: Kim Luc</code></pre>
<p>Remarquons que la valeur manquante est omise dans la sortie. C’est le comportement par défaut de la fonction <code>sort</code>. Pour forcer <code>sort</code> à inclure les valeurs manquantes dans la sortie, il faut lui dire où les placer avec l’argument <code>na.last</code> comme suit.</p>
<pre class="r"><code>sort(dataEx$lanceur, na.last = TRUE)</code></pre>
<pre><code>##  [1] Kim  Kim  Kim  Kim  Kim  Luc  Luc  Luc  Luc  &lt;NA&gt;
## Levels: Kim Luc</code></pre>
</div>
<div id="fonction-order" class="section level3">
<h3>Fonction <code>order</code> :</h3>
<p>Pour modifier l’ordre des observations ou des variables dans un jeu de données R, la <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/order.html">fonction <code>order</code></a> est utile. Elle permet d’obtenir un vecteur d’indice des observations dans l’ordre désiré.</p>
<p>Par exemple, pour ordonner les observations du jeu de données <code>dataEx</code> en ordre croissant de la valeur de la variable <code>de1</code>,</p>
<pre class="r"><code>dataEx$de1</code></pre>
<pre><code>##  [1] 2 3 4 1 2 3 5 6 5 4</code></pre>
<p>nous devons d’abord obtenir le vecteur d’indices suivant avec la fonction <code>order</code> :</p>
<pre class="r"><code>permutation &lt;- order(dataEx$de1)
permutation</code></pre>
<pre><code>##  [1]  4  1  5  2  6  3 10  7  9  8</code></pre>
<p>Ce vecteur s’interprète comme suit : la plus petite valeur de <code>dataEx$de1</code> se trouve en position 4 (valeur 1), les deuxièmes plus petites (valeur 2 qui revient 2 fois) se trouvent dans les positions 1 et 5, …, la plus grande valeur (6) se trouve en position 8. Ensuite, il suffit de fournir ce vecteur à un l’opérateur d’indiçage <code>[</code> pour réordonner les lignes de <code>dataEx</code>.</p>
<pre class="r"><code>dataEx[permutation, ]</code></pre>
<pre><code>##    de1 de2 lanceur
## 4    1   3     Luc
## 1    2   1     Luc
## 5    2   5     Luc
## 2    3   4     Luc
## 6    3   4     Kim
## 3    4   2    &lt;NA&gt;
## 10   4   3     Kim
## 7    5  NA     Kim
## 9    5   5     Kim
## 8    6   2     Kim</code></pre>
<p>Notons que nous aurions pu jumeler l’appel à <code>order</code> à l’appel à <code>[</code> comme suit :</p>
<pre class="r"><code>dataEx[order(dataEx$de1), ]</code></pre>
<p>La fonction <code>order</code> accepte plus d’un vecteur de valeurs pour déterminer le nouvel ordre. Par exemple, la commande suivante permet d’ordonner les observations de <code>dataEx</code> en ordre croissant de valeur de la variable <code>de1</code>, en résolvant les égalités en <code>de1</code> en considérant l’ordre alphabétique croissant de la variable <code>lanceur</code>.</p>
<pre class="r"><code>dataEx[order(dataEx$de1, dataEx$lanceur), ]</code></pre>
<pre><code>##    de1 de2 lanceur
## 4    1   3     Luc
## 1    2   1     Luc
## 5    2   5     Luc
## 6    3   4     Kim
## 2    3   4     Luc
## 10   4   3     Kim
## 3    4   2    &lt;NA&gt;
## 7    5  NA     Kim
## 9    5   5     Kim
## 8    6   2     Kim</code></pre>
<p>La fonction <code>order</code> a un argument <code>decreasing</code>, tout comme <code>sort</code>, pour demander un ordre décroissant plutôt que croissant. Par exemple, pour modifier l’ordre des colonnes de <code>dataEx</code> selon l’ordre alphabétique décroissant des noms de colonnes, nous pourrions procéder comme suit.</p>
<pre class="r"><code>dataEx[, order(names(dataEx), decreasing = TRUE)]</code></pre>
<pre><code>##    lanceur de2 de1
## 1      Luc   1   2
## 2      Luc   4   3
## 3     &lt;NA&gt;   2   4
## 4      Luc   3   1
## 5      Luc   5   2
## 6      Kim   4   3
## 7      Kim  NA   5
## 8      Kim   2   6
## 9      Kim   5   5
## 10     Kim   3   4</code></pre>
<p>Ainsi, la fonction <code>order</code> fournie la permutation selon l’ordre voulue, mais c’est l’opérateur <code>[</code> qui effectue l’opération de réordonner des lignes ou des colonnes. Une permutation fournie comme premier argument à <code>[</code> (avant la virgule) réordonne les lignes et une permutation fournie comme deuxième argument à <code>[</code> (après la virgule) réordonne les colonnes. Les lignes et les colonnes peuvent être réodonner simultanément.</p>
<p>Nous pourrions fournir à l’opérateur <code>[</code> des permutations arbitraires. Par exemple, pour déplacer en une commande la dernière observation du data frame <code>dataEx</code> en première position et la variable <code>lanceur</code> en premier position nous pouvons procéder ainsi.</p>
<pre class="r"><code>dataEx[c(nrow(dataEx), 1:(nrow(dataEx) - 1)), c(&quot;lanceur&quot;, &quot;de1&quot;, &quot;de2&quot;)]</code></pre>
<pre><code>##    lanceur de1 de2
## 10     Kim   4   3
## 1      Luc   2   1
## 2      Luc   3   4
## 3     &lt;NA&gt;   4   2
## 4      Luc   1   3
## 5      Luc   2   5
## 6      Kim   3   4
## 7      Kim   5  NA
## 8      Kim   6   2
## 9      Kim   5   5</code></pre>
<p>Notons finalement que ce genre de manipulation fonctionne aussi avec une matrice plutôt qu’un data frame.</p>
</div>
<div id="fonction-arrange-du-package-dplyr" class="section level3">
<h3>Fonction <code>arrange</code> du package <code>dplyr</code></h3>
<p>Si l’utilisation de la fonction <code>order</code> vous paraît peu conviviale, vous pouvez vous tourner vers la <a href="https://dplyr.tidyverse.org/reference/arrange.html">fonction <code>arrange</code> du package <code>dplyr</code></a> pour le réordonnancement d’observations dans un data frame. Voici un exemple d’utilisation de cette fonction, produisant presque le même résultat que la commande suivante.</p>
<pre class="r"><code>dataEx[order(dataEx$de1, dataEx$lanceur), ]</code></pre>
<pre><code>##    de1 de2 lanceur
## 4    1   3     Luc
## 1    2   1     Luc
## 5    2   5     Luc
## 6    3   4     Kim
## 2    3   4     Luc
## 10   4   3     Kim
## 3    4   2    &lt;NA&gt;
## 7    5  NA     Kim
## 9    5   5     Kim
## 8    6   2     Kim</code></pre>
<pre class="r"><code>library(dplyr)
arrange(dataEx, de1, lanceur)</code></pre>
<pre><code>##    de1 de2 lanceur
## 1    1   3     Luc
## 2    2   1     Luc
## 3    2   5     Luc
## 4    3   4     Kim
## 5    3   4     Luc
## 6    4   3     Kim
## 7    4   2    &lt;NA&gt;
## 8    5  NA     Kim
## 9    5   5     Kim
## 10   6   2     Kim</code></pre>
<p>La seule différence entre les deux sorties est les noms des lignes. La fonction <code>arrange</code> renomme les lignes 1 au nombre total de lignes.</p>
<p>Avec <code>arrange</code>, pour demander un ordre décroissant par rapport à une certaine variable, il faut envelopper le nom de la variable par un appel à la <a href="https://dplyr.tidyverse.org/reference/desc.html">fonction <code>desc</code></a> comme dans cet exemple.</p>
<pre class="r"><code>arrange(dataEx, desc(de1), lanceur)</code></pre>
<pre><code>##    de1 de2 lanceur
## 1    6   2     Kim
## 2    5  NA     Kim
## 3    5   5     Kim
## 4    4   3     Kim
## 5    4   2    &lt;NA&gt;
## 6    3   4     Kim
## 7    3   4     Luc
## 8    2   1     Luc
## 9    2   5     Luc
## 10   1   3     Luc</code></pre>
<p>La fonction <code>arrange</code> s’avère donc plus souple que <code>order</code>, qui applique le même type d’ordre (ascendant ou descendant) à toutes les variables.</p>
<pre class="r"><code>dataEx[order(dataEx$de1, dataEx$lanceur, decreasing = TRUE), ]</code></pre>
<pre><code>##    de1 de2 lanceur
## 8    6   2     Kim
## 7    5  NA     Kim
## 9    5   5     Kim
## 10   4   3     Kim
## 3    4   2    &lt;NA&gt;
## 2    3   4     Luc
## 6    3   4     Kim
## 1    2   1     Luc
## 5    2   5     Luc
## 4    1   3     Luc</code></pre>
<p>Cependant, la fonction <code>arrange</code> permet seulement de réordonner les lignes d’un data frame (ou d’un <a href="https://stt4230.rbind.io/manipulation_donnees/structures_r/#le-tibble">tibble</a>), alors que la fonction <code>order</code> utilisée avec l’opérateur <code>[</code> permet en fait de réordonner les éléments de n’importe quel type de structure de données et selon n’importe laquelle de ses dimensions.</p>
</div>
</div>
<div id="changement-de-mise-en-forme-de-jeux-de-donnees" class="section level2">
<h2>Changement de mise en forme de jeux de données</h2>
<p>La mise en forme de jeux de données est définie ici, de façon générale, par le choix de positionnement des données dans un tableau de données.</p>
<p>Par exemple, en statistique, les variables sont habituellement positionnées en colonnes et les observations en lignes dans un tableau de données. Que faire avec un tableau de données dans lequel les variables sont en lignes et les observations en colonnes ? Il serait judicieux de transposer le tableau (inverser les lignes et les colonnes), afin de retomber sur une mise en forme plus standard.</p>
<p>Mais par mise en forme de jeux de données en statistique, on réfère le plus souvent à la distinction entre deux types de mise en forme, que nous appellerons ici les mises en forme « large » et « longue ». Ces mises en forme sont définies un peu plus bas.</p>
<div id="transposition-avec-la-fonction-t" class="section level3">
<h3>Transposition avec la fonction <code>t</code></h3>
<p>La <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/t.html">fonction <code>t</code></a> sert à transposer (inverser les lignes et les colonnes) une matrice ou un data frame.</p>
<pre class="r"><code>dataEx</code></pre>
<pre><code>##    de1 de2 lanceur
## 1    2   1     Luc
## 2    3   4     Luc
## 3    4   2    &lt;NA&gt;
## 4    1   3     Luc
## 5    2   5     Luc
## 6    3   4     Kim
## 7    5  NA     Kim
## 8    6   2     Kim
## 9    5   5     Kim
## 10   4   3     Kim</code></pre>
<pre class="r"><code>dataEx_transpo &lt;- t(dataEx)
dataEx_transpo</code></pre>
<pre><code>##         [,1]  [,2]  [,3] [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
## de1     &quot;2&quot;   &quot;3&quot;   &quot;4&quot;  &quot;1&quot;   &quot;2&quot;   &quot;3&quot;   &quot;5&quot;   &quot;6&quot;   &quot;5&quot;   &quot;4&quot;  
## de2     &quot; 1&quot;  &quot; 4&quot;  &quot; 2&quot; &quot; 3&quot;  &quot; 5&quot;  &quot; 4&quot;  NA    &quot; 2&quot;  &quot; 5&quot;  &quot; 3&quot; 
## lanceur &quot;Luc&quot; &quot;Luc&quot; NA   &quot;Luc&quot; &quot;Luc&quot; &quot;Kim&quot; &quot;Kim&quot; &quot;Kim&quot; &quot;Kim&quot; &quot;Kim&quot;</code></pre>
<pre class="r"><code>str(dataEx_transpo)</code></pre>
<pre><code>##  chr [1:3, 1:10] &quot;2&quot; &quot; 1&quot; &quot;Luc&quot; &quot;3&quot; &quot; 4&quot; &quot;Luc&quot; &quot;4&quot; &quot; 2&quot; NA &quot;1&quot; &quot; 3&quot; ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : chr [1:3] &quot;de1&quot; &quot;de2&quot; &quot;lanceur&quot;
##   ..$ : NULL</code></pre>
<p>Cependant, la fonction <code>t</code> est en fait conçue pour effectuer des calculs d’algèbre linéaire et elle retourne toujours une matrice.</p>
</div>
<div id="comparaison-des-mises-en-forme-large-et-longue" class="section level3">
<h3>Comparaison des mises en forme large et longue</h3>
<p>Tout d’abord, introduisons un peu de terminologie informelle qui nous aidera à décrire les mises en forme.</p>
<ul>
<li>Individus (ou unités statistiques ou sujets) :
<ul>
<li>unités sur lesquelles des mesures sont prises;</li>
<li>possèdent des identifiants.</li>
</ul></li>
<li>Variables :
<ul>
<li>ce qui est mesuré;</li>
<li>possèdent aussi des identifiants.</li>
</ul></li>
<li>Valeurs :
<ul>
<li>mesures obtenues;</li>
<li>chaque valeur est associée à un individu et une variable.</li>
</ul></li>
</ul>
<div id="mise-en-forme-large-en-anglais-wide" class="section level4">
<h4>Mise en forme large (en anglais <em>wide</em>) :</h4>
<p>Lorsqu’un jeu de données comprend une seule ligne par individu et que les différentes variables mesurées se trouvent dans différentes colonnes, la mise en forme du jeu de données est dite « large ».</p>
<div id="exemple-de-notes-detudiants---mise-en-forme-large" class="section level5">
<h5>Exemple de notes d’étudiants - Mise en forme large</h5>
<ul>
<li>Individus = étudiants (au nombre de 4),</li>
<li>Variables = notes pour deux travaux pratiques : <code>TP1</code> et <code>TP2</code></li>
</ul>
<p> </p>
<pre class="r"><code>notes_large</code></pre>
<pre><code>##   etudiant TP1 TP2
## 1        a  90  95
## 2        b  80  74
## 3        c  70  89
## 4        d  60  85</code></pre>
</div>
</div>
<div id="mise-en-forme-longue-en-anglais-long" class="section level4">
<h4>Mise en forme longue (en anglais <em>long</em>) :</h4>
<p>Si un jeu de données comporte plutôt plus d’une ligne par individu, sa mise en forme est dite « longue ».</p>
<div id="exemple-de-notes-detudiants---mise-en-forme-long" class="section level5">
<h5>Exemple de notes d’étudiants - Mise en forme long</h5>
<pre class="r"><code>notes_long</code></pre>
<pre><code>##   etudiant note evaluation
## 1        a   90        TP1
## 2        b   80        TP1
## 3        c   70        TP1
## 4        d   60        TP1
## 5        a   95        TP2
## 6        b   74        TP2
## 7        c   89        TP2
## 8        d   85        TP2</code></pre>
<p>Le data frame <code>notes_long</code> contient exactement les mêmes données que celles dans le data frame <code>notes_large</code>, mais disposées différemment. Dans <code>notes_long</code>, il y a deux lignes par individu. Le tableau de mise en forme longue contient plus de lignes, donc est plus long, que le tableau de mise en forme large, d’où les qualificatifs « large » et « longue » pour les mises en forme.</p>
<p>Dans un jeu de données avec une mise en forme longue, les mesures pour plus d’une variable sont combinées dans une même colonne. Cependant, il doit aussi nécessairement y avoir une ou des colonnes servant à identifier à quelle variable est associée chaque ligne (colonne <code>evaluation</code> dans l’exemple).</p>
<p>Lors d’une analyse statistique de données stockées sous une mise en forme longue, l’analyste doit être vigilant. Il est important d’être conscient que certaines lignes concernent les mêmes individus, donc qu’il s’agit de <em>mesures répétées</em> sur les mêmes individus et non d’observations indépendantes.</p>
</div>
</div>
<div id="mise-en-forme-intermediaire" class="section level4">
<h4>Mise en forme intermédiaire :</h4>
<p>Il peut arriver qu’un jeu de données ait une mise en forme mi-large, mi-longue. Voici un exemple pour illustrer cette mise en forme intermédiaire.</p>
<div id="exemple-de-mesures-sur-des-plants" class="section level5">
<h5>Exemple de mesures sur des plants</h5>
<ul>
<li>Individus = plants (au nombre de 3),</li>
<li>Variables = <code>Hauteur_Temps1</code>, <code>Hauteur_Temps2</code>, <code>Diametre_Temps1</code>, <code>Diametre_Temps2</code></li>
</ul>
</div>
<div id="format-large-pur-une-ligne-par-individu-une-colonne-par-variable" class="section level5">
<h5>Format large pur : une ligne par individu, une colonne par variable</h5>
<p>Dimension de la sous-matrice contenant les valeurs : 3 x 4</p>
<pre class="r"><code>plants_large</code></pre>
<pre><code>##   Plant Hauteur_Temps1 Hauteur_Temps2 Diametre_Temps1 Diametre_Temps2
## 1     a             67             69              15              15
## 2     b             59             65              16              17
## 3     c             62             66              13              14</code></pre>
</div>
<div id="format-intermediaire-plus-dune-ligne-par-individu-mais-valeurs-reparties-dans-plus-dune-colonne" class="section level5">
<h5>Format intermédiaire : plus d’une ligne par individu, mais valeurs réparties dans plus d’une colonne</h5>
<p>Dimension de la sous-matrice contenant les valeurs : 6 x 2</p>
<pre class="r"><code>plants_inter</code></pre>
<pre><code>##   Plant Temps Hauteur Diametre
## 1     a     1      67       15
## 2     b     1      59       16
## 3     c     1      62       13
## 4     a     2      69       15
## 5     b     2      65       17
## 6     c     2      66       14</code></pre>
</div>
<div id="format-long-pur-toutes-les-valeurs-sont-empilees-dans-une-seule-colonne" class="section level5">
<h5>Format long pur : toutes les valeurs sont empilées dans une seule colonne</h5>
<p>Dimension de la sous-matrice contenant les valeurs : 12 x 1</p>
<pre class="r"><code>plants_long</code></pre>
<pre><code>##    Plant Temps Variable Valeur
## 1      a     1  Hauteur     67
## 2      b     1  Hauteur     59
## 3      c     1  Hauteur     62
## 4      a     2  Hauteur     69
## 5      b     2  Hauteur     65
## 6      c     2  Hauteur     66
## 7      a     1 Diametre     15
## 8      b     1 Diametre     16
## 9      c     1 Diametre     13
## 10     a     2 Diametre     15
## 11     b     2 Diametre     17
## 12     c     2 Diametre     14</code></pre>
<p>ou encore</p>
<pre class="r"><code>plants_long2</code></pre>
<pre><code>##    Plant        Variable Valeur
## 1      a  Hauteur_Temps1     67
## 2      b  Hauteur_Temps1     59
## 3      c  Hauteur_Temps1     62
## 4      a  Hauteur_Temps2     69
## 5      b  Hauteur_Temps2     65
## 6      c  Hauteur_Temps2     66
## 7      a Diametre_Temps1     15
## 8      b Diametre_Temps1     16
## 9      c Diametre_Temps1     13
## 10     a Diametre_Temps2     15
## 11     b Diametre_Temps2     17
## 12     c Diametre_Temps2     14</code></pre>
</div>
</div>
<div id="utilisation-des-deux-mises-en-forme" class="section level4">
<h4>Utilisation des deux mises en forme</h4>
<p>Certaines fonctions R requièrent un type particulier de mise en forme du jeu de données.</p>
<p>Dans l’exemple des notes d’étudiants, nous pourrions vouloir comparer les notes des deux travaux. Étant donné que nous sommes en présence de données prises sur les mêmes individus (qualifiées en statistique de <em>mesures répétées</em> ou encore de <em>données pairées</em> dans le cas particulier de deux variables), un test approprié à réaliser serait un test de comparaison de moyennes pour données pairées. La <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html">fonction <code>t.test</code></a> réalise ce type de test. Elle accepte les jeux de données de mise en forme large,</p>
<pre class="r"><code>t.test(notes_large$TP1, notes_large$TP2, paired = TRUE)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  notes_large$TP1 and notes_large$TP2
## t = -1.54, df = 3, p-value = 0.2212
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -32.96547  11.46547
## sample estimates:
## mean of the differences 
##                  -10.75</code></pre>
<p>ou de mise en forme longue (qui permet l’utilisation d’une formule R).</p>
<pre class="r"><code>t.test(note ~ evaluation, data = notes_long, paired = TRUE)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  note by evaluation
## t = -1.54, df = 3, p-value = 0.2212
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -32.96547  11.46547
## sample estimates:
## mean of the differences 
##                  -10.75</code></pre>
<p>Nous pourrions aussi ajuster un modèle linéaire mixte pour réaliser un test équivalent. La <a href="https://stat.ethz.ch/R-manual/R-devel/library/nlme/html/lme.html">fonction <code>lme</code> du package <code>nlme</code></a> ajuste des modèles linéaires mixtes. Elle accepte cependant seulement des jeux de données de mise en forme longue.</p>
<pre class="r"><code>library(nlme)
mixed &lt;- lme(fixed = note ~ evaluation, data = notes_long, random = ~ 1 | etudiant)
summary(mixed)</code></pre>
<pre><code>## Linear mixed-effects model fit by REML
##  Data: notes_long 
##        AIC     BIC    logLik
##   56.51876 55.6858 -24.25938
## 
## Random effects:
##  Formula: ~1 | etudiant
##         (Intercept) Residual
## StdDev:    5.000001 9.872098
## 
## Fixed effects: note ~ evaluation 
##               Value Std.Error DF   t-value p-value
## (Intercept)   75.00  5.533045  3 13.554924  0.0009
## evaluationTP2 10.75  6.980628  3  1.539976  0.2212
##  Correlation: 
##               (Intr)
## evaluationTP2 -0.631
## 
## Standardized Within-Group Residuals:
##        Min         Q1        Med         Q3        Max 
## -1.2489496 -0.6258934  0.2768885  0.5459932  1.1029740 
## 
## Number of Observations: 8
## Number of Groups: 4</code></pre>
<p>Nous avons utilisé ici un modèle statistique puissant pour réaliser en fait un test simple. Le test sur le terme <code>evaluationTP2</code> dans le modèle linéaire mixte revient au test de comparaison de moyennes pour données pairées réalisé avec la fonction <code>t.test</code>. Nous pouvons constater que le seuil observé des deux tests est le même, soit 0.2212.</p>
<p>Le but de cet exemple était de montrer qu’il est utile en R de savoir convertir un jeu de données d’une mise à forme à l’autre puisque certaines fonctions exigent une mise en forme spécifique.</p>
</div>
</div>
<div id="transformation-entre-les-mises-en-forme-large-et-longue-avec-les-fonctions-stack-et-unstack" class="section level3">
<h3>Transformation entre les mises en forme large et longue avec les fonctions <code>stack</code> et <code>unstack</code></h3>
<p>Revenons maintenant au jeu de données <code>dataEx</code>. Celui-ci est sous une mise en forme large, car il contient une seule ligne par individu. Dans ce jeu de données, un individu est un lancer de dés.</p>
<pre class="r"><code>dataEx</code></pre>
<pre><code>##    de1 de2 lanceur
## 1    2   1     Luc
## 2    3   4     Luc
## 3    4   2    &lt;NA&gt;
## 4    1   3     Luc
## 5    2   5     Luc
## 6    3   4     Kim
## 7    5  NA     Kim
## 8    6   2     Kim
## 9    5   5     Kim
## 10   4   3     Kim</code></pre>
<p>Il est possible de faire passer ce jeu de données à une mise en forme longue avec la <a href="https://stat.ethz.ch/R-manual/R-devel/library/utils/html/stack.html">fonction <code>stack</code></a> comme suit</p>
<pre class="r"><code>dataEx_long &lt;- stack(dataEx)</code></pre>
<pre><code>## Warning in stack.data.frame(dataEx): non-vector columns will be ignored</code></pre>
<pre class="r"><code>dataEx_long</code></pre>
<pre><code>##    values ind
## 1       2 de1
## 2       3 de1
## 3       4 de1
## 4       1 de1
## 5       2 de1
## 6       3 de1
## 7       5 de1
## 8       6 de1
## 9       5 de1
## 10      4 de1
## 11      1 de2
## 12      4 de2
## 13      2 de2
## 14      3 de2
## 15      5 de2
## 16      4 de2
## 17     NA de2
## 18      2 de2
## 19      5 de2
## 20      3 de2</code></pre>
<p>Cette fonction n’est pas très puissante. Elle n’a pas su traiter la colonne <code>lanceur</code> et l’a laissé tomber.</p>
<p>Nous pourrions réaliser la transformation inverse avec la <a href="https://stat.ethz.ch/R-manual/R-devel/library/utils/html/stack.html">fonction <code>unstack</code></a>, pour revenir à la mise en forme originale.</p>
<pre class="r"><code>dataEx_large &lt;- unstack(dataEx_long)
dataEx_large</code></pre>
<pre><code>##    de1 de2
## 1    2   1
## 2    3   4
## 3    4   2
## 4    1   3
## 5    2   5
## 6    3   4
## 7    5  NA
## 8    6   2
## 9    5   5
## 10   4   3</code></pre>
<p>Voyons maintenant une autre fonction qui nous permettra de réaliser les mêmes transformations, sans mettre de côté la variable <code>lanceur</code>.</p>
</div>
<div id="transformation-entre-les-mises-en-forme-large-et-longue-avec-la-fonction-reshape" class="section level3">
<h3>Transformation entre les mises en forme large et longue avec la fonction <code>reshape</code></h3>
<p>Le package <code>stats</code>, chargé en R par défaut, comprend une <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/reshape.html">fonction nommée <code>reshape</code></a> dont l’utilité est de faire passer un jeu de donnée d’une mise en forme large vers une mise en forme longue, et aussi de réaliser la transformation inverse, d’une mise en forme longue vers une mise en forme large. Cette fonction est puissante, mais un peu difficile à utiliser, il faut l’avouer. Il est facile de se perdre dans ses nombreux arguments.</p>
<div id="exemple-de-transformation-vers-une-mise-en-forme-longue" class="section level4">
<h4>Exemple de transformation vers une mise en forme longue :</h4>
<p>Pour faire passer le data frame <code>dataEx</code> vers une mise en forme longue, nous pouvons procéder comme suit.</p>
<pre class="r"><code>dataEx_long2 &lt;- reshape(data = dataEx, 
                        direction = &quot;long&quot;, 
                        varying = c(&quot;de1&quot;, &quot;de2&quot;),
                        v.names = &quot;resultat&quot;)
dataEx_long2</code></pre>
<pre><code>##      lanceur time resultat id
## 1.1      Luc    1        2  1
## 2.1      Luc    1        3  2
## 3.1     &lt;NA&gt;    1        4  3
## 4.1      Luc    1        1  4
## 5.1      Luc    1        2  5
## 6.1      Kim    1        3  6
## 7.1      Kim    1        5  7
## 8.1      Kim    1        6  8
## 9.1      Kim    1        5  9
## 10.1     Kim    1        4 10
## 1.2      Luc    2        1  1
## 2.2      Luc    2        4  2
## 3.2     &lt;NA&gt;    2        2  3
## 4.2      Luc    2        3  4
## 5.2      Luc    2        5  5
## 6.2      Kim    2        4  6
## 7.2      Kim    2       NA  7
## 8.2      Kim    2        2  8
## 9.2      Kim    2        5  9
## 10.2     Kim    2        3 10</code></pre>
<p>Il faut toujours fournir à la fonction <code>reshape</code> les arguments :</p>
<ul>
<li><code>data</code> : le data frame dont à mise en forme est à transformer;</li>
<li><code>direction</code> : la direction de la transformation, <code>long</code> pour une transformation vers une mise en forme longue, <code>wide</code> pour une transformation vers une mise en forme large.</li>
</ul>
<p>Lors d’une transformation vers une mise en forme longue, il faut aussi spécifier l’argument :</p>
<ul>
<li><code>varying</code> : les noms ou les indices des colonnes dans le jeu de données d’origine sous la mise en forme large (<code>data</code>) contenant les données à combiner dans des colonnes uniques sous la mise en forme longue.</li>
</ul>
<p>La fonction <code>reshape</code> va alors tenter de deviner le ou les noms à donner à cette ou ces nouvelles colonnes, mais il est préférable de lui spécifier ce ou ces noms avec l’argument :</p>
<ul>
<li><code>v.names</code> : nom(s) de la ou des colonnes dans la mise en forme longue correspondant à plusieurs colonnes sous la mise en forme large.</li>
</ul>
<p>Par défaut, <code>reshape</code> a nommé <code>time</code> la colonne contenant les identifiants des variables empilées. Aussi, <code>reshape</code> a utilisé comme identifiants dans cette colonne les entiers allant de 1 jusqu’au nombre de variables empilées. Il est possible de contrôler cette colonne avec les arguments :</p>
<ul>
<li><code>timevar</code> : nom de la colonne dans la mise en forme longue contenant l’identifiant de la variable à laquelle correspond la ou les données qui se trouvent dans la ou les colonnes identifiées par <code>v.names</code>.</li>
<li><code>times</code> : les valeurs d’identifiants à utiliser dans la colonne spécifiée par <code>timevar</code>.</li>
</ul>
<p>Les noms de ces arguments contiennent le mot <code>time</code> en référence à un cas classique de données pour lesquelles nous sommes susceptibles de vouloir modifier la mise en forme : des mesures répétées dans le temps.</p>
<pre class="r"><code>dataEx_long2 &lt;- reshape(data = dataEx, 
                        direction = &quot;long&quot;, 
                        varying = c(&quot;de1&quot;, &quot;de2&quot;),
                        v.names = &quot;resultat&quot;, 
                        timevar = &quot;de&quot;,
                        times = c(&quot;de1&quot;, &quot;de2&quot;))
dataEx_long2</code></pre>
<pre><code>##        lanceur  de resultat id
## 1.de1      Luc de1        2  1
## 2.de1      Luc de1        3  2
## 3.de1     &lt;NA&gt; de1        4  3
## 4.de1      Luc de1        1  4
## 5.de1      Luc de1        2  5
## 6.de1      Kim de1        3  6
## 7.de1      Kim de1        5  7
## 8.de1      Kim de1        6  8
## 9.de1      Kim de1        5  9
## 10.de1     Kim de1        4 10
## 1.de2      Luc de2        1  1
## 2.de2      Luc de2        4  2
## 3.de2     &lt;NA&gt; de2        2  3
## 4.de2      Luc de2        3  4
## 5.de2      Luc de2        5  5
## 6.de2      Kim de2        4  6
## 7.de2      Kim de2       NA  7
## 8.de2      Kim de2        2  8
## 9.de2      Kim de2        5  9
## 10.de2     Kim de2        3 10</code></pre>
<p>Sous une mise en forme longue, <code>reshape</code> inclut aussi toujours au moins une colonne pour contenir un identifiant des individus. Il nomme par défaut cette colonne <code>id</code> et utilise comme identifiants les entiers allant de 1 jusqu’au nombre de lignes dans le jeu de données d’origine sous la mise en forme large (<code>data</code>). Pour contrôler cette colonne, il faut utiliser les arguments :</p>
<ul>
<li><code>idvar</code> : nom(s) de la ou des colonnes pour identifier les individus sous la mise en forme longue.</li>
<li><code>ids</code> : les valeurs d’identifiants à utiliser dans la ou les colonnes spécifiées par <code>idvar</code>.</li>
</ul>
<pre class="r"><code>dataEx_long2 &lt;- reshape(data = dataEx, 
                        direction = &quot;long&quot;, 
                        varying = c(&quot;de1&quot;, &quot;de2&quot;),
                        v.names = &quot;resultat&quot;, 
                        timevar = &quot;de&quot;,
                        times = c(&quot;de1&quot;, &quot;de2&quot;),
                        idvar = &quot;noLancer&quot;,
                        ids = paste0(&quot;l&quot;, 1:10))
dataEx_long2</code></pre>
<pre><code>##         lanceur  de resultat noLancer
## l1.de1      Luc de1        2       l1
## l2.de1      Luc de1        3       l2
## l3.de1     &lt;NA&gt; de1        4       l3
## l4.de1      Luc de1        1       l4
## l5.de1      Luc de1        2       l5
## l6.de1      Kim de1        3       l6
## l7.de1      Kim de1        5       l7
## l8.de1      Kim de1        6       l8
## l9.de1      Kim de1        5       l9
## l10.de1     Kim de1        4      l10
## l1.de2      Luc de2        1       l1
## l2.de2      Luc de2        4       l2
## l3.de2     &lt;NA&gt; de2        2       l3
## l4.de2      Luc de2        3       l4
## l5.de2      Luc de2        5       l5
## l6.de2      Kim de2        4       l6
## l7.de2      Kim de2       NA       l7
## l8.de2      Kim de2        2       l8
## l9.de2      Kim de2        5       l9
## l10.de2     Kim de2        3      l10</code></pre>
<p>Dans le jeu de données de mise en forme longue obtenu en sortie de <code>reshape</code>, les données pour les variables (colonnes) ne contenant pas de mesures répétées ont simplement été recopiées autant de fois que nécessaire. Il serait possible de laisser tomber ces variables grâce à l’argument <code>drop</code>. Il serait aussi possible de contrôler les noms des lignes du data frame obtenu avec l’argument <code>new.row.names</code>.</p>
</div>
<div id="exemple-de-transformation-vers-une-mise-en-forme-large" class="section level4">
<h4>Exemple de transformation vers une mise en forme large :</h4>
<p>Lorsque nous avons obtenu un jeu de données avec la fonction <code>reshape</code>, il est toujours possible de retourner à la mise en forme d’origine simplement avec la commande</p>
<pre class="r"><code>reshape(dataEx_long2)</code></pre>
<pre><code>##         lanceur noLancer de1 de2
## l1.de1      Luc       l1   2   1
## l2.de1      Luc       l2   3   4
## l3.de1     &lt;NA&gt;       l3   4   2
## l4.de1      Luc       l4   1   3
## l5.de1      Luc       l5   2   5
## l6.de1      Kim       l6   3   4
## l7.de1      Kim       l7   5  NA
## l8.de1      Kim       l8   6   2
## l9.de1      Kim       l9   5   5
## l10.de1     Kim      l10   4   3</code></pre>
<p>en raison d’un attribut inséré par <code>reshape</code> dans sa sortie.</p>
<pre class="r"><code>str(dataEx_long2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    20 obs. of  4 variables:
##  $ lanceur : Factor w/ 2 levels &quot;Kim&quot;,&quot;Luc&quot;: 2 2 NA 2 2 1 1 1 1 1 ...
##  $ de      : chr  &quot;de1&quot; &quot;de1&quot; &quot;de1&quot; &quot;de1&quot; ...
##  $ resultat: num  2 3 4 1 2 3 5 6 5 4 ...
##  $ noLancer: chr  &quot;l1&quot; &quot;l2&quot; &quot;l3&quot; &quot;l4&quot; ...
##  - attr(*, &quot;reshapeLong&quot;)=List of 4
##   ..$ varying:List of 1
##   .. ..$ resultat: chr  &quot;de1&quot; &quot;de2&quot;
##   .. ..- attr(*, &quot;v.names&quot;)= chr &quot;resultat&quot;
##   .. ..- attr(*, &quot;times&quot;)= chr  &quot;de1&quot; &quot;de2&quot;
##   ..$ v.names: chr &quot;resultat&quot;
##   ..$ idvar  : chr &quot;noLancer&quot;
##   ..$ timevar: chr &quot;de&quot;</code></pre>
<p>Mais supposons que nous n’avons pas créé <code>dataEx_long2</code> avec la fonction <code>reshape</code> et que nous voulons transformer ce jeu de données vers une mise en forme large. Afin de réellement simuler une telle situation, nous allons effacer de <code>dataEx_long2</code> son attribut nommé <code>reshapeLong</code> comme suit.</p>
<pre class="r"><code>attr(dataEx_long2, &quot;reshapeLong&quot;) &lt;- NULL
str(dataEx_long2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    20 obs. of  4 variables:
##  $ lanceur : Factor w/ 2 levels &quot;Kim&quot;,&quot;Luc&quot;: 2 2 NA 2 2 1 1 1 1 1 ...
##  $ de      : chr  &quot;de1&quot; &quot;de1&quot; &quot;de1&quot; &quot;de1&quot; ...
##  $ resultat: num  2 3 4 1 2 3 5 6 5 4 ...
##  $ noLancer: chr  &quot;l1&quot; &quot;l2&quot; &quot;l3&quot; &quot;l4&quot; ...</code></pre>
<p>Nous pourrions procéder ainsi pour effectuer la transformation de mise en forme.</p>
<pre class="r"><code>dataEx_large2 &lt;- reshape(data = dataEx_long2,
                        direction = &quot;wide&quot;,
                        timevar = &quot;de&quot;,
                        idvar = &quot;noLancer&quot;)
dataEx_large2</code></pre>
<pre><code>##         noLancer lanceur.de1 resultat.de1 lanceur.de2 resultat.de2
## l1.de1        l1         Luc            2         Luc            1
## l2.de1        l2         Luc            3         Luc            4
## l3.de1        l3        &lt;NA&gt;            4        &lt;NA&gt;            2
## l4.de1        l4         Luc            1         Luc            3
## l5.de1        l5         Luc            2         Luc            5
## l6.de1        l6         Kim            3         Kim            4
## l7.de1        l7         Kim            5         Kim           NA
## l8.de1        l8         Kim            6         Kim            2
## l9.de1        l9         Kim            5         Kim            5
## l10.de1      l10         Kim            4         Kim            3</code></pre>
<p>Les seuls arguments obligatoires pour réaliser cette transformation vers une mise en forme large sont <code>data</code>, <code>direction</code>, <code>timevar</code> et <code>idvar</code>, dont les descriptions ont été fournies ci-dessus. Cependant, <code>reshape</code> a par défaut considéré que toutes les variables autres que celles identifiées avec <code>timevar</code> et <code>idvar</code> contiennent des mesures répétées. Nous nous retrouvons donc maintenant avec deux colonnes identiques contenant le nom du lanceur. Pour spécifier à <code>reshape</code> la ou les colonnes pour lesquelles les données doivent être réparties en plusieurs colonnes, il faut aussi spécifier l’argument <code>v.names</code>.</p>
<pre class="r"><code>dataEx_large2 &lt;- reshape(dataEx_long2,
                        direction = &quot;wide&quot;,
                        timevar = &quot;de&quot;,
                        idvar = &quot;noLancer&quot;,
                        v.names = &quot;resultat&quot;)
dataEx_large2</code></pre>
<pre><code>##         lanceur noLancer resultat.de1 resultat.de2
## l1.de1      Luc       l1            2            1
## l2.de1      Luc       l2            3            4
## l3.de1     &lt;NA&gt;       l3            4            2
## l4.de1      Luc       l4            1            3
## l5.de1      Luc       l5            2            5
## l6.de1      Kim       l6            3            4
## l7.de1      Kim       l7            5           NA
## l8.de1      Kim       l8            6            2
## l9.de1      Kim       l9            5            5
## l10.de1     Kim      l10            4            3</code></pre>
<p>Et voilà!</p>
<p>Afin de reconstruire un data frame vraiment identique à <code>dataEx</code>,</p>
<pre class="r"><code>dataEx</code></pre>
<pre><code>##    de1 de2 lanceur
## 1    2   1     Luc
## 2    3   4     Luc
## 3    4   2    &lt;NA&gt;
## 4    1   3     Luc
## 5    2   5     Luc
## 6    3   4     Kim
## 7    5  NA     Kim
## 8    6   2     Kim
## 9    5   5     Kim
## 10   4   3     Kim</code></pre>
<p>il suffirait de retirer la colonne <code>noLancer</code>, réordonner les colonnes, renommer les colonnes contenant les résultats des lancers de dés et renommer les lignes.</p>
<pre class="r"><code>dataEx_large2$noLancer &lt;- NULL                   # retirer une colonne
dataEx_large2 &lt;- dataEx_large2[, c(2,3,1)]        # réordonner les colonnes
colnames(dataEx_large2)[1:2] &lt;- c(&quot;de1&quot;, &quot;de2&quot;)  # renommer certaines colonnes
rownames(dataEx_large2) &lt;- 1:10                  # renommer les lignes
dataEx_large2</code></pre>
<pre><code>##    de1 de2 lanceur
## 1    2   1     Luc
## 2    3   4     Luc
## 3    4   2    &lt;NA&gt;
## 4    1   3     Luc
## 5    2   5     Luc
## 6    3   4     Kim
## 7    5  NA     Kim
## 8    6   2     Kim
## 9    5   5     Kim
## 10   4   3     Kim</code></pre>
</div>
</div>
<div id="transformation-entre-les-mises-en-forme-large-et-longue-avec-les-fonctions-gather-et-spread-du-package-tidyr" class="section level3">
<h3>Transformation entre les mises en forme large et longue avec les fonctions <code>gather</code> et <code>spread</code> du package <code>tidyr</code></h3>
<p>Des alternatives à la fonction <code>reshape</code> ont été créées et sont distribuées dans des packages R. Notamment, le <a href="https://tidyr.tidyverse.org/">package <code>tidyr</code></a> offre les fonctions suivantes, permettant d’effectuer des transformations de mise en forme.</p>
<table>
<thead>
<tr class="header">
<th>Transformation</th>
<th>Package <code>stats</code></th>
<th>Package <code>tidyr</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>large vers long</td>
<td><code>reshape</code> (avec <code>direction = &quot;long&quot;</code>)</td>
<td><code>gather</code></td>
</tr>
<tr class="even">
<td>long vers large</td>
<td><code>reshape</code> (avec <code>direction = &quot;wide&quot;</code>)</td>
<td><code>spread</code></td>
</tr>
</tbody>
</table>
<p>Illustrons l’utilisation des fonctions <a href="https://tidyr.tidyverse.org/reference/gather.html"><code>gather</code></a> et <a href="https://tidyr.tidyverse.org/reference/spread.html"><code>spread</code></a> de <code>tidyr</code>.</p>
<pre class="r"><code>library(tidyr)</code></pre>
<div id="exemple-de-transformation-vers-une-mise-en-forme-longue-1" class="section level4">
<h4>Exemple de transformation vers une mise en forme longue :</h4>
<p>Voici une commande pour transformer le data frame <code>dataEx</code> de sa mise en forme d’origine, large, à la mise en forme longue.</p>
<pre class="r"><code>dataEx_long3 &lt;- gather(data = dataEx, key = de, value = resultat, de1, de2)
dataEx_long3</code></pre>
<pre><code>##    lanceur  de resultat
## 1      Luc de1        2
## 2      Luc de1        3
## 3     &lt;NA&gt; de1        4
## 4      Luc de1        1
## 5      Luc de1        2
## 6      Kim de1        3
## 7      Kim de1        5
## 8      Kim de1        6
## 9      Kim de1        5
## 10     Kim de1        4
## 11     Luc de2        1
## 12     Luc de2        4
## 13    &lt;NA&gt; de2        2
## 14     Luc de2        3
## 15     Luc de2        5
## 16     Kim de2        4
## 17     Kim de2       NA
## 18     Kim de2        2
## 19     Kim de2        5
## 20     Kim de2        3</code></pre>
<p>Il faut fournir à <code>gather</code> les arguments :</p>
<ul>
<li><code>data</code> : le data frame à transformer de mise en forme.</li>
<li><code>key</code> : le nom de la colonne dans la mise en forme longue pour contenir l’identifiant de la variable à laquelle correspond la donnée qui se retrouvera dans la colonne identifiée par <code>value</code>.</li>
<li><code>value</code> : le nom de la colonne dans la mise en forme longue correspondant à plusieurs colonnes sous la mise en forme large.</li>
</ul>
<p>Notons que les noms fournis aux arguments <code>key</code> et <code>value</code> peuvent être encadrés de guillemets (donc sous forme de chaîne de caractères) ou non.</p>
<p>Après avoir fourni les trois premiers arguments nommés obligatoires, il faut fournir les noms (sans les encadrer de guillemets) des colonnes dans le jeu de données d’origine sous la mise en forme large (<code>data</code>) contenant les données à combiner dans des colonnes uniques sous la mise en forme longue.</p>
<p>Remarquons que la fonction <code>gather</code> n’ajoute pas une colonne pour identifier les individus comme le fait la fonction <code>reshape</code>. Il aurait fallu que le jeu de données d’origine contienne déjà une colonne avec ces identifiants. Dans <code>dataEx</code>, ce sont plutôt les noms de lignes qui identifient en quelque sorte les individus.</p>
</div>
<div id="exemple-de-transformation-vers-une-mise-en-forme-large-1" class="section level4">
<h4>Exemple de transformation vers une mise en forme large :</h4>
<p>Afin d’effectuer une transformation d’une mise en forme longue vers une mise en forme large avec la fonction <code>spread</code> de <code>tidyr</code>, le jeu de données fourni en entrée à la fonction doit contenir une colonne pour identifier les individus. Voici donc un exemple d’utilisation de la fonction <code>spread</code>, réalisé en utilisant comme jeu de données d’origine <code>dataEx_long2</code>.</p>
<pre class="r"><code>dataEx_large3 &lt;- spread(data = dataEx_long2, key = de, value = resultat)
dataEx_large3</code></pre>
<pre><code>##    lanceur noLancer de1 de2
## 1      Kim      l10   4   3
## 2      Kim       l6   3   4
## 3      Kim       l7   5  NA
## 4      Kim       l8   6   2
## 5      Kim       l9   5   5
## 6      Luc       l1   2   1
## 7      Luc       l2   3   4
## 8      Luc       l4   1   3
## 9      Luc       l5   2   5
## 10    &lt;NA&gt;       l3   4   2</code></pre>
<p>La fonction a seulement besoin des arguments <code>data</code>, <code>key</code>, <code>value</code>, qui ont la même signification que pour la fonction <code>gather</code>.</p>
</div>
</div>
<div id="exemples-supplementaires-de-changement-de-mise-en-forme" class="section level3">
<h3>Exemples supplémentaires de changement de mise en forme</h3>
<div id="format-large-pur-vers-format-intermediaire" class="section level4">
<h4>Format large pur vers format intermédiaire</h4>
<pre class="r"><code># Avec reshape
reshape(data = plants_large,
        direction = &quot;long&quot;,
        idvar = &quot;Plant&quot;,
        timevar = &quot;Temps&quot;,
        times = 1:2,
        v.names = c(&quot;Hauteur&quot;, &quot;Diametre&quot;),
        varying = c(&quot;Diametre_Temps1&quot;, &quot;Hauteur_Temps1&quot;, &quot;Diametre_Temps2&quot;, &quot;Hauteur_Temps2&quot;))</code></pre>
<pre><code>##     Plant Temps Hauteur Diametre
## a.1     a     1      67       15
## b.1     b     1      59       16
## c.1     c     1      62       13
## a.2     a     2      69       15
## b.2     b     2      65       17
## c.2     c     2      66       14</code></pre>
<p>L’ordre à donner aux noms de colonnes dans <code>varying</code> pour arriver au bon résultat est contre-intuitif.</p>
<pre class="r"><code># Avec gather
# Il faut réaliser la transformation en deux temps, 
# parce que l&#39;argument value accepte seulement un nom.
gather(data = plants_large,
       key = Time,
       value =  Hauteur,
       Hauteur_Temps1, Hauteur_Temps2)</code></pre>
<pre><code>##   Plant Diametre_Temps1 Diametre_Temps2           Time Hauteur
## 1     a              15              15 Hauteur_Temps1      67
## 2     b              16              17 Hauteur_Temps1      59
## 3     c              13              14 Hauteur_Temps1      62
## 4     a              15              15 Hauteur_Temps2      69
## 5     b              16              17 Hauteur_Temps2      65
## 6     c              13              14 Hauteur_Temps2      66</code></pre>
<pre class="r"><code>gather(data = plants_large,
       key = Time,
       value =  Diametre,
       Diametre_Temps1, Diametre_Temps2)</code></pre>
<pre><code>##   Plant Hauteur_Temps1 Hauteur_Temps2            Time Diametre
## 1     a             67             69 Diametre_Temps1       15
## 2     b             59             65 Diametre_Temps1       16
## 3     c             62             66 Diametre_Temps1       13
## 4     a             67             69 Diametre_Temps2       15
## 5     b             59             65 Diametre_Temps2       17
## 6     c             62             66 Diametre_Temps2       14</code></pre>
<pre class="r"><code># Il resterait à fusionner les deux data frames et à éliminer des variables.</code></pre>
</div>
<div id="format-large-pur-vers-format-long-pur" class="section level4">
<h4>Format large pur vers format long pur</h4>
<pre class="r"><code># Avec reshape
reshape(data = plants_large,
        direction = &quot;long&quot;,
        idvar = &quot;Plant&quot;,
        timevar = &quot;Variable&quot;,
        times = c(&quot;Hauteur_Temps1&quot;, &quot;Hauteur_Temps2&quot;, &quot;Diametre_Temps1&quot;, &quot;Diametre_Temps2&quot;),
        v.names = &quot;Valeur&quot;,
        varying = c(&quot;Hauteur_Temps1&quot;, &quot;Hauteur_Temps2&quot;, &quot;Diametre_Temps1&quot;, &quot;Diametre_Temps2&quot;))</code></pre>
<pre><code>##                   Plant        Variable Valeur
## a.Hauteur_Temps1      a  Hauteur_Temps1     67
## b.Hauteur_Temps1      b  Hauteur_Temps1     59
## c.Hauteur_Temps1      c  Hauteur_Temps1     62
## a.Hauteur_Temps2      a  Hauteur_Temps2     69
## b.Hauteur_Temps2      b  Hauteur_Temps2     65
## c.Hauteur_Temps2      c  Hauteur_Temps2     66
## a.Diametre_Temps1     a Diametre_Temps1     15
## b.Diametre_Temps1     b Diametre_Temps1     16
## c.Diametre_Temps1     c Diametre_Temps1     13
## a.Diametre_Temps2     a Diametre_Temps2     15
## b.Diametre_Temps2     b Diametre_Temps2     17
## c.Diametre_Temps2     c Diametre_Temps2     14</code></pre>
<p>L’ordre à donner aux noms de colonnes dans <code>varying</code> pour arriver au bon résultat est contre-intuitif.</p>
<pre class="r"><code># Avec gather
gather(data = plants_large,
       key = Variable,
       value =  Valeur,
       Hauteur_Temps1, Hauteur_Temps2, Diametre_Temps1, Diametre_Temps2)</code></pre>
<pre><code>##    Plant        Variable Valeur
## 1      a  Hauteur_Temps1     67
## 2      b  Hauteur_Temps1     59
## 3      c  Hauteur_Temps1     62
## 4      a  Hauteur_Temps2     69
## 5      b  Hauteur_Temps2     65
## 6      c  Hauteur_Temps2     66
## 7      a Diametre_Temps1     15
## 8      b Diametre_Temps1     16
## 9      c Diametre_Temps1     13
## 10     a Diametre_Temps2     15
## 11     b Diametre_Temps2     17
## 12     c Diametre_Temps2     14</code></pre>
</div>
<div id="format-intermediaire-vers-format-long-pur" class="section level4">
<h4>Format intermédiaire vers format long pur</h4>
<pre class="r"><code># Avec reshape
reshape(data = plants_inter,
        direction = &quot;long&quot;,
        idvar = c(&quot;Plant&quot;, &quot;Temps&quot;), # n&#39;accepte pas &quot;Plant&quot; seul, car la colonne
        timevar = &quot;Variable&quot;,        # contient des combinaisons répétées
        times = c(&quot;Hauteur&quot;, &quot;Diametre&quot;),
        v.names = &quot;Valeur&quot;,
        varying = c(&quot;Hauteur&quot;, &quot;Diametre&quot;))</code></pre>
<pre><code>##              Plant Temps Variable Valeur
## a.1.Hauteur      a     1  Hauteur     67
## b.1.Hauteur      b     1  Hauteur     59
## c.1.Hauteur      c     1  Hauteur     62
## a.2.Hauteur      a     2  Hauteur     69
## b.2.Hauteur      b     2  Hauteur     65
## c.2.Hauteur      c     2  Hauteur     66
## a.1.Diametre     a     1 Diametre     15
## b.1.Diametre     b     1 Diametre     16
## c.1.Diametre     c     1 Diametre     13
## a.2.Diametre     a     2 Diametre     15
## b.2.Diametre     b     2 Diametre     17
## c.2.Diametre     c     2 Diametre     14</code></pre>
<pre class="r"><code># Avec gather
gather(data = plants_inter,
       key = Variable,
       value =  Valeur,
       Hauteur, Diametre)</code></pre>
<pre><code>##    Plant Temps Variable Valeur
## 1      a     1  Hauteur     67
## 2      b     1  Hauteur     59
## 3      c     1  Hauteur     62
## 4      a     2  Hauteur     69
## 5      b     2  Hauteur     65
## 6      c     2  Hauteur     66
## 7      a     1 Diametre     15
## 8      b     1 Diametre     16
## 9      c     1 Diametre     13
## 10     a     2 Diametre     15
## 11     b     2 Diametre     17
## 12     c     2 Diametre     14</code></pre>
</div>
<div id="format-long-pur-vers-format-intermediaire" class="section level4">
<h4>Format long pur vers format intermédiaire</h4>
<p>Il faut partir de <code>plants_long</code>.</p>
<pre class="r"><code># Avec reshape
reshape(data = plants_long,
        direction = &quot;wide&quot;,
        idvar = c(&quot;Plant&quot;, &quot;Temps&quot;),
        timevar = &quot;Variable&quot;,
        v.names = &quot;Valeur&quot;)</code></pre>
<pre><code>##   Plant Temps Valeur.Hauteur Valeur.Diametre
## 1     a     1             67              15
## 2     b     1             59              16
## 3     c     1             62              13
## 4     a     2             69              15
## 5     b     2             65              17
## 6     c     2             66              14</code></pre>
<pre class="r"><code># Avec spread
spread(data = plants_long,
       key = Variable,
       value = Valeur)</code></pre>
<pre><code>##   Plant Temps Diametre Hauteur
## 1     a     1       15      67
## 2     a     2       15      69
## 3     b     1       16      59
## 4     b     2       17      65
## 5     c     1       13      62
## 6     c     2       14      66</code></pre>
</div>
<div id="format-long-pur-vers-large-pur" class="section level4">
<h4>Format long pur vers large pur</h4>
<p>Il faut partir de <code>plants_long2</code>.</p>
<pre class="r"><code># Avec reshape
reshape(data = plants_long2,
        direction = &quot;wide&quot;,
        idvar = &quot;Plant&quot;,
        timevar = &quot;Variable&quot;,
        v.names = &quot;Valeur&quot;)</code></pre>
<pre><code>##   Plant Valeur.Hauteur_Temps1 Valeur.Hauteur_Temps2 Valeur.Diametre_Temps1
## 1     a                    67                    69                     15
## 2     b                    59                    65                     16
## 3     c                    62                    66                     13
##   Valeur.Diametre_Temps2
## 1                     15
## 2                     17
## 3                     14</code></pre>
<pre class="r"><code># Avec spread
spread(data = plants_long2,
       key = Variable,
       value = Valeur)</code></pre>
<pre><code>##   Plant Diametre_Temps1 Diametre_Temps2 Hauteur_Temps1 Hauteur_Temps2
## 1     a              15              15             67             69
## 2     b              16              17             59             65
## 3     c              13              14             62             66</code></pre>
</div>
<div id="format-intermediaire-pur-vers-large-pur" class="section level4">
<h4>Format intermédiaire pur vers large pur</h4>
<pre class="r"><code># Avec reshape
reshape(data = plants_inter,
        direction = &quot;wide&quot;,
        idvar = &quot;Plant&quot;,
        timevar = &quot;Temps&quot;,
        v.names = c(&quot;Hauteur&quot;, &quot;Diametre&quot;))</code></pre>
<pre><code>##   Plant Hauteur.1 Diametre.1 Hauteur.2 Diametre.2
## 1     a        67         15        69         15
## 2     b        59         16        65         17
## 3     c        62         13        66         14</code></pre>
<pre class="r"><code># Avec spread
# Il faut réaliser la transformation en deux temps, 
# parce que l&#39;argument value accepte seulement un nom.
spread(data = subset(plants_inter, select = - Diametre),
       key = Temps,
       value = Hauteur)</code></pre>
<pre><code>##   Plant  1  2
## 1     a 67 69
## 2     b 59 65
## 3     c 62 66</code></pre>
<pre class="r"><code>spread(data = subset(plants_inter, select = - Hauteur),
       key = Temps,
       value = Diametre)</code></pre>
<pre><code>##   Plant  1  2
## 1     a 15 15
## 2     b 16 17
## 3     c 13 14</code></pre>
<pre class="r"><code># Il faut retirer la variable non traitée, sinon elle est considérée comme participant à 
# l&#39;identification des individus. Il resterait à renommer les colonnes et à fusionner les 
# deux data frames</code></pre>
<hr />
</div>
</div>
</div>
</div>
<div id="synthese" class="section level1">
<h1>Synthèse</h1>
<div id="transformation-de-variables-1" class="section level4">
<h4>Transformation de variables</h4>
<ul>
<li>Ajout ou modification de variables dans un data frame :
<ul>
<li>assignation à une colonne, nouvelle pour un ajout,</li>
<li>concaténation de colonnes avec <code>cbind</code> ou <code>data.frame</code>,</li>
<li>fonction <code>transform</code>;</li>
</ul></li>
<li><p>Variable conditionnelle à une autre : <code>ifelse</code>;</p></li>
<li><p>Catégorisation d’une variable numérique : <code>cut</code>, <code>ave</code>;</p></li>
<li><p>Normalisation de valeurs : <code>scale</code>;</p></li>
<li>Manipulation de chaînes de caractères :
<ul>
<li><code>paste</code> : concatène des chaînes de caractères,</li>
<li><code>nchar</code> : calcule le nombre de caractères,</li>
<li><code>toupper</code> : transforme toutes les lettres en majuscules,</li>
<li><code>tolower</code> : transforme toutes les lettres en minuscules,</li>
<li><code>strsplit</code> : brise des chaînes de caractères, en coupant lors de la rencontre d’une certaine sous-chaîne de caractères,</li>
<li><code>substr</code> : extrait les caractères entre deux positions,</li>
<li><code>sub</code> ou <code>gsub</code> : remplacent la première occurrence ou toutes les occurrences d’une certaine sous-chaîne de caractères par une autre,</li>
<li><code>grep</code> et <code>grepl</code> : testent la présence d’une certaine sous-chaîne de caractères dans des chaînes de caractères,</li>
<li><code>chartr</code> : remplace des caractères par d’autres,</li>
<li><code>iconv</code> : convertit l’encodage de chaîne de caractères;</li>
</ul></li>
<li>Manipulation de dates :
<ul>
<li><code>as.Date</code> : convertit une chaîne de caractère en format date,</li>
<li><code>Sys.setlocale</code> : permet de modifier les paramètres régionaux d’une session R (utile lorsque nous voulons convertir en format <code>Date</code> des chaînes de caractères contenant des noms de mois dans une langue autre que celle du système d’exploitation de notre ordinateur),</li>
<li><code>difftime</code> : calcule l’intervalle de temps entre deux dates,</li>
<li><code>Sys.Date</code> : retourne la date courante,</li>
<li><code>format</code> : permet de modifier le format d’une date.</li>
</ul></li>
</ul>
</div>
<div id="manipulation-de-jeux-de-donnees-1" class="section level4">
<h4>Manipulation de jeux de données</h4>
<div id="fusion-de-donnees-1" class="section level5">
<h5>Fusion de données</h5>
<ul>
<li><p>Concaténer des vecteurs, matrices ou data frames en lignes (lignes = observations dans un data frame) : <code>rbind</code>.</p></li>
<li><p>Concaténer des vecteurs, matrices ou data frames en colonnes (lignes = variables dans un data frame) : <code>cbind</code>, <code>data.frame</code>.</p></li>
<li>Fusionner par association (ajout de colonnes en identifiant les lignes correspondantes) : <code>merge</code>
<ul>
<li>argument <code>by</code>, ou arguments <code>by.x</code> et <code>by.y</code>, pour spécifier les variables identifiant les unités (ou individus) à faire correspondre</li>
<li>argument <code>all</code>, ou arguments <code>all.x</code> et <code>all.y</code>, pour spécifier les lignes à conserver.</li>
</ul></li>
</ul>
</div>
<div id="modification-de-lordre-des-donnees-1" class="section level5">
<h5>Modification de l’ordre des données</h5>
<ul>
<li><code>rev</code> : renverse l’ordre des éléments;</li>
<li><code>sort</code> : ordonne les éléments d’un vecteur atomique
<ul>
<li>argument <code>decreasing = TRUE</code> pour ordre décroissant;</li>
</ul></li>
<li><code>order</code> : retourne la permutation des données requise pour réordonner les données selon l’ordre spécifié<br />
<span class="math inline">\(\rightarrow\)</span> pour effectuer le réordonnancement il faut fournir le résultat retourné par <code>order</code> en argument à l’opérateur d’extraction <code>[</code>
<ul>
<li>argument <code>decreasing = TRUE</code> pour ordre décroissant;</li>
</ul></li>
<li><code>arrange</code> du package <code>dplyr</code> : réordonne les observations dans un data frame
<ul>
<li>encadrer les noms de variable d’un appel à la fonction <code>desc</code> pour obtenir un ordre décroissant.</li>
</ul></li>
</ul>
</div>
<div id="changement-de-mise-en-forme-de-jeux-de-donnees-1" class="section level5">
<h5>Changement de mise en forme de jeux de données</h5>
<ul>
<li><p><code>t</code> : transpose des matrices</p></li>
<li><strong>Mise en forme « large »</strong> :
<ul>
<li>une seule ligne par individu (lorsque la largeur est maximale),</li>
<li>les vecteurs d’observations de certaines variables sont placés dans différentes colonnes.</li>
</ul></li>
<li><strong>Mise en forme « longue »</strong> :
<ul>
<li>plus d’une ligne par individu,</li>
<li>les vecteurs d’observations de certaines variables sont empilés dans une même colonne, les uns en dessous des autres,</li>
<li>comprend une ou des colonnes ayant pour but d’identifier à quelle variable est associée chaque observation.</li>
</ul></li>
</ul>
<table>
<thead>
<tr class="header">
<th>Transformation</th>
<th>Package <code>utils</code></th>
<th>Package <code>stats</code></th>
<th>Package <code>tidyr</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>large vers long</td>
<td><code>stack</code></td>
<td><code>reshape</code> (<code>direction = &quot;long&quot;</code>)</td>
<td><code>gather</code></td>
</tr>
<tr class="even">
<td>long vers large</td>
<td><code>unstack</code></td>
<td><code>reshape</code> (<code>direction = &quot;wide&quot;</code>)</td>
<td><code>spread</code></td>
</tr>
</tbody>
</table>
</div>
<div id="arguments-de-la-fonction-reshape" class="section level5">
<h5>Arguments de la fonction <code>reshape</code></h5>
<ul>
<li>En lien avec le contexte :
<ul>
<li><code>data</code> : data frame à remettre en forme;</li>
<li><code>direction</code> : direction de la remise en forme.</li>
</ul></li>
<li>En lien avec les individus :
<ul>
<li><code>idvar</code> : nom(s) colonne(s) contenant les identifiants des individus;</li>
<li><code>ids</code> : identifiants des individus.</li>
</ul></li>
<li>En lien avec les variables :
<ul>
<li><code>timevar</code> : nom colonne contenant les identifiants des variables;</li>
<li><code>times</code> : identifiants des variables.</li>
</ul></li>
<li>En lien avec les valeurs :
<ul>
<li><code>v.names</code> : nom(s) colonne(s) contenant les valeurs dans le format long ou intermédiaire;</li>
<li><code>varying</code> : noms colonnes contenant les valeurs dans le format large ou intermédiaire.</li>
</ul></li>
</ul>
<p>Les noms de colonnes doivent être fournis sous forme de chaînes de caractères.</p>
</div>
<div id="arguments-des-fonctions-gather-et-spread-du-package-tidyr" class="section level5">
<h5>Arguments des fonctions <code>gather</code> et <code>spread</code> du package <code>tidyr</code></h5>
<p><code>gather</code> : transformation vers un format plus long (rassembler valeurs dans une même colonne)<br />
<code>spread</code> : transformation vers un format plus large (étaler valeurs dans plusieurs colonnes)</p>
<ul>
<li>En lien avec le contexte :
<ul>
<li><code>data</code> : data frame à remettre en forme;</li>
</ul></li>
<li>En lien avec les individus :
<ul>
<li>aucun argument : colonne(s) contenant les identifiants des individus déduites de façon automatique = colonnes non identifiées dans les autres arguments.</li>
</ul></li>
<li>En lien avec les variables :
<ul>
<li><code>key</code> : nom colonne contenant les identifiants des variables; de vouloir modifier la mise en forme : des mesures répétées dans le temps.</li>
</ul></li>
<li>En lien avec les valeurs :
<ul>
<li><code>value</code> : nom colonne contenant les valeurs dans le format long.</li>
<li><code>...</code> : noms colonnes contenant les valeurs dans le format large;</li>
</ul></li>
</ul>
<p>Les noms de colonnes peuvent être fournis directement (ou sous forme de chaînes de caractères).</p>
<hr />
</div>
</div>
</div>
<div id="references" class="section level1">
<h1>Références</h1>
<ul>
<li>Spector, P. (2008). Data Manipulation with R. Springer, New York.</li>
</ul>
<div id="outils-alternatifs-pour-la-manipulation-de-donnees" class="section level4">
<h4>Outils alternatifs pour la manipulation de données :</h4>
<ul>
<li>Package <code>dplyr</code> :
<ul>
<li><a href="https://dplyr.tidyverse.org/" class="uri">https://dplyr.tidyverse.org/</a></li>
<li>Tutoriel d’étudiants : <a href="https://stt4230.rbind.io/tutoriels_etudiants/hiver_2016/manipuler_donnees_dplyr/">Manipulations de base sur un jeu de données</a></li>
<li>alternative à <code>cbind</code>, <code>data.frame</code>, <code>transform</code> ou une assignation à une nouvelle colonne :
<ul>
<li>ajouter de nouvelles variables avec <a href="https://dplyr.tidyverse.org/reference/mutate.html"><code>mutate</code> ou <code>transmute</code></a>;</li>
</ul></li>
<li>alternatives à <code>merge</code> :
<ul>
<li>fusionner des jeux de données avec les fonctions <a href="https://dplyr.tidyverse.org/reference/join.html"><code>left_join</code>, <code>right_join</code>, <code>inner_join</code>, <code>full_join</code>, <code>semi_join</code>, <code>nest_join</code> ou <code>anti_join</code></a>;</li>
</ul></li>
</ul></li>
<li>Package <code>tidyr</code> :
<ul>
<li><a href="https://tidyr.tidyverse.org/" class="uri">https://tidyr.tidyverse.org/</a></li>
<li>Tutoriel d’étudiants : <a href="https://stt4230.rbind.io/tutoriels_etudiants/hiver_2016/transformer_donnees_tidyr/">Réorganisation des données par concaténation et séparation d’observations</a></li>
</ul></li>
</ul>
</div>
<div id="pour-aller-plus-loin-en-manipulation-de-chaines-de-caracteres" class="section level4">
<h4>Pour aller plus loin en manipulation de chaînes de caractères :</h4>
<p>Le package <code>stringr</code> contient des fonctions pour la manipulation de chaînes de caractères alternatives aux fonctions du R de base. Ces fonctions portent des noms plus faciles à retenir et ont des noms d’arguments unifiés.</p>
<ul>
<li><a href="https://stringr.tidyverse.org/" class="uri">https://stringr.tidyverse.org/</a></li>
<li>Vignette : <a href="https://cran.r-project.org/web/packages/stringr/vignettes/stringr.html">Introduction to stringr</a></li>
<li>Tutoriel d’étudiants : <a href="https://stt4230.rbind.io/tutoriels_etudiants/hiver_2017/stringr/">Faciliter la manipulation de chaînes de caractères avec le package stringr</a></li>
</ul>
<p>Pour en savoir plus sur les expressions régulières :</p>
<ul>
<li><code>help(regexp)</code></li>
<li><a href="http://fr.wikipedia.org/wiki/Expression_rationnelle" class="uri">http://fr.wikipedia.org/wiki/Expression_rationnelle</a></li>
</ul>
<p>Autres références en manipulation de chaînes de caractères en R :</p>
<ul>
<li><a href="http://gastonsanchez.com/Handling_and_Processing_Strings_in_R.pdf" class="uri">http://gastonsanchez.com/Handling_and_Processing_Strings_in_R.pdf</a></li>
<li><a href="https://jozefhajnala.gitlab.io/r/r007-string-manipulation/" class="uri">https://jozefhajnala.gitlab.io/r/r007-string-manipulation/</a></li>
</ul>
</div>
<div id="pour-aller-plus-loin-en-manipulation-de-dates" class="section level4">
<h4>Pour aller plus loin en manipulation de dates :</h4>
<ul>
<li>documentation sur tous les format possibles : <code>help(strptime)</code>,</li>
<li>package <code>lubridate</code>, qui vise à faciliter le travail avec les dates en R :
<ul>
<li><a href="https://CRAN.R-project.org/package=lubridate" class="uri">https://CRAN.R-project.org/package=lubridate</a></li>
<li>Vignette : <a href="https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html">Do more with dates and times in R with lubridate 1.3.0</a></li>
<li>Tutoriel d’étudiants : <a href="https://stt4230.rbind.io/tutoriels_etudiants/hiver_2017/lubridate/">Manipuler facilement vos formats date avec lubridate</a></li>
</ul></li>
<li>Article de blogue : <a href="http://www.noamross.net/blog/2014/2/10/using-times-and-dates-in-r---presentation-code.html">Using Dates and Times in R</a></li>
</ul>
</div>
<div id="pour-aller-plus-loin-en-mise-en-forme-de-jeux-de-donnees" class="section level4">
<h4>Pour aller plus loin en mise en forme de jeux de données :</h4>
<ul>
<li>Fonction <code>arrange</code> du package <code>dplyr</code> ou du package <code>plyr</code> pour ordonner les observations d’un data frame :
<ul>
<li><a href="https://CRAN.R-project.org/package=dplyr" class="uri">https://CRAN.R-project.org/package=dplyr</a></li>
<li>Tutoriel d’étudiants : <a href="https://stt4230.rbind.io/tutoriels_etudiants/hiver_2014/ordonner_donnees_plyr/">Ordonner un data frame</a></li>
</ul></li>
<li>Fonctions <code>melt</code> et <code>dcast</code> du package <code>reshape2</code>, qui offre une alternative à la fonction <code>reshape</code> :
<ul>
<li><a href="https://CRAN.R-project.org/package=reshape2" class="uri">https://CRAN.R-project.org/package=reshape2</a></li>
<li>Tutoriel d’étudiants : <a href="https://stt4230.rbind.io/tutoriels_etudiants/hiver_2014/large_vers_long_reshape2/">Transformer un jeu de données d’une mise en forme large vers une mise en forme longue</a></li>
<li>Tutoriel d’étudiants : <a href="https://stt4230.rbind.io/tutoriels_etudiants/hiver_2014/long_vers_large_reshape2/">Transformer un jeu de données d’une mise en forme longue vers une mise en forme large en R</a></li>
</ul></li>
<li>Fonctions <code>gather</code> et <code>spread</code> du package <code>tidyr</code>, qui offre une alternative à la fonction <code>reshape</code> :
<ul>
<li><a href="https://CRAN.R-project.org/package=tidyr" class="uri">https://CRAN.R-project.org/package=tidyr</a></li>
<li>Tutoriel d’étudiants : <a href="https://stt4230.rbind.io/tutoriels_etudiants/hiver_2016/reformater_donnees_tidyr/">Transformer un jeu de données en forme large ou longue : base R vs le package tidyr</a></li>
</ul></li>
</ul>
</div>
<div id="pour-manipuler-des-data-frames-r-en-utilisant-le-langage-sql" class="section level4">
<h4>Pour manipuler des data frames R en utilisant le langage SQL :</h4>
<ul>
<li>Package <code>sqldf</code> : <a href="https://CRAN.R-project.org/package=sqldf" class="uri">https://CRAN.R-project.org/package=sqldf</a></li>
</ul>
</div>
</div>
