---
title: "Calculs statistiques et mathématiques en R"
linkTitle: "Calculs stat-math en R"
author: "Sophie Baillargeon, Université Laval"
date: "2020-02-26"
weight: 2
slug: "calculs_stat_math_r"
categories: ["cours_2020-03-10"]
categories_weight: 1
lastmodifierdisplayname : "Sophie Baillargeon"
lastmodifieremail: "sophie.baillargeon@mat.ulaval.ca"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
    highlight: tango
  blogdown::html_page:
    toc: yes
    toc_depth: 3
    highlight: tango
header-includes:
- \usepackage[french]{babel}
- \frenchbsetup{StandardLayout}
- \hypersetup{colorlinks=true, urlcolor = {blue}, linkcolor = {blue}}
- \renewcommand{\linethickness}{0.05em}
editor_options: 
  chunk_output_type: console
---





<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { background-color: #f8f8f8; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<div id="TOC">
<ul>
<li><a href="#calculs-statistiques">Calculs statistiques</a><ul>
<li><a href="#distributions-de-probabilité">Distributions de probabilité</a><ul>
<li><a href="#fonction-de-densité">Fonction de densité</a></li>
<li><a href="#fonction-de-répartition">Fonction de répartition</a></li>
<li><a href="#fonction-quantile">Fonction quantile</a></li>
</ul></li>
<li><a href="#génération-de-nombres-pseudo-aléatoires">Génération de nombres pseudo-aléatoires</a><ul>
<li><a href="#fonction-sample">Fonction <code>sample</code></a></li>
<li><a href="#germe-de-la-génération-pseudo-aléatoire">Germe de la génération pseudo-aléatoire</a></li>
</ul></li>
<li><a href="#calcul-de-statistiques-descriptives">Calcul de statistiques descriptives</a></li>
<li><a href="#tests-statistiques">Tests statistiques</a></li>
<li><a href="#ajustement-de-modèles">Ajustement de modèles</a><ul>
<li><a href="#formules">Formules</a></li>
<li><a href="#arguments-accompagnant-les-formules">Arguments accompagnant les formules</a></li>
<li><a href="#manipulation-de-la-sortie-dune-fonction-dajustement-de-modèle">Manipulation de la sortie d’une fonction d’ajustement de modèle</a></li>
<li><a href="#résultats-additionnels-fournis-par-summary">Résultats additionnels fournis par <code>summary</code></a></li>
<li><a href="#mise-en-forme-de-la-sortie-dune-fonction-dajustement-de-modèle-avec-le-package-broom">Mise en forme de la sortie d’une fonction d’ajustement de modèle avec le package <code>broom</code></a></li>
</ul></li>
<li><a href="#méthodes-statistiques-diverses">Méthodes statistiques diverses</a></li>
</ul></li>
<li><a href="#calculs-mathématiques">Calculs mathématiques</a><ul>
<li><a href="#opérateurs-et-fonctions-de-base">Opérateurs et fonctions de base</a></li>
<li><a href="#calcul-de-distances">Calcul de distances</a></li>
<li><a href="#algèbre-linéaire">Algèbre linéaire</a></li>
<li><a href="#calcul-différentiel-et-intégral">Calcul différentiel et intégral</a></li>
<li><a href="#optimisation-numérique">Optimisation numérique</a></li>
</ul></li>
<li><a href="#résumé">Résumé</a></li>
<li><a href="#références">Références</a></li>
</ul>
</div>

<hr />
<div id="calculs-statistiques" class="section level1">
<h1>Calculs statistiques</h1>
<p>L’utilité première du logiciel R est la réalisation de calculs statistiques. Les principaux outils pour réaliser de tels calculs sont présentés ici. Cette section traite de fonctions permettant de manipuler des distributions de probabilité, de générer des nombres pseudo-aléatoires, de réaliser de tests statistiques et d’ajuster des modèles statistiques.</p>
<div id="distributions-de-probabilité" class="section level2">
<h2>Distributions de probabilité</h2>
<p>Le package <code>stats</code> de l’installation de base de R comprend, pour plusieurs distributions de probabilité, des fonctions de calcul de :</p>
<ul>
<li>la fonction de densité (forme <code>dxxx</code> où <code>xxx</code> change selon la distribution),</li>
<li>la fonction de répartition (forme <code>pxxx</code>) et</li>
<li>la fonction quantile (forme <code>qxxx</code>).</li>
</ul>
<p>La fiche d’aide ouverte par la commande <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/Distributions.html"><code>help(Distributions)</code></a> énumère toutes les distributions de probabilité offertes dans le package <code>stats</code>. Il existe aussi des fonctions relatives à d’autres distributions de probabilité dans des packages sur le CRAN (voir <a href="https://CRAN.R-project.org/view=Distributions" class="uri">https://CRAN.R-project.org/view=Distributions</a> pour découvrir ce qui est offert).</p>
<p>Ces fonctions sont utiles notamment pour calculer des valeurs critiques ou des seuils observés de tests d’hypothèses. Un exemple est présenté plus loin.</p>
<div id="fonction-de-densité" class="section level3">
<h3>Fonction de densité</h3>
<p>Les fonctions R implémentant des <a href="https://fr.wikipedia.org/wiki/Densit%C3%A9_de_probabilit%C3%A9">fonctions de densité</a> ont un nom qui débute par le lettre <code>d</code> pour <em>density</em>. Leur premier argument est toujours un vecteur de valeurs en lesquelles calculer la fonction de densité. Les arguments suivants servent à spécifier les valeurs des paramètres de la distribution.</p>
<p>Dans le cas d’une variable aléatoire discrète, la fonction de densité est plus justement appelée <a href="https://fr.wikipedia.org/wiki/Fonction_de_masse_(probabilit%C3%A9s)">fonction de masse</a>. Il s’agit alors d’une probabilité, pour une variable aléatoire suivant une certaine distribution, de prendre une certaine valeur.</p>
<div id="exemple-distribution-binomiale" class="section level4">
<h4>Exemple : Distribution binomiale</h4>

<p>Soit <span class="math inline">\(X\)</span> une variable aléatoire représentant le nombre de 6 obtenus lors de 5 lancés d’un dé. Cette variable aléatoire suit une <a href="https://fr.wikipedia.org/wiki/Loi_binomiale">distribution binomiale</a> de paramètres <span class="math inline">\(n = 5\)</span> et <span class="math inline">\(p = 1/6\)</span>, donc <span class="math inline">\(X \sim Bin(n = 5, p = 1/6)\)</span>.</p>
<p>Calculons <span class="math inline">\(P(X = 2)\)</span>, soit la probabilité que la variable aléatoire <span class="math inline">\(X\)</span> prenne la valeur 2.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">dbinom</span>(<span class="dt">x =</span> <span class="dv">2</span>, <span class="dt">size =</span> <span class="dv">5</span>, <span class="dt">prob =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">6</span>)</a></code></pre></div>
<pre><code>## [1] 0.160751</code></pre>
<p>La fonction <code>dbinom</code> implémente donc la fonction de masse d’une distribution binomiale. Les arguments <code>size</code> et <code>prob</code> sont les paramètres <span class="math inline">\(n\)</span> et <span class="math inline">\(p\)</span> de la distribution, selon la notation utilisée ci-dessus.</p>
<p>Les fonctions de la famille <code>dxxx</code> peuvent calculer plusieurs valeurs de densité par un seul appel de la fonction, car celles-ci acceptent des valeurs d’arguments de longueur supérieure à 1. Ces fonctions travaillent donc de façon vectorielle, comme presque toutes les fonctions de calcul en R.</p>
<p>Voici un exemple de code R permettant de représenter graphiquement la densité <span class="math inline">\(Bin(n = 5, p = 1/6)\)</span> complète, en mettant en évidence la valeur calculée ci-dessus, soit <span class="math inline">\(P(X = 2)\)</span>.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">barplot</span>(</a>
<a class="sourceLine" id="cb3-2" title="2">  <span class="dt">height =</span> <span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">5</span>, <span class="dt">size =</span> <span class="dv">5</span>, <span class="dt">prob =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">6</span>), </a>
<a class="sourceLine" id="cb3-3" title="3">  <span class="dt">names.arg =</span> <span class="dv">0</span><span class="op">:</span><span class="dv">5</span>,</a>
<a class="sourceLine" id="cb3-4" title="4">  <span class="dt">main =</span> <span class="st">&quot;Densité Binomiale(5,1/6)&quot;</span>,</a>
<a class="sourceLine" id="cb3-5" title="5">  <span class="dt">xlab =</span> <span class="st">&quot;x&quot;</span>,</a>
<a class="sourceLine" id="cb3-6" title="6">  <span class="dt">ylab =</span> <span class="st">&quot;dbinom(x, size = 5, prob = 1/6)&quot;</span>)</a>
<a class="sourceLine" id="cb3-7" title="7"><span class="kw">barplot</span>(</a>
<a class="sourceLine" id="cb3-8" title="8">  <span class="dt">height =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="kw">dbinom</span>(<span class="dv">2</span>, <span class="dt">size =</span> <span class="dv">5</span>, <span class="dt">prob =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">6</span>), <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>),</a>
<a class="sourceLine" id="cb3-9" title="9">  <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>,</a>
<a class="sourceLine" id="cb3-10" title="10">  <span class="dt">add =</span> <span class="ot">TRUE</span></a>
<a class="sourceLine" id="cb3-11" title="11">)</a></code></pre></div>
<p><img src="/calculs/calculs_stat_math_r_2020_files/figure-html/unnamed-chunk-2-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<div id="exemple-distribution-normale-standard" class="section level4">
<h4>Exemple : Distribution normale standard</h4>

<p>Supposons maintenant que <span class="math inline">\(X\)</span> est une variable aléatoire continue de <a href="https://fr.wikipedia.org/wiki/Loi_normale">distribution normale</a> standard, donc <span class="math inline">\(X \sim N(\mu = 0, \sigma^2 = 1)\)</span>. La valeur de la fonction de densité pour cette distribution en la valeur <span class="math inline">\(x = 1\)</span>, souvent notée <span class="math inline">\(f_X(1)\)</span>, vaut :</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="kw">dnorm</span>(<span class="dt">x =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.2419707</code></pre>
<p>Voici une représentation graphique de la densité complète dans laquelle la valeur calculée ci-dessus est mise en évidence.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">curve</span>(<span class="dt">expr =</span> dnorm, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="dt">main =</span> <span class="st">&quot;Densité N(0,1)&quot;</span>)</a>
<a class="sourceLine" id="cb6-2" title="2"><span class="kw">segments</span>(</a>
<a class="sourceLine" id="cb6-3" title="3">  <span class="dt">x0 =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">1</span>), <span class="dt">y0 =</span> <span class="kw">dnorm</span>(<span class="dv">1</span>), <span class="dt">x1 =</span> <span class="dv">1</span>, <span class="dt">y1 =</span> <span class="kw">c</span>(<span class="kw">dnorm</span>(<span class="dv">1</span>), <span class="dv">-1</span>), </a>
<a class="sourceLine" id="cb6-4" title="4">  <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span></a>
<a class="sourceLine" id="cb6-5" title="5">)</a></code></pre></div>
<p><img src="/calculs/calculs_stat_math_r_2020_files/figure-html/unnamed-chunk-4-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Ici, nous n’avons pas eu besoin de fournir des valeurs aux arguments de la fonction <code>dnorm</code> relatifs aux paramètres de la distribution, parce que nous avons utilisés leurs valeurs par défaut. Ces paramètres, pour la densité <span class="math inline">\(N(\mu, \sigma^2)\)</span>, sont représentés par les arguments <code>mean</code> = <span class="math inline">\(\mu\)</span> et <code>sd</code> = <span class="math inline">\(\sigma\)</span> (remarquez que l’argument de la fonction R représente l’écart-type, pas la variance).</p>
<p>Tout comme le premier argument, nommé <span class="math inline">\(x\)</span>, les arguments des fonctions de la famille <code>dxxx</code> représentant des paramètres de la distribution acceptent aussi en entrée plus d’une valeur. Voici un exemple, qui permet de calculer la densité en <span class="math inline">\(x = 1\)</span> pour <span class="math inline">\(X \sim N(\mu = -2, \sigma^2 = 1)\)</span>, <span class="math inline">\(X \sim N(\mu = 0, \sigma^2 = 2.25)\)</span> et <span class="math inline">\(X \sim N(\mu = 1, \sigma^2 = 4)\)</span> en un seul appel à la fonction <code>dnorm</code>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw">dnorm</span>(<span class="dt">x =</span> <span class="dv">1</span>, <span class="dt">mean =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">sd =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">1.5</span>, <span class="dv">2</span>))</a></code></pre></div>
<pre><code>## [1] 0.004431848 0.212965337 0.199471140</code></pre>
</div>
</div>
<div id="fonction-de-répartition" class="section level3">
<h3>Fonction de répartition</h3>
<p>La <a href="https://fr.wikipedia.org/wiki/Fonction_de_r%C3%A9partition">fonction de répartition</a> d’une variable aléatoire <span class="math inline">\(X\)</span> est définie par <span class="math inline">\(F_X(x) = P(X \le x)\)</span>. Il s’agit donc toujours d’une probabilité, d’où le <code>p</code> au début des noms des fonctions R implémentant des fonctions de répartition.</p>
<div id="exemple-distribution-normale-standard-1" class="section level4">
<h4>Exemple : Distribution normale standard</h4>

<p>Prenons encore comme exemple la distribution normale standard. Nous avons donc <span class="math inline">\(X \sim N(0, 1)\)</span>. Calculons la valeur de la fonction de répartition de cette variable aléatoire en <span class="math inline">\(x = 1\)</span>.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="kw">pnorm</span>(<span class="dt">q =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.8413447</code></pre>
<p>Il s’agit de la valeur de la probabilité <span class="math inline">\(P(X \le 1)\)</span>.</p>
<p>Le premier argument des fonctions de la famille <code>pxxx</code> ne se nomme pas <code>x</code>, il se nomme plutôt <code>q</code>. Cette lettre réfère au mot quantile et souligne le lien entre les fonctions de répartition et les fonctions quantiles. Les arguments suivants des fonctions de la famille <code>pxxx</code> permettent de spécifier les valeurs des paramètres de la distribution, comme pour les fonctions de la famille <code>pxxx</code>.</p>
<p>Voici une illustration graphique du lien entre la fonction de densité et la fonction de répartition en utilisant la distribution normale standard. La valeur de la fonction de répartition en un point quelconque <span class="math inline">\(x\)</span> (dans le graphique <span class="math inline">\(x = 1\)</span>) est égale à l’aire sous la courbe de densité entre <span class="math inline">\(-\infty\)</span> et <span class="math inline">\(x\)</span>.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">par.default &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb11-2" title="2"></a>
<a class="sourceLine" id="cb11-3" title="3"><span class="kw">curve</span>(<span class="dt">expr =</span> dnorm, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="dt">main =</span> <span class="st">&quot;Densité N(0,1)&quot;</span>)</a>
<a class="sourceLine" id="cb11-4" title="4">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">-3</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">length =</span> <span class="dv">100</span>)</a>
<a class="sourceLine" id="cb11-5" title="5"><span class="kw">polygon</span>(<span class="dt">x =</span> <span class="kw">c</span>(x, <span class="dv">1</span>, <span class="dv">-3</span>), <span class="dt">y =</span> <span class="kw">c</span>(<span class="kw">dnorm</span>(x), <span class="dv">0</span>, <span class="dv">0</span>), <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb11-6" title="6"></a>
<a class="sourceLine" id="cb11-7" title="7"><span class="kw">curve</span>(</a>
<a class="sourceLine" id="cb11-8" title="8">  <span class="dt">expr =</span> pnorm, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), </a>
<a class="sourceLine" id="cb11-9" title="9">  <span class="dt">main =</span> <span class="st">&quot;Fonction de répartition N(0,1)&quot;</span>, <span class="dt">xname =</span> <span class="st">&quot;q&quot;</span></a>
<a class="sourceLine" id="cb11-10" title="10">)</a>
<a class="sourceLine" id="cb11-11" title="11"><span class="kw">segments</span>(</a>
<a class="sourceLine" id="cb11-12" title="12">  <span class="dt">x0 =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">1</span>), <span class="dt">y0 =</span> <span class="kw">pnorm</span>(<span class="dv">1</span>), <span class="dt">x1 =</span> <span class="dv">1</span>, <span class="dt">y1 =</span> <span class="kw">c</span>(<span class="kw">pnorm</span>(<span class="dv">1</span>), <span class="dv">-1</span>), </a>
<a class="sourceLine" id="cb11-13" title="13">  <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span></a>
<a class="sourceLine" id="cb11-14" title="14">)</a>
<a class="sourceLine" id="cb11-15" title="15"></a>
<a class="sourceLine" id="cb11-16" title="16"><span class="kw">par</span>(par.default)</a></code></pre></div>
<p><img src="/calculs/calculs_stat_math_r_2020_files/figure-html/unnamed-chunk-7-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="fonction-quantile" class="section level3">
<h3>Fonction quantile</h3>
<p>La <a href="https://fr.wikipedia.org/wiki/Fonction_quantile">fonction quantile</a> est l’inverse généralisé de la fonction de répartition. Les fonctions R implémentant des fonctions quantile ont un nom qui débute par le lettre <code>q</code> pour <em>quantile</em>.</p>
<div id="exemple-distribution-normale-standard-2" class="section level4">
<h4>Exemple : Distribution normale standard</h4>

<p>Pour clore l’exemple de la distribution normale standard, voyons de quoi à l’air la fonction quantile de cette distribution.</p>
<p>Premièrement, calculons la valeur de la fonction quantile en un point, disons en <span class="math inline">\(p = 0.8413447\)</span>.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="kw">qnorm</span>(<span class="dt">p =</span> <span class="fl">0.8413447</span>)</a></code></pre></div>
<pre><code>## [1] 0.9999998</code></pre>
<p>Il s’agit de la valeur <span class="math inline">\(x\)</span> pour laquelle <span class="math inline">\(P(X \le x) = 0.8413447\)</span>, où <span class="math inline">\(X \sim N(0, 1)\)</span>.</p>
<p>Le premier argument d’une fonction de la famille <code>qxxx</code> se nomme <code>p</code>. Cette notation peut nous aider à nous rappeler que cet argument représente une probabilité et accepte donc seulement des valeurs entre 0 et 1. Encore une fois, les arguments suivants des fonctions de la famille <code>qxxx</code> permettent de spécifier les valeurs des paramètres de la distribution.</p>
<p>Le graphique suivant illustre le lien entre la fonction de répartition et la fonction quantile. Le graphique de la fonction quantile est simplement obtenu en inversant les axes du graphique de la fonction de répartition.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1">par.default &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">pty =</span> <span class="st">&quot;s&quot;</span>)</a>
<a class="sourceLine" id="cb14-2" title="2"></a>
<a class="sourceLine" id="cb14-3" title="3"><span class="kw">curve</span>(</a>
<a class="sourceLine" id="cb14-4" title="4">  <span class="dt">expr =</span> pnorm, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="dt">n =</span> <span class="dv">1000</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">asp=</span><span class="dv">6</span>,</a>
<a class="sourceLine" id="cb14-5" title="5">  <span class="dt">main =</span> <span class="st">&quot;Fonction de répartition N(0,1)&quot;</span>, <span class="dt">xname =</span> <span class="st">&quot;q&quot;</span></a>
<a class="sourceLine" id="cb14-6" title="6">)</a>
<a class="sourceLine" id="cb14-7" title="7"><span class="kw">segments</span>(</a>
<a class="sourceLine" id="cb14-8" title="8">  <span class="dt">x0 =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">1</span>), <span class="dt">y0 =</span> <span class="kw">pnorm</span>(<span class="dv">1</span>),  <span class="dt">x1 =</span> <span class="dv">1</span>, <span class="dt">y1 =</span> <span class="kw">c</span>(<span class="kw">pnorm</span>(<span class="dv">1</span>), <span class="dv">-1</span>), </a>
<a class="sourceLine" id="cb14-9" title="9">  <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span></a>
<a class="sourceLine" id="cb14-10" title="10">)</a>
<a class="sourceLine" id="cb14-11" title="11"></a>
<a class="sourceLine" id="cb14-12" title="12"><span class="kw">curve</span>(</a>
<a class="sourceLine" id="cb14-13" title="13">  <span class="dt">expr =</span> qnorm, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">n =</span> <span class="dv">1000</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="dt">asp=</span><span class="dv">1</span><span class="op">/</span><span class="dv">6</span>, </a>
<a class="sourceLine" id="cb14-14" title="14">  <span class="dt">main =</span> <span class="st">&quot;Fonction quantile  N(0,1)&quot;</span>, <span class="dt">xname =</span> <span class="st">&quot;p&quot;</span></a>
<a class="sourceLine" id="cb14-15" title="15">)</a>
<a class="sourceLine" id="cb14-16" title="16"><span class="kw">segments</span>(</a>
<a class="sourceLine" id="cb14-17" title="17">  <span class="dt">x0 =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.2</span>, <span class="kw">pnorm</span>(<span class="dv">1</span>)), <span class="dt">y0 =</span> <span class="kw">qnorm</span>(<span class="kw">pnorm</span>(<span class="dv">1</span>)), </a>
<a class="sourceLine" id="cb14-18" title="18">  <span class="dt">x1 =</span> <span class="kw">pnorm</span>(<span class="dv">1</span>), <span class="dt">y1 =</span> <span class="kw">c</span>(<span class="kw">qnorm</span>(<span class="kw">pnorm</span>(<span class="dv">1</span>)), <span class="dv">-4</span>), </a>
<a class="sourceLine" id="cb14-19" title="19">  <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span></a>
<a class="sourceLine" id="cb14-20" title="20">)</a>
<a class="sourceLine" id="cb14-21" title="21"></a>
<a class="sourceLine" id="cb14-22" title="22"><span class="kw">par</span>(par.default)</a></code></pre></div>
<p><img src="/calculs/calculs_stat_math_r_2020_files/figure-html/unnamed-chunk-9-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="génération-de-nombres-pseudo-aléatoires" class="section level2">
<h2>Génération de nombres pseudo-aléatoires</h2>
<p>En R, les fonctions <code>rxxx</code> permettent de générer pseudo-aléatoirement des observations selon une certaine distribution désignée par <code>xxx</code>. La lettre <code>r</code> au début de leur nom signifie <em>random</em>.</p>
<p>Par exemple, voici la représentation graphique de 3 échantillons générés aléatoirement selon 3 distributions différentes : des distributions normale, uniforme continue et khi-deux. Pour chaque échantillon, nous traçons l’histogramme des observations simulées pour représenter leur densité empirique. Nous superposons à cet histogramme la courbe de densité de la distribution théorique à partir de laquelle les observations ont été générées.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1">par.default &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</a>
<a class="sourceLine" id="cb15-2" title="2"></a>
<a class="sourceLine" id="cb15-3" title="3"><span class="co"># Densité normale d&#39;espérance 5 et de variance 4</span></a>
<a class="sourceLine" id="cb15-4" title="4">x1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">1000</span>, <span class="dt">mean =</span> <span class="dv">5</span>, <span class="dt">sd =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb15-5" title="5"><span class="kw">hist</span>(<span class="dt">x =</span> x1, <span class="dt">freq =</span> <span class="ot">FALSE</span>, <span class="dt">ylab =</span> <span class="st">&quot;Proportion&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Densité empirique de x1&quot;</span>)</a>
<a class="sourceLine" id="cb15-6" title="6"><span class="kw">curve</span>(<span class="dt">expr =</span> <span class="kw">dnorm</span>(x, <span class="dt">mean =</span> <span class="dv">5</span>, <span class="dt">sd =</span> <span class="dv">2</span>), <span class="dt">add =</span> <span class="ot">TRUE</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb15-7" title="7"><span class="kw">title</span>(<span class="dt">main =</span> <span class="st">&quot;courbe bleue = densité visée N(5,4)&quot;</span>, <span class="dt">line =</span> <span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb15-8" title="8"></a>
<a class="sourceLine" id="cb15-9" title="9"><span class="co"># Densité uniforme continue entre 2 et 8</span></a>
<a class="sourceLine" id="cb15-10" title="10">x2 &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">1000</span>, <span class="dt">min =</span> <span class="dv">2</span>, <span class="dt">max =</span> <span class="dv">8</span>)</a>
<a class="sourceLine" id="cb15-11" title="11"><span class="kw">hist</span>(<span class="dt">x =</span> x2, <span class="dt">freq =</span> <span class="ot">FALSE</span>, <span class="dt">ylab =</span> <span class="st">&quot;Proportion&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Densité empirique de x2&quot;</span>)</a>
<a class="sourceLine" id="cb15-12" title="12"><span class="kw">curve</span>(<span class="dt">expr =</span> <span class="kw">dunif</span>(x, <span class="dt">min =</span> <span class="dv">2</span>, <span class="dt">max =</span> <span class="dv">8</span>), <span class="dt">add =</span> <span class="ot">TRUE</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb15-13" title="13"><span class="kw">title</span>(<span class="dt">main =</span> <span class="st">&quot;courbe bleue = densité visée U(2,8)&quot;</span>, <span class="dt">line =</span> <span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb15-14" title="14"></a>
<a class="sourceLine" id="cb15-15" title="15"><span class="co"># Densité chi-carré à 4 degrés de liberté</span></a>
<a class="sourceLine" id="cb15-16" title="16">x3 &lt;-<span class="st"> </span><span class="kw">rchisq</span>(<span class="dv">1000</span>, <span class="dt">df =</span> <span class="dv">4</span>)</a>
<a class="sourceLine" id="cb15-17" title="17"><span class="kw">hist</span>(<span class="dt">x =</span> x3, <span class="dt">freq =</span> <span class="ot">FALSE</span>, <span class="dt">ylab =</span> <span class="st">&quot;Proportion&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Densité empirique de x3&quot;</span>)</a>
<a class="sourceLine" id="cb15-18" title="18"><span class="kw">curve</span>(<span class="dt">expr =</span> <span class="kw">dchisq</span>(x, <span class="dt">df =</span> <span class="dv">4</span>), <span class="dt">add =</span> <span class="ot">TRUE</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb15-19" title="19"><span class="kw">title</span>(<span class="dt">main =</span> <span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&quot;courbe bleue = densité visée &quot;</span>, chi[<span class="dv">4</span>]<span class="op">^</span><span class="dv">2</span>)), <span class="dt">line =</span> <span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb15-20" title="20"></a>
<a class="sourceLine" id="cb15-21" title="21"><span class="kw">par</span>(par.default)</a></code></pre></div>
<p><img src="/calculs/calculs_stat_math_r_2020_files/figure-html/unnamed-chunk-11-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>Comme nous pouvons le constater sur ces graphiques, la distribution empirique des observations générées avec ces fonctions se rapproche vraiment de la distribution théorique demandée. En générant un nombre encore plus grand d’observations (ici nous en avons généré 1000 pour chaque distribution), la densité empirique se rapprocherait encore plus de la densité théorique.</p>
<div id="fonction-sample" class="section level3">
<h3>Fonction <code>sample</code></h3>
<p>La fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/sample.html"><code>sample</code></a> permet de tirer un échantillon aléatoire parmi un ensemble d’éléments fourni à son argument <code>x</code> sous forme de vecteur.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="st">&quot;Luc&quot;</span>, <span class="st">&quot;Kim&quot;</span>, <span class="st">&quot;Paul&quot;</span>, <span class="st">&quot;Ève&quot;</span>))</a></code></pre></div>
<pre><code>## [1] &quot;Paul&quot; &quot;Ève&quot;  &quot;Kim&quot;  &quot;Luc&quot;</code></pre>
<p>Ce vecteur peut contenir des données de n’importe quel type.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">6</span>)</a></code></pre></div>
<pre><code>## [1] 4 3 1 6 5 2</code></pre>
<p>Par défaut, <code>sample</code> effectue un tirage sans remise et sélectionne autant d’éléments que l’ensemble de départ en contient. La fonction effectue donc une permutation aléatoire des éléments de l’ensemble de départ. L’argument <code>size</code> permet cependant de contrôler la taille de l’échantillon tiré.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">size =</span> <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1] 6 4 5 1 3</code></pre>
<p>L’argument <code>replace</code> permet quant à lui de spécifier si le tirage doit être effectué avec (<code>replace = TRUE</code>) ou sans remise (<code>replace = FALSE</code>, valeur par défaut).</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">size =</span> <span class="dv">10</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>##  [1] 1 6 1 6 6 5 4 3 3 1</code></pre>
<p>Il est aussi possible d’attribuer des probabilité de sélection à chacun des éléments grâce à l’argument <code>prob</code>. Par défaut, tous les éléments ont une probabilité égale d’être tiré.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">size =</span> <span class="dv">20</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">prob =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">2</span>, <span class="kw">rep</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">10</span>, <span class="dt">times =</span> <span class="dv">5</span>)))</a></code></pre></div>
<pre><code>##  [1] 1 1 1 4 1 2 5 1 1 3 1 4 1 3 3 1 6 2 1 1</code></pre>
<p>La fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/sample.html"><code>sample.int</code></a> est très similaire à la fonction <code>sample</code>, mais elle prend comme premier argument un seul entier, <code>n</code>, et tire aléatoirement <code>size</code> entiers entre 1 et <code>n</code>.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1"><span class="kw">sample.int</span>(<span class="dt">n =</span> <span class="dv">6</span>, <span class="dt">size =</span> <span class="dv">4</span>)</a></code></pre></div>
<pre><code>## [1] 6 1 2 5</code></pre>
<p>Si nous souhaitons sélectionner aléatoirement des observations (lignes) dans un jeu de données, il est d’usage de sélectionner d’abord des entiers compris entre 1 et le nombre total d’observations, puis d’extraire du jeu de donnée les observations sur les lignes portant les numéros sélectionnés. Voici un exemple, utilisant les données sur les <a href="https://stat.ethz.ch/R-manual/R-patched/library/datasets/html/iris.html">iris de Fisher</a> incluses dans l’installation de base de R.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="kw">str</span>(iris)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1">index_ech &lt;-<span class="st"> </span><span class="kw">sample.int</span>(<span class="dt">n =</span> <span class="kw">nrow</span>(iris), <span class="dt">size =</span> <span class="dv">5</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb30-2" title="2">index_ech</a></code></pre></div>
<pre><code>## [1]  32  83 118 116  67</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1">iris_ech &lt;-<span class="st"> </span>iris[index_ech, ]</a>
<a class="sourceLine" id="cb32-2" title="2">iris_ech</a></code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
## 32           5.4         3.4          1.5         0.4     setosa
## 83           5.8         2.7          3.9         1.2 versicolor
## 118          7.7         3.8          6.7         2.2  virginica
## 116          6.4         3.2          5.3         2.3  virginica
## 67           5.6         3.0          4.5         1.5 versicolor</code></pre>
</div>
<div id="germe-de-la-génération-pseudo-aléatoire" class="section level3">
<h3>Germe de la génération pseudo-aléatoire</h3>
<p>Les nombres générés avec les fonctions <code>rxxx</code> et les échantillons tirés avec <code>sample</code> sont qualifiés de pseudo-aléatoires, car ils proviennent d’un algorithme déterministe qui tente de reproduire le hasard. Un tel algorithme est nommé en anglais <em>random number generator</em> (RNG) ou <em>pseudo-random number generator</em>. La fiche d’aide ouverte par la commande <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/Random.html"><code>help(Random)</code></a> contient de l’information sur la génération de nombres pseudo-aléatoires en R.</p>
<p>Plusieurs RNG sont implémentés en R. Celui utilisé par défaut, nommé Mersenne Twister, a été choisi parce qu’il est réputé être bon. Sans entrer dans les détails du fonctionnement des RNG implémentés dans le package <code>base</code> de R, il faut savoir qu’ils travaillent tous à partir d’une séquence de nombres appelée <em>germe</em> (en anglais <em>seed</em>). En contrôlant ce germe, il est possible de générer de nouveau, autant de fois que désiré, les mêmes valeurs.</p>
<p>Par défaut, R contrôle le germe des RNG de façon automatique. Chaque fois qu’une commande faisant intervenir un RNG est évaluée, R crée un nouveau germe à partir, notamment, de l’heure à laquelle la commande est soumise. Ainsi, deux générations pseudo-aléatoires consécutives ne produisent en général pas le même résultat.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> letters, <span class="dt">size =</span> <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1] &quot;m&quot; &quot;b&quot; &quot;y&quot; &quot;f&quot; &quot;n&quot;</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> letters, <span class="dt">size =</span> <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1] &quot;u&quot; &quot;s&quot; &quot;p&quot; &quot;b&quot; &quot;j&quot;</code></pre>
<p>En tout temps, il est possible de connaître le germe du RNG en R. Il est stocké dans un objet nommé <code>.Random.seed</code>. Cet objet est un vecteur numérique de longueur 626 pour le RNG Mersenne Twister. Voyons de quoi ont l’air les premiers éléments de ce vecteur à différents moments.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1"><span class="kw">str</span>(.Random.seed)</a></code></pre></div>
<pre><code>##  int [1:626] 10403 77 -1392043757 981309122 -2020273804 -143021705 216357485 -1895090..</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> letters, <span class="dt">size =</span> <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1] &quot;g&quot; &quot;r&quot; &quot;l&quot; &quot;a&quot; &quot;q&quot;</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1"><span class="kw">str</span>(.Random.seed)</a></code></pre></div>
<pre><code>##  int [1:626] 10403 82 -1392043757 981309122 -2020273804 -143021705 216357485 -1895090..</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> letters, <span class="dt">size =</span> <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1] &quot;m&quot; &quot;o&quot; &quot;u&quot; &quot;q&quot; &quot;w&quot;</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1"><span class="kw">str</span>(.Random.seed)</a></code></pre></div>
<pre><code>##  int [1:626] 10403 87 -1392043757 981309122 -2020273804 -143021705 216357485 -1895090..</code></pre>
<p>Nous constatons qu’au moins un élément de ce vecteur (le deuxième élément) change à chaque fois que nous appelons la fonction <code>sample</code>. La fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/Random.html"><code>set.seed</code></a> permet de fixer le germe du RNG à partir d’une seule valeur entière. Par exemple, la commande suivante :</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1"><span class="kw">set.seed</span>(<span class="dv">753</span>)</a></code></pre></div>
<p>spécifie le germe suivant :</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1"><span class="kw">str</span>(.Random.seed)</a></code></pre></div>
<pre><code>##  int [1:626] 10403 624 302719261 615841082 -1828406925 -1314498536 214287161 14262109..</code></pre>
<p>En soumettant de nouveau le même appel à la fonction <code>sample</code>, nous obtenons l’échantillon suivant.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> letters, <span class="dt">size =</span> <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1] &quot;v&quot; &quot;r&quot; &quot;g&quot; &quot;i&quot; &quot;t&quot;</code></pre>
<p>La soumission de cette commande a eu pour effet de modifier le germe.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="kw">str</span>(.Random.seed)</a></code></pre></div>
<pre><code>##  int [1:626] 10403 6 47777699 -819670847 -326033232 523235278 1163109177 1104276299 1..</code></pre>
<p>Donc si nous resoumettons la commande <code>sample</code>, nous n’obtiendrons sûrement pas le même résultat.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1"><span class="kw">sample</span>(<span class="dt">x =</span> letters, <span class="dt">size =</span> <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1] &quot;l&quot; &quot;q&quot; &quot;f&quot; &quot;e&quot; &quot;k&quot;</code></pre>
<p>Par contre, si nous fixons de nouveau le germe à partir de l’entier 753 avec <code>set.seed</code>, nous arrivons à obtenir de nouveau l’avant-dernier échantillon généré.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1"><span class="kw">set.seed</span>(<span class="dv">753</span>)</a>
<a class="sourceLine" id="cb57-2" title="2"><span class="kw">sample</span>(<span class="dt">x =</span> letters, <span class="dt">size =</span> <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1] &quot;v&quot; &quot;r&quot; &quot;g&quot; &quot;i&quot; &quot;t&quot;</code></pre>
<p>À n’importe quel moment, dans n’importe qu’elle session R, nous obtienons l’échantillon {v, r, g, i, t} si nous soumettons la commande <code>set.seed(753)</code> avant la commande <code>sample(letters, size = 5)</code>.</p>
<p>L’utilité de fixer le germe d’une génération pseudo-aléatoire est de rendre son résultat reproduisible.</p>
<p> </p>
</div>
</div>
<div id="calcul-de-statistiques-descriptives" class="section level2">
<h2>Calcul de statistiques descriptives</h2>
<p>Les fonctions pour des calculs de statistiques descriptives de base ont été vues dans les notes intitulées <a href="https://stt4230.rbind.io/calculs/calculs_base_r/#fonctions-pour-le-calcul-de-statistiques-descriptives">Calculs de base en R</a>.</p>
<p> </p>
</div>
<div id="tests-statistiques" class="section level2">
<h2>Tests statistiques</h2>
<p>Il existe des fonctions R pour faire des tests statistiques de base. En voici quelques-unes :</p>
<ul>
<li>tests sur une ou des moyennes : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/t.test.html"><code>t.test</code></a>;</li>
<li>tests sur une ou des proportions : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/prop.test.html"><code>prop.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/binom.test.html"><code>binom.test</code></a>;</li>
<li>tests de comparaison de variances : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/var.test.html"><code>var.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/bartlett.test.html"><code>bartlett.test</code></a>;</li>
<li>tests sur une corrélation : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/cor.test.html"><code>cor.test</code></a>;</li>
<li>tests pour une distribution : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/shapiro.test.html"><code>shapiro.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/ks.test.html"><code>ks.test</code></a>;</li>
<li>tests non paramétriques : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/wilcox.test.html"><code>wilcox.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/kruskal.test.html"><code>kruskal.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/friedman.test.html"><code>friedman.test</code></a>;</li>
<li>tests sur des fréquences : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/table.html">méthode <code>summary</code> pour un objet de classe <code>table</code></a> (produit par la fonction <code>table</code> ou <code>xtabs</code>), <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/chisq.test.html"><code>chisq.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/fisher.test.html"><code>fisher.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/mantelhaen.test.html"><code>mantelhaen.test</code></a>.</li>
</ul>
<p>Utilisons encore une fois les données <code>iris</code> pour construire un exemple de test de comparaison de moyennes. Nous allons comparer les largeurs moyennes des sépales des espèces versicolor et virginica.</p>
<div id="test-t-bilatéral-de-comparaison-de-moyennes-avec-variances-inégales" class="section level5">
<h5>Test t bilatéral de comparaison de moyennes, avec variances inégales :</h5>

<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="kw">t.test</span>(</a>
<a class="sourceLine" id="cb59-2" title="2">  <span class="dt">formula =</span> Sepal.Width <span class="op">~</span><span class="st"> </span>Species,</a>
<a class="sourceLine" id="cb59-3" title="3">  <span class="dt">data =</span> iris,</a>
<a class="sourceLine" id="cb59-4" title="4">  <span class="dt">subset =</span> Species <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;versicolor&quot;</span>, <span class="st">&quot;virginica&quot;</span>)</a>
<a class="sourceLine" id="cb59-5" title="5">)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Sepal.Width by Species
## t = -3.2058, df = 97.927, p-value = 0.001819
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.33028364 -0.07771636
## sample estimates:
## mean in group versicolor  mean in group virginica 
##                    2.770                    2.974</code></pre>
<p>Lorsque nous connaissons la valeur d’une statistique de test ainsi que sa loi sous l’hypothèse nulle, il est possible de calculer en R le seuil observé du test avec la bonne fonction <code>pxxx</code>. Par exemple, dans le test t ci-dessus, nous pouvons retrouver la valeur du seuil observé ainsi :</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1"><span class="co"># multiplication par 2, car le test est bilatéral et la loi t est symétrique</span></a>
<a class="sourceLine" id="cb61-2" title="2"><span class="kw">pt</span>(<span class="dt">q =</span> <span class="fl">-3.2058</span>, <span class="dt">df =</span> <span class="fl">97.927</span>)<span class="op">*</span><span class="dv">2</span> </a></code></pre></div>
<pre><code>## [1] 0.001819258</code></pre>
</div>
<div id="test-non-paramétrique-équivalent" class="section level5">
<h5>Test non paramétrique équivalent :</h5>

<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1"><span class="kw">wilcox.test</span>(</a>
<a class="sourceLine" id="cb63-2" title="2">  <span class="dt">formula =</span> Sepal.Width <span class="op">~</span><span class="st"> </span>Species,</a>
<a class="sourceLine" id="cb63-3" title="3">  <span class="dt">data =</span> iris, </a>
<a class="sourceLine" id="cb63-4" title="4">  <span class="dt">subset =</span> Species <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;versicolor&quot;</span>, <span class="st">&quot;virginica&quot;</span>), </a>
<a class="sourceLine" id="cb63-5" title="5">  <span class="dt">exact =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb63-6" title="6">)</a></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  Sepal.Width by Species
## W = 841, p-value = 0.004572
## alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div id="ajustement-de-modèles" class="section level2">
<h2>Ajustement de modèles</h2>
<p>Il existe plusieurs fonctions en R pour ajuster des modèles. Les modèles les plus usuels sont :</p>
<ul>
<li>modèles linéaires, dont la régression : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/lm.html"><code>lm</code></a> pour <em>linear model</em>;</li>
<li>modèle d’analyse de la variance : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/lm.html"><code>lm</code></a> ou <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/aov.html"><code>aov</code></a>;</li>
<li>modèles linéaires généralisés : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/glm.html"><code>glm</code></a>;</li>
<li>modèles linéaires mixtes (peuvent contenir des effets aléatoires) : <code>lmer</code> du package <a href="https://CRAN.R-project.org/package=lme4"><code>lme4</code></a> ou <code>lme</code> du package <a href="https://CRAN.R-project.org/package=nlme"><code>nlme</code></a>;</li>
<li>modèles non linéaires : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/nls.html"><code>nls</code></a>.</li>
</ul>
<p>Par exemple, ajustons quelques modèles sur les données des iris de Fisher.</p>
<div id="régression-linéaire-simple-entre-la-largeur-et-la-longueur-des-sépales" class="section level5">
<h5>Régression linéaire simple entre la largeur et la longueur des sépales :</h5>

<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb65-2" title="2">reg</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sepal.Width ~ Sepal.Length, data = iris)
## 
## Coefficients:
##  (Intercept)  Sepal.Length  
##      3.41895      -0.06188</code></pre>
</div>
<div id="anova-pour-comparer-les-largeurs-de-sépales-moyennes-entre-toutes-les-espèces" class="section level5">
<h5>ANOVA pour comparer les largeurs de sépales moyennes entre toutes les espèces :</h5>

<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" title="1">ANOVA &lt;-<span class="st"> </span><span class="kw">aov</span>(<span class="dt">formula =</span> Sepal.Width <span class="op">~</span><span class="st"> </span>Species, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb67-2" title="2">ANOVA</a></code></pre></div>
<pre><code>## Call:
##    aov(formula = Sepal.Width ~ Species, data = iris)
## 
## Terms:
##                  Species Residuals
## Sum of Squares  11.34493  16.96200
## Deg. of Freedom        2       147
## 
## Residual standard error: 0.3396877
## Estimated effects may be unbalanced</code></pre>
</div>
<div id="formules" class="section level3">
<h3>Formules</h3>
<p>Ces fonctions d’ajustement de modèles prennent obligatoirement en entrée une formule R, tout comme la fonction <code>xtabs</code>. D’autres fonctions acceptent aussi en entrée une formule, sans que ce type d’argument soit obligatoire. C’est le cas des fonctions <code>aggregate</code>, <code>ftable</code>, plusieurs des fonctions effectuant un test (p. ex. <code>t.test</code>, <code>wilcox.test</code>) et certaines fonctions graphiques (p. ex. <code>plot</code>, <code>boxplot</code>).</p>
<p>Les fonctions prenant une formule en entrée ont toujours un argument <code>data</code> pour spécifier d’où tirer les variables incluses dans la formule.</p>
<p>Une formule s’écrit sous la forme <code>y ~ x1 + x2</code> où <code>y</code> représente la variable réponse (ou à expliquer, ou dépendante, ou endogène) et <code>x1</code> et <code>x2</code> des variables explicatives (ou indépendantes, ou exogènes). Dans la partie de droite, les opérateurs suivants peuvent apparaître :</p>
<ul>
<li>« <code>+</code> » : pour ajouter des termes;</li>
<li>« <code>-</code> » : pour soustraire des termes;</li>
<li>« <code>0</code> » : ou <code>1</code> pour représenter l’ordonnée à l’origine (par défaut tout modèle linéaire comporte une ordonnée à l’origine, pour la retirer il faut ajouter <code>- 1</code> ou <code>+ 0</code> à la partie de droite de la formule);</li>
<li>« <code>.</code> » : pour représenter toutes les variables dans le jeu de données fournit en argument <code>data</code>, autres que la variable mise à la gauche du <code>~</code> (note : le point signifie autre chose dans la fonction <code>update</code>).</li>
</ul>
<p>Opérateurs propres aux facteurs :</p>
<ul>
<li>« <code>:</code> » : pour les termes d’interaction entre facteurs;</li>
<li>« <code>*</code> » : pour le croisement de facteurs (<code>x1*x2</code> est équivalent à <code>x1 + x2 + x1:x2</code>);</li>
<li>« <code>^</code> » : pour le croisement de facteurs jusqu’à un certain niveau d’interaction (par exemple <code>(x1 + x2 + x3)^2</code> va inclure tous les termes de croisement des facteurs jusqu’aux interactions doubles <code>x1 + x2 + x3 + x1:x2 + x1:x3 + x2:x3</code>, mais pas l’interaction triple <code>x1:x2:x3</code>);</li>
<li>« <code>%in%</code> » : pour les facteurs emboîtés (dans <code>x2 %in% x1</code>, <code>x2</code> est emboîté dans <code>x1</code>).</li>
</ul>
<p>Autre opérateur :</p>
<ul>
<li>« <code>|</code> » : (p. ex. <code>y ~ x1 | x2</code>) n’a pas toujours exactement la même signification selon la fonction, il représente parfois :
<ul>
<li>un conditionnement par rapport à une variable (p. ex. fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/graphics/html/coplot.html"><code>coplot</code></a>),</li>
<li>la structure d’effets aléatoires (p. ex. fonctions <code>lmer</code> du package <a href="https://CRAN.R-project.org/package=lme4"><code>lme4</code></a> ou <code>lme</code> du package <a href="https://CRAN.R-project.org/package=nlme"><code>nlme</code></a>).</li>
</ul></li>
</ul>
<p>Les formules peuvent inclurent des appels à des fonctions pour transformer les variables. Par exemple, pour ajuster un modèle sur la racine carrée de la variable réponse, nous pouvons écrire <code>sqrt(y) ~ x1 + x2</code>. Certaines transformations pourraient faire intervenir un ou des opérateurs ayant une signification modifiée dans une formule. Par exemple, imaginons que nous voulons ajuster un modèle avec une seule variable explicative créée en additionnant les valeurs des variables <code>x1</code> et <code>x2</code>. La formule <code>y ~ x1 + x2</code> n’ajuste pas ce modèle puisque, dans une formule, l’opérateur <code>+</code> signifie « ajouter des termes » et non plus « additionner des valeurs ». Alors est-il possible d’ajuster le modèle souhaité (<em>sans ajouter une nouvelle variable dans les données</em>)?</p>
<p>Oui, c’est possible grâce à la fonction <code>I</code>. Il faut encadrer l’opération arithmétique à effectuer dans la formule d’un appel à la fonction <code>I</code>. Par exemple, <code>y ~ I(x1 + x2)</code> ajuste un modèle à une seule variable explicative formée de la somme des valeurs de <code>x1</code> et <code>x2</code>. Ainsi, <code>I()</code> permet d’utiliser la signification usuelle des opérateurs et non celle spécifique aux formules.</p>
<p> </p>
<p>Voici quelques exemples, dans lesquels nous omettrons de nommer le premier argument, soit <code>formula</code>, pour alléger la présentation et parce qu’il est usuel de ne pas nommer ce premier argument.</p>
<div id="retrait-de-lordonnée-à-lorigine" class="section level5">
<h5>Retrait de l’ordonnée à l’origine :</h5>

<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb69-2" title="2"><span class="co"># ou encore :</span></a>
<a class="sourceLine" id="cb69-3" title="3">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length <span class="op">+</span><span class="st"> </span><span class="dv">0</span>, <span class="dt">data =</span> iris)</a></code></pre></div>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1"><span class="kw">coef</span>(<span class="kw">summary</span>(reg))</a></code></pre></div>
<pre><code>##               Estimate  Std. Error  t value      Pr(&gt;|t|)
## Sepal.Length 0.5117739 0.008939966 57.24562 2.422615e-103</code></pre>
</div>
<div id="régression-log-log" class="section level5">
<h5>Régression log-log :</h5>

<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">log</span>(Sepal.Width) <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(Sepal.Length), <span class="dt">data =</span> iris)</a></code></pre></div>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1"><span class="kw">coef</span>(<span class="kw">summary</span>(reg))</a></code></pre></div>
<pre><code>##                     Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)        1.3057236 0.14573780  8.959402 1.293792e-15
## log(Sepal.Length) -0.1129573 0.08275742 -1.364920 1.743495e-01</code></pre>
</div>
<div id="régression-polynomiale" class="section level5">
<h5>Régression polynomiale :</h5>

<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length <span class="op">+</span><span class="st"> </span>Sepal.Length<span class="op">^</span><span class="dv">2</span>, <span class="dt">data =</span> iris)</a></code></pre></div>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="kw">coef</span>(<span class="kw">summary</span>(reg))</a></code></pre></div>
<pre><code>##                Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)   3.4189468 0.25356227 13.483658 1.552431e-27
## Sepal.Length -0.0618848 0.04296699 -1.440287 1.518983e-01</code></pre>
<p>Non, ça n’a pas fonctionné. Dans une formule, l’opérateur <code>^</code> ne signifie pas exposant. Pour demander à R d’utiliser la signification usuelle de l’opérateur, et non celle spécifique aux formules, il faut encadrer le terme contenant l’opérateur de <code>I()</code> comme suit :</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(Sepal.Length<span class="op">^</span><span class="dv">2</span>), <span class="dt">data =</span> iris)</a></code></pre></div>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1"><span class="kw">coef</span>(<span class="kw">summary</span>(reg))</a></code></pre></div>
<pre><code>##                      Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)        6.41583572 1.58499197  4.047866 8.327686e-05
## Sepal.Length      -1.08556027 0.53624556 -2.024372 4.474291e-02
## I(Sepal.Length^2)  0.08570656 0.04475502  1.915016 5.743267e-02</code></pre>
<p> </p>
<p><em>Création de variables catégoriques pour les exemples à venir :</em></p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1">iris<span class="op">$</span>Sepal.Length_catego &lt;-<span class="st"> </span><span class="kw">cut</span>(</a>
<a class="sourceLine" id="cb81-2" title="2">  <span class="dt">x =</span> iris<span class="op">$</span>Sepal.Length, </a>
<a class="sourceLine" id="cb81-3" title="3">  <span class="dt">breaks =</span> <span class="kw">c</span>(<span class="op">-</span><span class="ot">Inf</span>, <span class="kw">quantile</span>(iris<span class="op">$</span>Sepal.Length, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>, <span class="dv">2</span><span class="op">/</span><span class="dv">3</span>)), <span class="ot">Inf</span>),</a>
<a class="sourceLine" id="cb81-4" title="4">  <span class="dt">right =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb81-5" title="5">)</a>
<a class="sourceLine" id="cb81-6" title="6">iris<span class="op">$</span>Petal.Width_catego &lt;-<span class="st"> </span><span class="kw">cut</span>(</a>
<a class="sourceLine" id="cb81-7" title="7">  <span class="dt">x =</span> iris<span class="op">$</span>Petal.Width, </a>
<a class="sourceLine" id="cb81-8" title="8">  <span class="dt">breaks =</span> <span class="kw">c</span>(<span class="op">-</span><span class="ot">Inf</span>, <span class="kw">quantile</span>(iris<span class="op">$</span>Petal.Width, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>, <span class="dv">2</span><span class="op">/</span><span class="dv">3</span>)), <span class="ot">Inf</span>), </a>
<a class="sourceLine" id="cb81-9" title="9">  <span class="dt">right =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb81-10" title="10">  )</a></code></pre></div>
</div>
<div id="anova-à-3-facteurs-modèle-complet" class="section level5">
<h5>Anova à 3 facteurs, modèle complet :</h5>

<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1">ANOVA &lt;-<span class="st"> </span><span class="kw">aov</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Species<span class="op">*</span>Sepal.Length_catego<span class="op">*</span>Petal.Width_catego, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb82-2" title="2"><span class="co"># ou encore</span></a>
<a class="sourceLine" id="cb82-3" title="3">ANOVA &lt;-<span class="st"> </span><span class="kw">aov</span>(</a>
<a class="sourceLine" id="cb82-4" title="4">  Sepal.Width <span class="op">~</span><span class="st"> </span>(Species <span class="op">+</span><span class="st"> </span>Sepal.Length_catego <span class="op">+</span><span class="st"> </span>Petal.Width_catego)<span class="op">^</span><span class="dv">3</span>,</a>
<a class="sourceLine" id="cb82-5" title="5">  <span class="dt">data =</span> iris</a>
<a class="sourceLine" id="cb82-6" title="6">)</a></code></pre></div>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1"><span class="kw">summary</span>(ANOVA)</a></code></pre></div>
<pre><code>##                                                 Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Species                                          2 11.345   5.672  64.620  &lt; 2e-16 ***
## Sepal.Length_catego                              2  3.843   1.922  21.891 5.53e-09 ***
## Petal.Width_catego                               1  0.872   0.872   9.934  0.00199 ** 
## Species:Sepal.Length_catego                      3  0.077   0.026   0.291  0.83194    
## Species:Petal.Width_catego                       1  0.006   0.006   0.073  0.78754    
## Sepal.Length_catego:Petal.Width_catego           1  0.047   0.047   0.540  0.46357    
## Species:Sepal.Length_catego:Petal.Width_catego   1  0.002   0.002   0.026  0.87212    
## Residuals                                      138 12.114   0.088                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="anova-à-3-facteurs-modèle-complet-sans-linteraction-triple" class="section level5">
<h5>Anova à 3 facteurs, modèle complet sans l’interaction triple :</h5>

<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1">ANOVA &lt;-<span class="st"> </span><span class="kw">aov</span>(</a>
<a class="sourceLine" id="cb85-2" title="2">  Sepal.Width <span class="op">~</span><span class="st"> </span>Species<span class="op">*</span>Sepal.Length_catego<span class="op">*</span>Petal.Width_catego <span class="op">-</span><span class="st"> </span></a>
<a class="sourceLine" id="cb85-3" title="3"><span class="st">                </span>Species<span class="op">:</span>Sepal.Length_catego<span class="op">:</span>Petal.Width_catego, </a>
<a class="sourceLine" id="cb85-4" title="4">  <span class="dt">data =</span> iris</a>
<a class="sourceLine" id="cb85-5" title="5">)</a>
<a class="sourceLine" id="cb85-6" title="6"><span class="co"># ou encore</span></a>
<a class="sourceLine" id="cb85-7" title="7">ANOVA &lt;-<span class="st"> </span><span class="kw">aov</span>(</a>
<a class="sourceLine" id="cb85-8" title="8">  Sepal.Width <span class="op">~</span><span class="st"> </span>(Species <span class="op">+</span><span class="st"> </span>Sepal.Length_catego <span class="op">+</span><span class="st"> </span>Petal.Width_catego)<span class="op">^</span><span class="dv">2</span>, </a>
<a class="sourceLine" id="cb85-9" title="9">  <span class="dt">data =</span> iris</a>
<a class="sourceLine" id="cb85-10" title="10">)</a></code></pre></div>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1"><span class="kw">summary</span>(ANOVA)</a></code></pre></div>
<pre><code>##                                         Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Species                                  2 11.345   5.672  65.076  &lt; 2e-16 ***
## Sepal.Length_catego                      2  3.843   1.922  22.046 4.83e-09 ***
## Petal.Width_catego                       1  0.872   0.872  10.004  0.00192 ** 
## Species:Sepal.Length_catego              3  0.077   0.026   0.293  0.83046    
## Species:Petal.Width_catego               1  0.006   0.006   0.073  0.78681    
## Sepal.Length_catego:Petal.Width_catego   1  0.047   0.047   0.544  0.46199    
## Residuals                              139 12.116   0.087                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="arguments-accompagnant-les-formules" class="section level3">
<h3>Arguments accompagnant les formules</h3>
<p>Pour les fonctions prenant une formule comme premier argument, cet argument est souvent le seul argument obligatoire.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(iris<span class="op">$</span>Sepal.Width <span class="op">~</span><span class="st"> </span>iris<span class="op">$</span>Sepal.Length)</a>
<a class="sourceLine" id="cb88-2" title="2"><span class="kw">coef</span>(<span class="kw">summary</span>(reg))</a></code></pre></div>
<pre><code>##                     Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)        3.4189468 0.25356227 13.483658 1.552431e-27
## iris$Sepal.Length -0.0618848 0.04296699 -1.440287 1.518983e-01</code></pre>
<p>Cependant, un argument <code>formula</code> est toujours accompagné d’un argument <code>data</code>. Typiquement, l’utilisateur fournit à <code>data</code> un data frame contenant en colonnes les variables à inclure dans la formule. Utiliser l’argument <code>data</code> permet d’alléger la formule. Les noms de variables dans la formule sont d’abord recherchés parmi les noms des éléments de <code>data</code>.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length, <span class="dt">data =</span> iris)  <span class="co"># (plus besoin des iris$ dans la formule)</span></a>
<a class="sourceLine" id="cb90-2" title="2"><span class="kw">coef</span>(<span class="kw">summary</span>(reg))</a></code></pre></div>
<pre><code>##                Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)   3.4189468 0.25356227 13.483658 1.552431e-27
## Sepal.Length -0.0618848 0.04296699 -1.440287 1.518983e-01</code></pre>
<p> </p>
<p>En plus de l’argument <code>data</code>, les fonctions prenant une formule en entrée ont la plupart du temps les arguments :</p>
<ul>
<li><code>subset</code> pour spécifier un sous-ensemble de données à utiliser (par défaut toutes les observations de <code>data</code> sont utilisées) et</li>
<li><code>na.action</code> pour spécifier quoi faire avec les valeurs manquantes (voir <a href="http://stat.ethz.ch/R-manual/R-patched/library/stats/html/na.fail.html"><code>help(na.fail)</code></a>).</li>
</ul>
<div id="ajustement-dun-modèle-sur-un-sous-ensemble-des-données" class="section level5">
<h5>Ajustement d’un modèle sur un sous-ensemble des données :</h5>

<p>Un argument <code>subset</code> se spécifie comme l’argument <code>subset</code> de la fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/subset.html"><code>subset</code></a>. Sa valeur doit être un vecteur logique dont la longueur est égale au nombre d’observations dans le jeu de données fourni à l’argument <code>data</code>. Voici un exemple.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length, <span class="dt">data =</span> iris, <span class="dt">subset =</span> Species <span class="op">==</span><span class="st"> &quot;setosa&quot;</span>)</a>
<a class="sourceLine" id="cb92-2" title="2"><span class="kw">coef</span>(<span class="kw">summary</span>(reg))</a></code></pre></div>
<pre><code>##                Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)  -0.5694327  0.5217119 -1.091470 2.805148e-01
## Sepal.Length  0.7985283  0.1039651  7.680738 6.709843e-10</code></pre>
</div>
<div id="modification-du-traitement-des-valeurs-manquantes" class="section level5">
<h5>Modification du traitement des valeurs manquantes :</h5>

<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1">iris2 &lt;-<span class="st"> </span>iris</a>
<a class="sourceLine" id="cb94-2" title="2">iris2<span class="op">$</span>Sepal.Length[<span class="dv">6</span>] &lt;-<span class="st"> </span><span class="ot">NA</span> <span class="co"># pour insérer une donnée manquante (pas de NA dans iris)</span></a></code></pre></div>
<p>La valeur fournie à l’argument <code>na.action</code> est le nom d’une fonction qui traite les données manquantes dans un jeu de données. Le comportement par défaut de l’argument <code>na.action</code> est régi par l’<a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/options.html">option de session</a> du même nom.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" title="1"><span class="kw">getOption</span>(<span class="st">&quot;na.action&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;na.omit&quot;</code></pre>
<p>Dans mon cas, <code>na.action</code> prend donc par défaut la valeur <code>na.omit</code>, ce qui a pour conséquence que les observations avec au moins une valeur de variable manquante sont omises (ligne complète non considérée).</p>
<p>Nous pourrions fournir à l’argument une autre des fonctions listées dans la fiche d’aide <a href="http://stat.ethz.ch/R-manual/R-patched/library/stats/html/na.fail.html"><code>help(na.fail)</code></a>. Par exemple, l’ajustement du modèle n’est pas effectué lorsque les données comportent des données manquantes si la valeur <code>na.fail</code> est fournie à <code>na.action</code>.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb97-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length, <span class="dt">data =</span> iris2, <span class="dt">na.action =</span> na.fail)</a></code></pre></div>
<pre><code>## Error in na.fail.default(list(Sepal.Width = c(3.5, 3, 3.2, 3.1, 3.6, 3.9,  : 
##   missing values in object</code></pre>
</div>
</div>
<div id="manipulation-de-la-sortie-dune-fonction-dajustement-de-modèle" class="section level3">
<h3>Manipulation de la sortie d’une fonction d’ajustement de modèle</h3>
<p>Lorsque nous affichons dans la console un objet produit en sortie d’une fonction d’ajustement de modèle, la sortie obtenue est brève.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb99-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb99-2" title="2">reg</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sepal.Width ~ Sepal.Length, data = iris)
## 
## Coefficients:
##  (Intercept)  Sepal.Length  
##      3.41895      -0.06188</code></pre>
<p>En réalité, cet objet est une liste contenant plusieurs éléments.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" title="1"><span class="kw">str</span>(reg, <span class="dt">list.len =</span> <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## List of 12
##  $ coefficients : Named num [1:2] 3.4189 -0.0619
##   ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;(Intercept)&quot; &quot;Sepal.Length&quot;
##  $ residuals    : Named num [1:150] 0.3967 -0.1157 0.0719 -0.0343 0.4905 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:150] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##  $ effects      : Named num [1:150] -37.4445 -0.6255 0.0564 -0.0485 0.471 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:150] &quot;(Intercept)&quot; &quot;Sepal.Length&quot; &quot;&quot; &quot;&quot; ...
##  $ rank         : int 2
##  $ fitted.values: Named num [1:150] 3.1 3.12 3.13 3.13 3.11 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:150] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##   [list output truncated]
##  - attr(*, &quot;class&quot;)= chr &quot;lm&quot;</code></pre>
<p>L’objet obtenu de la fonction d’ajustement de modèle ne s’affiche pas comme une liste parce qu’un attribut classe lui est attribué et que la fonction polymorphe <code>print</code> possède une définition spécifique aux objets de cette classe.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb103-1" title="1"><span class="kw">class</span>(reg)</a></code></pre></div>
<pre><code>## [1] &quot;lm&quot;</code></pre>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" title="1"><span class="kw">print</span>(reg)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sepal.Width ~ Sepal.Length, data = iris)
## 
## Coefficients:
##  (Intercept)  Sepal.Length  
##      3.41895      -0.06188</code></pre>
<p>C’est une caractéristique orientée objet du langage R. Dans la terminologie de R, une fonction polymorphe est appelée <em>fonction générique</em> et les différentes définitions de cette fonction sont appelées <em>méthodes</em>. Les fonctions génériques, telles que les fonctions <code>print</code> et <code>plot</code>, ont un comportement qui varie en fonction de la classe du premier argument qui leur est fourni en entrée.</p>
<p>Rappelons que taper le nom d’un objet dans la console est en fait un raccourci pour soumettre la fonction <code>print</code> avec l’objet à afficher en argument.</p>
<p>Si nous retirons l’attribut classe de l’objet, nous retombons sur un affichage usuel pour un objet de type liste.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" title="1"><span class="kw">class</span>(reg) &lt;-<span class="st"> </span><span class="ot">NULL</span></a>
<a class="sourceLine" id="cb107-2" title="2">reg <span class="co"># résultat non affiché, car trop long</span></a></code></pre></div>
<p>L’attribut classe peut même contenir plus d’une classe.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" title="1">ANOVA &lt;-<span class="st"> </span><span class="kw">aov</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Species, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb108-2" title="2"><span class="kw">class</span>(ANOVA)</a></code></pre></div>
<pre><code>## [1] &quot;aov&quot; &quot;lm&quot;</code></pre>
<p>Souvent, le nom de la classe d’un objet est le nom de la fonction qui a produit cet objet. Les objets retournés par la fonction <code>aov</code> ont deux classes, car en réalité la fonction <code>aov</code> appelle la fonction <code>lm</code>.</p>
<div id="fonctions-génériques-dextraction-dinformation-de-la-sortie-dune-fonction-dajustement-de-modèle" class="section level4">
<h4>Fonctions génériques d’extraction d’information de la sortie d’une fonction d’ajustement de modèle</h4>

<p>Voici la liste des fonctions génériques les plus couramment utilisées pour tirer de l’information d’un objet produit par une fonction d’ajustement de modèle :</p>
<ul>
<li><code>summary</code> : pour afficher un résumé des informations plus long que ce qui est affiché avec <code>print</code> et pour produire des résultats supplémentaires;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/coef.html"><code>coef</code></a> (ou son alias <code>coefficients</code>) et <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/confint.html"><code>confint</code></a> : pour afficher les coefficients et pour produire des intervalles de confiance pour les coefficients d’un modèle;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/residuals.html"><code>residuals</code></a> et <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/fitted.values.html"><code>fitted</code></a> : pour extraire les résidus et les valeurs prédites;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/predict.html"><code>predict</code></a> : pour effectuer des prédictions pour de nouvelles observations;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/anova.html"><code>anova</code></a> : pour calculer la table d’analyse de la variance (ANOVA) du modèle;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/model.tables.html"><code>model.tables</code></a> et <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/TukeyHSD.html"><code>TukeyHSD</code></a> (pour la classe <code>aov</code>) : pour calculer les moyennes par niveaux de facteurs et pour faire des comparaisons multiples de Tukey sur ces moyennes;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/deviance.html"><code>deviance</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/logLik.html"><code>logLik</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/AIC.html"><code>AIC</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/AIC.html"><code>BIC</code></a> : pour extraire la déviance, la log-vraisemblance maximisée, le AIC et le BIC.</li>
</ul>
<p>L’utilisation de ces fonctions est la façon usuelle en R d’extraire des résultats relatifs à un modèle. Par exemple, pour extraire les coefficients d’un modèle, nous pouvons utiliser :</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb110-2" title="2"><span class="kw">coef</span>(reg)</a></code></pre></div>
<pre><code>##  (Intercept) Sepal.Length 
##    3.4189468   -0.0618848</code></pre>
<p>Notons cependant qu’il est aussi possible d’extraire cette information en accédant directement aux éléments de <code>reg</code>, qui est une liste.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb112-1" title="1">reg<span class="op">$</span>coefficients</a></code></pre></div>
<pre><code>##  (Intercept) Sepal.Length 
##    3.4189468   -0.0618848</code></pre>
<p> </p>
<p>Voici quelques exemples d’utilisation des fonctions d’extraction d’information :</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb114-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length <span class="op">+</span><span class="st"> </span>Petal.Width, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb114-2" title="2"><span class="kw">summary</span>(reg)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sepal.Width ~ Sepal.Length + Petal.Width, data = iris)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.99563 -0.24690 -0.00503  0.23354  1.01131 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   1.92632    0.32094   6.002 1.45e-08 ***
## Sepal.Length  0.28929    0.06605   4.380 2.24e-05 ***
## Petal.Width  -0.46641    0.07175  -6.501 1.17e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3841 on 147 degrees of freedom
## Multiple R-squared:  0.234,  Adjusted R-squared:  0.2236 
## F-statistic: 22.46 on 2 and 147 DF,  p-value: 3.091e-09</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb116-1" title="1"><span class="kw">confint</span>(reg)</a></code></pre></div>
<pre><code>##                   2.5 %     97.5 %
## (Intercept)   1.2920761  2.5605655
## Sepal.Length  0.1587655  0.4198079
## Petal.Width  -0.6082076 -0.3246210</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" title="1"><span class="kw">str</span>(<span class="kw">residuals</span>(reg))</a></code></pre></div>
<pre><code>##  Named num [1:150] 0.1916 -0.25054 0.00731 -0.06376 0.32053 ...
##  - attr(*, &quot;names&quot;)= chr [1:150] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" title="1"><span class="kw">predict</span>(</a>
<a class="sourceLine" id="cb120-2" title="2">  reg, </a>
<a class="sourceLine" id="cb120-3" title="3">  <span class="dt">newdata =</span> <span class="kw">data.frame</span>(</a>
<a class="sourceLine" id="cb120-4" title="4">    <span class="dt">Sepal.Length =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">6</span>),</a>
<a class="sourceLine" id="cb120-5" title="5">    <span class="dt">Petal.Width =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb120-6" title="6">  )</a>
<a class="sourceLine" id="cb120-7" title="7">)</a></code></pre></div>
<pre><code>##        1        2 
## 2.906340 2.729213</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" title="1">ANOVA &lt;-<span class="st"> </span><span class="kw">aov</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Species <span class="op">+</span><span class="st"> </span>Sepal.Length_catego, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb122-2" title="2"><span class="kw">summary</span>(ANOVA)</a></code></pre></div>
<pre><code>##                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Species               2 11.345   5.672   62.70  &lt; 2e-16 ***
## Sepal.Length_catego   2  3.843   1.922   21.24 8.13e-09 ***
## Residuals           145 13.119   0.090                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" title="1"><span class="kw">anova</span>(ANOVA)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Sepal.Width
##                      Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## Species               2 11.3449  5.6725  62.697 &lt; 2.2e-16 ***
## Sepal.Length_catego   2  3.8433  1.9216  21.240 8.129e-09 ***
## Residuals           145 13.1187  0.0905                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" title="1"><span class="kw">model.tables</span>(ANOVA, <span class="dt">type =</span> <span class="st">&quot;means&quot;</span>)</a></code></pre></div>
<pre><code>## Tables of means
## Grand mean
##          
## 3.057333 
## 
##  Species 
##     setosa versicolor virginica
##      3.428       2.77     2.974
## rep 50.000      50.00    50.000
## 
##  Sepal.Length_catego 
##     [-Inf,5.4) [5.4,6.3) [6.3, Inf)
##          2.919     3.081      3.157
## rep     46.000    53.000     51.000</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" title="1"><span class="kw">TukeyHSD</span>(ANOVA)</a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Sepal.Width ~ Species + Sepal.Length_catego, data = iris)
## 
## $Species
##                        diff         lwr        upr     p adj
## versicolor-setosa    -0.658 -0.80045516 -0.5155448 0.0000000
## virginica-setosa     -0.454 -0.59645516 -0.3115448 0.0000000
## virginica-versicolor  0.204  0.06154484  0.3464552 0.0025694
## 
## $Sepal.Length_catego
##                             diff         lwr       upr     p adj
## [5.4,6.3)-[-Inf,5.4)  0.16172436  0.01819230 0.3052564 0.0229762
## [6.3, Inf)-[-Inf,5.4) 0.23756010  0.09272626 0.3823939 0.0004549
## [6.3, Inf)-[5.4,6.3)  0.07583574 -0.06387887 0.2155503 0.4057167</code></pre>
</div>
</div>
<div id="résultats-additionnels-fournis-par-summary" class="section level3">
<h3>Résultats additionnels fournis par <code>summary</code></h3>
<p>La fonction générique <code>summary</code> ne fait pas que produire un affichage du modèle ajusté plus complet que la fonction générique <code>print</code>. Elle produit des résultats supplémentaires concernant le modèle. Par exemple, pour un modèle produit avec <code>lm</code>, comparons ce que produit directement la fonction <code>lm</code> et ce que produit la fonction générique <code>summary</code> pour un objet retourné par <code>lm</code>.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb130-2" title="2">reg_summary &lt;-<span class="st"> </span><span class="kw">summary</span>(reg)</a>
<a class="sourceLine" id="cb130-3" title="3"><span class="kw">sort</span>(<span class="kw">names</span>(reg))</a></code></pre></div>
<pre><code>##  [1] &quot;assign&quot;        &quot;call&quot;          &quot;coefficients&quot;  &quot;df.residual&quot;  
##  [5] &quot;effects&quot;       &quot;fitted.values&quot; &quot;model&quot;         &quot;qr&quot;           
##  [9] &quot;rank&quot;          &quot;residuals&quot;     &quot;terms&quot;         &quot;xlevels&quot;</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1"><span class="kw">sort</span>(<span class="kw">names</span>(reg_summary))</a></code></pre></div>
<pre><code>##  [1] &quot;adj.r.squared&quot; &quot;aliased&quot;       &quot;call&quot;          &quot;coefficients&quot; 
##  [5] &quot;cov.unscaled&quot;  &quot;df&quot;            &quot;fstatistic&quot;    &quot;r.squared&quot;    
##  [9] &quot;residuals&quot;     &quot;sigma&quot;         &quot;terms&quot;</code></pre>
<p>Seulement 4 éléments de la liste <code>reg</code> portent des noms aussi présents dans la liste <code>reg_summary</code>. Et des éléments de même nom dans les deux listes ne contiennent pas toujours la même chose.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1">reg<span class="op">$</span>coefficients</a></code></pre></div>
<pre><code>##  (Intercept) Sepal.Length 
##    3.4189468   -0.0618848</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" title="1">reg_summary<span class="op">$</span>coefficients</a></code></pre></div>
<pre><code>##                Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)   3.4189468 0.25356227 13.483658 1.552431e-27
## Sepal.Length -0.0618848 0.04296699 -1.440287 1.518983e-01</code></pre>
<p>Les éléments produits par <code>summary</code> tendent à contenir plus de détails que les éléments obtenus directement de <code>lm</code>.</p>
<p>La fonction <code>summary</code> réalise donc des calculs supplémentaires relatifs au modèle. Par exemple, pour un modèle ajusté avec <code>lm</code>, elle réalise les tests sur les termes du modèle et calcule le coefficient de détermination (R<sup>2</sup>), soit une mesure souvent utilisée pour évaluer la qualité de la prédiction du modèle.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" title="1">reg_summary<span class="op">$</span>r.squared</a></code></pre></div>
<pre><code>## [1] 0.01382265</code></pre>
<p>Pour un modèle d’analyse de la variance ajusté avec <code>aov</code>, la fonction <code>summary</code> produit la table d’ANOVA complète, tout comme la fonction <code>anova</code> le fait.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1">ANOVA &lt;-<span class="st"> </span><span class="kw">aov</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Species <span class="op">+</span><span class="st"> </span>Sepal.Length_catego, <span class="dt">data =</span> iris)</a>
<a class="sourceLine" id="cb140-2" title="2">ANOVA_summary &lt;-<span class="st"> </span><span class="kw">summary</span>(ANOVA)</a>
<a class="sourceLine" id="cb140-3" title="3"><span class="kw">str</span>(ANOVA_summary)</a></code></pre></div>
<pre><code>## List of 1
##  $ :Classes &#39;anova&#39; and &#39;data.frame&#39;:    3 obs. of  5 variables:
##   ..$ Df     : num [1:3] 2 2 145
##   ..$ Sum Sq : num [1:3] 11.34 3.84 13.12
##   ..$ Mean Sq: num [1:3] 5.6725 1.9216 0.0905
##   ..$ F value: num [1:3] 62.7 21.2 NA
##   ..$ Pr(&gt;F) : num [1:3] 2.40e-20 8.13e-09 NA
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;summary.aov&quot; &quot;listof&quot;</code></pre>
<div style="page-break-after: always;"></div>
</div>
<div id="mise-en-forme-de-la-sortie-dune-fonction-dajustement-de-modèle-avec-le-package-broom" class="section level3">
<h3>Mise en forme de la sortie d’une fonction d’ajustement de modèle avec le package <code>broom</code></h3>
<p>Le <a href="https://CRAN.R-project.org/package=broom">package <code>broom</code></a> offre des fonctions pour faciliter la manipulation de sorties d’une fonction d’ajustement de modèle. Les trois principales fonctions de ce package sont les suivantes :</p>
<ul>
<li><code>tidy</code> : produit un résumé des principaux résultats statistiques d’un modèle, dans le cas d’un modèle linéaire il s’agit d’une table des tests sur les coefficients du modèle;</li>
<li><code>augment</code> : ajoute aux données sur lesquelles le modèle a été ajusté des informations tirées du modèle, comme des résidus et des valeurs prédites;</li>
<li><code>glance</code> : réunit dans un seul data frame à une ligne plusieurs statistiques globales au modèle, comme des statistiques d’ajustement du modèle.</li>
</ul>
<p>Voici quelques exemples :</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Sepal.Length, <span class="dt">data =</span> iris)</a></code></pre></div>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb143-1" title="1"><span class="kw">library</span>(broom)</a>
<a class="sourceLine" id="cb143-2" title="2"><span class="kw">tidy</span>(reg) <span class="co"># très similaire à coef(summary(reg)) pour une sortie de lm</span></a></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term         estimate std.error statistic  p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)    3.42      0.254      13.5  1.55e-27
## 2 Sepal.Length  -0.0619    0.0430     -1.44 1.52e- 1</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb145-1" title="1"><span class="kw">head</span>(<span class="kw">augment</span>(reg))</a></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   Sepal.Width Sepal.Length .fitted .se.fit  .resid    .hat .sigma   .cooksd .std.resid
##         &lt;dbl&gt;        &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1         3.5          5.1    3.10  0.0477  0.397  0.0121   0.435 0.00516       0.919 
## 2         3            4.9    3.12  0.0539 -0.116  0.0154   0.436 0.000563     -0.269 
## 3         3.2          4.7    3.13  0.0606  0.0719 0.0195   0.436 0.000277      0.167 
## 4         3.1          4.6    3.13  0.0641 -0.0343 0.0218   0.436 0.0000709    -0.0798
## 5         3.6          5      3.11  0.0507  0.490  0.0136   0.434 0.00893       1.14  
## 6         3.9          5.4    3.08  0.0403  0.815  0.00859  0.431 0.0154        1.89</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" title="1"><span class="kw">glance</span>(reg)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 11
##   r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC deviance df.residual
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt;
## 1    0.0138       0.00716 0.434      2.07   0.152     2  -86.7  179.  188.     27.9         148</code></pre>
<p>Plus d’informations peuvent être trouvées dans les vignettes du package :<br />
<a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html" class="uri">https://cran.r-project.org/web/packages/broom/vignettes/broom.html</a>.</p>
</div>
</div>
<div id="méthodes-statistiques-diverses" class="section level2">
<h2>Méthodes statistiques diverses</h2>
<p>Une très grande quantité de méthodes statistiques sont implantées en R. Je ne vais pas les énumérer ici, mais voici quelques bonnes références sur le sujet.</p>
<ul>
<li>Livre présentant comment utiliser les principales techniques statistiques en R : Hothorn, T. et Everitt, B.S. (2014). <em>A handbook of statistical analyses using R</em>, third edition. CRC Press.</li>
<li>Site web contenant plusieurs exemples d’analyses statistiques en R (ainsi qu’avec d’autres logiciels statistiques) :
<a href="https://stats.idre.ucla.edu/other/dae/" class="uri">https://stats.idre.ucla.edu/other/dae/</a></li>
<li>Ressources pour dénicher des packages R implémentant des méthodes statistiques particulières :
<ul>
<li>Task views de R : <a href="http://cran.r-project.org/web/views/" class="uri">http://cran.r-project.org/web/views/</a></li>
<li>Dépôt informatique de packages R en bio-informatique : <a href="http://www.bioconductor.org/" class="uri">http://www.bioconductor.org/</a></li>
</ul></li>
</ul>
<hr />
</div>
</div>
<div id="calculs-mathématiques" class="section level1">
<h1>Calculs mathématiques</h1>
<div id="opérateurs-et-fonctions-de-base" class="section level2">
<h2>Opérateurs et fonctions de base</h2>
<p>Les opérateurs et fonctions mathématiques de base ont été vus dans les notes intitulées <a href="https://stt4230.rbind.io/calculs/calculs_base_r/#fonctions-et-operateurs-pour-des-calculs-mathematiques">Calculs de base en R</a>.</p>
</div>
<div id="calcul-de-distances" class="section level2">
<h2>Calcul de distances</h2>
<div id="distance-entre-des-variables-numériques" class="section level4">
<h4>Distance entre des variables numériques</h4>

<p>Pour calculer des distances entre des observations numériques, la package <code>stats</code> offre la fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/dist.html"><code>dist</code></a>. Par exemple, reprenons l’échantillon aléatoire de 5 observations du jeu de données <code>iris</code> que nous avons tiré plus tôt et conservons uniquement les variables numériques.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb149-1" title="1">iris_ech_num &lt;-<span class="st"> </span>iris_ech[, <span class="kw">c</span>(<span class="st">&quot;Sepal.Length&quot;</span>, <span class="st">&quot;Sepal.Width&quot;</span>, <span class="st">&quot;Petal.Length&quot;</span>, <span class="st">&quot;Petal.Width&quot;</span>)]</a>
<a class="sourceLine" id="cb149-2" title="2">iris_ech_num</a></code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width
## 32           5.4         3.4          1.5         0.4
## 83           5.8         2.7          3.9         1.2
## 118          7.7         3.8          6.7         2.2
## 116          6.4         3.2          5.3         2.3
## 67           5.6         3.0          4.5         1.5</code></pre>
<p>Calculons les distances euclidiennes entre toutes les paires d’observations dans ce jeu de données, basées sur les 4 variables numériques.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" title="1"><span class="kw">dist</span>(<span class="dt">x =</span> iris_ech_num, <span class="dt">method =</span> <span class="st">&quot;euclidean&quot;</span>, <span class="dt">diag =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>##            32        83       118       116        67
## 32  0.0000000                                        
## 83  2.6551836 0.0000000                              
## 118 5.9774577 3.6959437 0.0000000                    
## 116 4.3692105 1.9442222 2.0049938 0.0000000          
## 67  3.2264532 0.7615773 3.2218007 1.4000000 0.0000000</code></pre>
<p>La distance euclidienne est un cas particulier de la <a href="https://fr.wikipedia.org/wiki/Distance_(math%C3%A9matiques)#Exemples_de_distances_classiques">distance de Minkowski</a>, avec un paramètre <span class="math inline">\(p = 2\)</span>.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" title="1"><span class="kw">dist</span>(<span class="dt">x =</span> iris_ech_num, <span class="dt">method =</span> <span class="st">&quot;minkowski&quot;</span>, <span class="dt">p =</span> <span class="dv">2</span>, <span class="dt">diag =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>##            32        83       118       116        67
## 32  0.0000000                                        
## 83  2.6551836 0.0000000                              
## 118 5.9774577 3.6959437 0.0000000                    
## 116 4.3692105 1.9442222 2.0049938 0.0000000          
## 67  3.2264532 0.7615773 3.2218007 1.4000000 0.0000000</code></pre>
<p>La fonction <code>dist</code> propose quelques autres distances pour variables numériques (voir la <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/dist.html">fiche d’aide de la fonction</a> pour la liste complète). Le package <code>stats</code> offre aussi la fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/mahalanobis.html"><code>mahalanobis</code></a> pour calculer des <a href="https://fr.wikipedia.org/wiki/Distance_de_Mahalanobis">distances de Mahalanobis</a>.</p>
</div>
<div id="distance-entre-des-chaînes-de-caractères" class="section level4">
<h4>Distance entre des chaînes de caractères</h4>

<p>Pour faire le tour des fonctions de mesure de distances incluses dans l’installation R de base, mentionnons aussi la fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/utils/html/adist.html"><code>adist</code></a> du package <code>utils</code> qui calcule la <a href="https://fr.wikipedia.org/wiki/Distance_de_Levenshtein">distance de Levenshtein</a> entre des chaînes de caractères, par exemple :</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb155-1" title="1"><span class="kw">adist</span>(<span class="dt">x =</span> <span class="st">&quot;Allo&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Hello&quot;</span>)</a></code></pre></div>
<pre><code>##      [,1]
## [1,]    2</code></pre>
<p>La distance de Levenshtein, aussi appelée distance minimale d’édition, compte le nombre minimal d’insertions, de retraits et de substitutions à effectuer pour transformer la première chaîne de caractères en la deuxième. Il est possible d’associer un coût différent à chacune de ces opérations. Par défaut, elles ont toutes un coût de 1. La distance de Levenshtein entre <code>"Allo"</code> et <code>"Hello"</code> vaut 2 parce que pour transformer <code>"Allo"</code> en <code>"Hello"</code> il faut au minimum faire les deux opérations suivantes :</p>
<ul>
<li>ajouter une lettre (par exemple un <code>H</code> au début);</li>
<li>transformer une lettre (par exemple transformer le <code>"A"</code> en <code>"e"</code>).</li>
</ul>
</div>
</div>
<div id="algèbre-linéaire" class="section level2">
<h2>Algèbre linéaire</h2>
<p>Il existe plusieurs fonctions en R pour faire de l’algèbre linéaire.</p>
<ul>
<li>multiplication matricielle : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/matmult.html"><code>%*%</code></a>;</li>
<li>transposition : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/t.html"><code>t</code></a>;</li>
<li>inverse : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/solve.html"><code>solve</code></a> (en fait <code>solve</code> résout <code>A %*% x = B</code>, mais par défaut <code>B</code> est la matrice identité);</li>
<li>produit vectoriel (en anglais <em>cross product</em>) de matrices : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/crossprod.html"><code>crossprod</code></a>;</li>
<li>produit dyadique généralisé (en anglais <em>outer product</em>) : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/outer.html"><code>outer</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/outer.html"><code>%o%</code></a>;</li>
<li>produit de Kronecker généralisé : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/kronecker.html"><code>kronecker</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/kronecker.html"><code>%x%</code></a>;</li>
<li>matrices diagonales : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/diag.html"><code>diag</code></a>;</li>
<li>déterminant : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/det.html"><code>det</code></a>;</li>
<li>valeurs et vecteur propres : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/eigen.html"><code>eigen</code></a>;</li>
<li>décompositions : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/svd.html"><code>svd</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/qr.html"><code>qr</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/chol.html"><code>chol</code></a>.</li>
</ul>
<p>Faisons quelques exemples pour illustrer certaines de ces fonctions.</p>
<div id="opérateur" class="section level5">
<h5>Opérateur <code>%*%</code></h5>

<p>L’opérateur usuel de multiplication effectue une multiplication terme à terme entre deux matrices.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" title="1">A &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">nrow =</span> <span class="dv">3</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb157-2" title="2">A</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" title="1">B &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">6</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">nrow =</span> <span class="dv">3</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb159-2" title="2">B</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    6    3
## [2,]    5    2
## [3,]    4    1</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" title="1">A<span class="op">*</span>B</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    6   12
## [2,]   10   10
## [3,]   12    6</code></pre>
<p>Pour effectuer une <a href="https://fr.wikipedia.org/wiki/Produit_matriciel">multiplication matricielle</a>, il faut utiliser l’opérateur <code>%*%</code>. Les dimensions des matrices doivent évidemment concorder.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1">A<span class="op">%*%</span>B</a></code></pre></div>
<pre><code>## Error in A %*% B: non-conformable arguments</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" title="1">C &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">7</span>), <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb165-2" title="2">C</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    5    3
## [2,]    2    7</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" title="1">A<span class="op">%*%</span>C</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   13   31
## [2,]   20   41
## [3,]   27   51</code></pre>
</div>
<div id="fonction-solve" class="section level5">
<h5>Fonction <code>solve</code></h5>

<p>L’<a href="https://fr.wikipedia.org/wiki/Matrice_inversible">inverse d’une matrice</a> s’obtient avec la fonction <code>solve</code>.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" title="1"><span class="kw">solve</span>(C)</a></code></pre></div>
<pre><code>##             [,1]       [,2]
## [1,]  0.24137931 -0.1034483
## [2,] -0.06896552  0.1724138</code></pre>
</div>
<div id="fonction-crossprod" class="section level5">
<h5>Fonction <code>crossprod</code></h5>

<p>La fonction <code>crossprod</code> sert à calculer <span class="math inline">\(A^T B\)</span> ou <span class="math inline">\(A^T A\)</span>.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" title="1"><span class="kw">crossprod</span>(A, B)</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   28   10
## [2,]   73   28</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" title="1"><span class="co"># équivalent à</span></a>
<a class="sourceLine" id="cb173-2" title="2"><span class="kw">t</span>(A)<span class="op">%*%</span>B</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   28   10
## [2,]   73   28</code></pre>
</div>
<div id="produits-dyadique-et-de-kronecker" class="section level5">
<h5>Produits dyadique et de Kronecker</h5>

<p>Parfois, nous avons besoin d’effectuer une opération en prenant toutes les paires de termes possibles entre deux vecteurs ou matrices. C’est ce que font les <a href="https://fr.wikipedia.org/wiki/Produit_dyadique">produits dyadique</a> (<em>outer product</em>) (opérateur <code>%o%</code>) et de <a href="https://fr.wikipedia.org/wiki/Produit_de_Kronecker">Kronecker</a> (opérateur <code>%x%</code>). Cependant, ils n’assemblent pas les résultats de la même façon. Voici des exemples avec des vecteurs.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1"><span class="dv">1</span><span class="op">:</span><span class="dv">3</span> <span class="op">%o%</span><span class="st"> </span><span class="dv">4</span><span class="op">:</span><span class="dv">5</span></a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    4    5
## [2,]    8   10
## [3,]   12   15</code></pre>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" title="1"><span class="dv">1</span><span class="op">:</span><span class="dv">3</span> <span class="op">%x%</span><span class="st"> </span><span class="dv">4</span><span class="op">:</span><span class="dv">5</span></a></code></pre></div>
<pre><code>## [1]  4  5  8 10 12 15</code></pre>
<p>Les deux commandes ont permis le calcul des mêmes 6 produits (<span class="math inline">\(1 \times 4 = 4\)</span>, <span class="math inline">\(2 \times 4 = 8\)</span>, <span class="math inline">\(3 \times 4 = 12\)</span>, <span class="math inline">\(1 \times 5 = 5\)</span>, <span class="math inline">\(2 \times 5 = 10\)</span> et <span class="math inline">\(3 \times 5 = 15\)</span>). Cependant, l’opérateur <code>%o%</code> a rassemblé les produits dans une matrice de dimension 3 par 2, et l’opérateur <code>%x%</code> dans un vecteur de longueur <span class="math inline">\(3 \times 2 = 6\)</span>.</p>
<p>Avec deux matrices en entrée, le résultat de <code>A %o% B</code> est un array à 4 dimensions dont les tailles sont, dans l’ordre, <code>nrow(A)</code>, <code>ncol(A)</code>, <code>nrow(B)</code> et <code>ncol(B)</code>. Le résultat de <code>A %x% B</code> est pour sa part une matrice à 2 dimensions comprenant <code>nrow(A)*nrow(B)</code> lignes et <code>ncol(A)*ncol(B)</code> colonnes.</p>
<p>Voici des exemples.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" title="1">A &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">12</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">nrow =</span> <span class="dv">3</span>, <span class="dt">ncol =</span> <span class="dv">4</span>)</a>
<a class="sourceLine" id="cb179-2" title="2">A</a></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]   12    9    6    3
## [2,]   11    8    5    2
## [3,]   10    7    4    1</code></pre>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" title="1">B &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">ncol =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb181-2" title="2">B</a></code></pre></div>
<pre><code>##      [,1]
## [1,]    1
## [2,]    2</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1">A <span class="op">%o%</span><span class="st"> </span>B</a></code></pre></div>
<pre><code>## , , 1, 1
## 
##      [,1] [,2] [,3] [,4]
## [1,]   12    9    6    3
## [2,]   11    8    5    2
## [3,]   10    7    4    1
## 
## , , 2, 1
## 
##      [,1] [,2] [,3] [,4]
## [1,]   24   18   12    6
## [2,]   22   16   10    4
## [3,]   20   14    8    2</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" title="1">A <span class="op">%x%</span><span class="st"> </span>B</a></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]   12    9    6    3
## [2,]   24   18   12    6
## [3,]   11    8    5    2
## [4,]   22   16   10    4
## [5,]   10    7    4    1
## [6,]   20   14    8    2</code></pre>
<p>Les deux opérations se généralisent à l’emploi d’un autre opérateur que le produit, grâce aux fonctions <code>outer</code> et <code>kronecker</code>.</p>
<div style="page-break-after: always;"></div>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" title="1"><span class="kw">outer</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dv">4</span><span class="op">:</span><span class="dv">5</span>, <span class="dt">FUN =</span> <span class="st">&#39;+&#39;</span>)</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    5    6
## [2,]    6    7
## [3,]    7    8</code></pre>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" title="1"><span class="kw">kronecker</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dv">4</span><span class="op">:</span><span class="dv">5</span>, <span class="dt">FUN =</span> <span class="st">&#39;+&#39;</span>)</a></code></pre></div>
<pre><code>## [1] 5 6 6 7 7 8</code></pre>
</div>
<div id="fonction-diag" class="section level5">
<h5>Fonction <code>diag</code></h5>

<p>Finalement, la fonction <code>diag</code> a plusieurs utilités. Selon le type de l’objet qu’elle reçoit comme premier argument, elle permet de :</p>
<ul>
<li>matrice en entrée : extraire la diagonale de la matrice reçue;</li>
</ul>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb191-1" title="1">C</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    5    3
## [2,]    2    7</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" title="1"><span class="kw">diag</span>(C)</a></code></pre></div>
<pre><code>## [1] 5 7</code></pre>
<ul>
<li>vecteur en entrée : créer une matrice diagonale à partir du vecteur reçu, qui doit continir les éléments à mettre sur la diagonale;</li>
</ul>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" title="1"><span class="kw">diag</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>)</a></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]    0    2    0
## [3,]    0    0    3</code></pre>
<ul>
<li>un seul nombre en entrée : créer une matrice identité dont la taille commune des dimensions est déterminée par le nombre fourni.</li>
</ul>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" title="1"><span class="kw">diag</span>(<span class="dv">3</span>)</a></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]    0    1    0
## [3,]    0    0    1</code></pre>
</div>
</div>
<div id="calcul-différentiel-et-intégral" class="section level2">
<h2>Calcul différentiel et intégral</h2>
<p><em>(Ce sujet ne sera pas approfondi, car ce qui est offert en R dans ce domaine n’est pas très performant ni facile d’utilisation.)</em></p>
<div id="calculs-symboliques-dérivation-avec-d-deriv-et-deriv3" class="section level4">
<h4>Calculs symboliques : dérivation avec <code>D</code>, <code>deriv</code> et <code>deriv3</code></h4>

<p>Tout comme les logiciels Maple ou Mathematica, R peut faire du calcul symbolique de dérivées. Cependant, il est loin d’être le meilleur outil pour ces tâches. Pour illustrer les capacités (limitées) de R dans ce domaine, tentons d’abord de calculer la dérivée suivante :
<span class="math display">\[\frac{d}{dx}( log(x) + sin(x) ).\]</span></p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" title="1">df &lt;-<span class="st"> </span><span class="kw">deriv</span>(<span class="dt">expr =</span> <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(x) <span class="op">+</span><span class="st"> </span><span class="kw">sin</span>(x), <span class="dt">namevec =</span> <span class="st">&quot;x&quot;</span>)</a>
<a class="sourceLine" id="cb199-2" title="2">df</a></code></pre></div>
<pre><code>## expression({
##     .value &lt;- log(x) + sin(x)
##     .grad &lt;- array(0, c(length(.value), 1L), list(NULL, c(&quot;x&quot;)))
##     .grad[, &quot;x&quot;] &lt;- 1/x + cos(x)
##     attr(.value, &quot;gradient&quot;) &lt;- .grad
##     .value
## })</code></pre>
<p>L’objet <code>df</code> est particulier. Il s’agit d’une expression. La ligne <code>.grad[, "x"] &lt;- 1/x + cos(x)</code> permet de constater que R a bien trouvé que la dérivée symbolique de <span class="math inline">\(log(x) + sin(x)\)</span> est <span class="math inline">\(1/x + cos(x)\)</span>. Nous pouvons maintenant utiliser <code>df</code> pour calculer cette dérivée en certains points. Étant donné que nous avons nommé <code>x</code> la variable dans la fonction à dériver, il faut d’abord créer un objet nommé <code>x</code> contenant les valeurs en lesquelles nous souhaitons calculer la dérivée.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" title="1">x &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">:</span><span class="dv">5</span></a></code></pre></div>
<p>Ensuite, nous soumettons la commande suivante pour obtenir le résultat recherché.</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb202-1" title="1"><span class="kw">eval</span>(df)</a></code></pre></div>
<pre><code>## [1] 1.6024446 1.2397323 0.6294919 0.6505136
## attr(,&quot;gradient&quot;)
##                x
## [1,]  0.08385316
## [2,] -0.65665916
## [3,] -0.40364362
## [4,]  0.48366219</code></pre>
<p>Cette sortie contient les valeurs de la fonction d’origine aux points d’intérêt,</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" title="1"><span class="kw">log</span>(x) <span class="op">+</span><span class="st"> </span><span class="kw">sin</span>(x)</a></code></pre></div>
<pre><code>## [1] 1.6024446 1.2397323 0.6294919 0.6505136</code></pre>
<p>suivies des valeurs de la dérivée de la fonction en ces points.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" title="1"><span class="dv">1</span><span class="op">/</span>x <span class="op">+</span><span class="st"> </span><span class="kw">cos</span>(x)</a></code></pre></div>
<pre><code>## [1]  0.08385316 -0.65665916 -0.40364362  0.48366219</code></pre>
<p>Ainsi, R peut faire du calcul symbolique de dérivée, mais il n’offre pas une façon très conviviale de le faire. Plus d’information peut être trouvée dans la <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/deriv.html">fiche d’aide des fonctions <code>D</code>, <code>deriv</code> et <code>deriv3</code></a>. Le R de base n’offre pas de fonctions pour le calcul symbolique d’intégrales. Cependant, le package <code>Ryacas</code> en offre : <a href="https://CRAN.R-project.org/package=Ryacas" class="uri">https://CRAN.R-project.org/package=Ryacas</a></p>
</div>
<div id="calculs-numériques-dérivation-avec-numericderiv" class="section level4">
<h4>Calculs numériques : dérivation avec <code>numericDeriv</code></h4>

<p>Le <a href="https://en.wikipedia.org/wiki/Numerical_differentiation">calcul de dérivées numériques</a> est un peu plus simple. Par exemple, dérivons la fonction de répartition d’une loi normale standard en quelques points avec la fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/numericDeriv.html"><code>numericDeriv</code></a>.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" title="1"><span class="co"># Points en lesquels nous allons dériver</span></a>
<a class="sourceLine" id="cb208-2" title="2">x &lt;-<span class="st"> </span><span class="kw">as.double</span>(<span class="op">-</span><span class="dv">3</span><span class="op">:</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb208-3" title="3"><span class="co"># Valeur de la fonction en ces points</span></a>
<a class="sourceLine" id="cb208-4" title="4"><span class="kw">pnorm</span>(x)</a></code></pre></div>
<pre><code>## [1] 0.001349898 0.022750132 0.158655254 0.500000000 0.841344746 0.977249868 0.998650102</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" title="1"><span class="co"># Calcul de la dérivée en ces points</span></a>
<a class="sourceLine" id="cb210-2" title="2"><span class="kw">numericDeriv</span>(<span class="dt">expr =</span> <span class="kw">quote</span>(<span class="kw">pnorm</span>(x)), <span class="dt">theta =</span> <span class="st">&quot;x&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 0.001349898 0.022750132 0.158655254 0.500000000 0.841344746 0.977249868 0.998650102
## attr(,&quot;gradient&quot;)
##             [,1]       [,2]      [,3]      [,4]      [,5]       [,6]        [,7]
## [1,] 0.004431849 0.00000000 0.0000000 0.0000000 0.0000000 0.00000000 0.000000000
## [2,] 0.000000000 0.05399097 0.0000000 0.0000000 0.0000000 0.00000000 0.000000000
## [3,] 0.000000000 0.00000000 0.2419707 0.0000000 0.0000000 0.00000000 0.000000000
## [4,] 0.000000000 0.00000000 0.0000000 0.3989423 0.0000000 0.00000000 0.000000000
## [5,] 0.000000000 0.00000000 0.0000000 0.0000000 0.2419707 0.00000000 0.000000000
## [6,] 0.000000000 0.00000000 0.0000000 0.0000000 0.0000000 0.05399096 0.000000000
## [7,] 0.000000000 0.00000000 0.0000000 0.0000000 0.0000000 0.00000000 0.004431849</code></pre>
<p>Nous arrivons au bon résultat, soit la fonction de densité de loi normale standard aux mêmes points.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" title="1"><span class="kw">dnorm</span>(x)</a></code></pre></div>
<pre><code>## [1] 0.004431848 0.053990967 0.241970725 0.398942280 0.241970725 0.053990967 0.004431848</code></pre>
<p>L’appel de la fonction <code>numericDeriv</code> n’est pas standard. Il fait intervenir une expression R à créer avec la fonction <code>quote</code>.</p>
<p>Nous pourrions aussi programmer à la main une version simpliste de la dérivation numérique comme suit :</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" title="1">delta &lt;-<span class="st"> </span><span class="fl">.000001</span></a>
<a class="sourceLine" id="cb214-2" title="2">(<span class="kw">pnorm</span>(x <span class="op">+</span><span class="st"> </span>delta) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(x <span class="op">-</span><span class="st"> </span>delta)) <span class="op">/</span><span class="st"> </span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span>delta)</a></code></pre></div>
<pre><code>## [1] 0.004431848 0.053990967 0.241970724 0.398942280 0.241970725 0.053990967 0.004431848</code></pre>
</div>
<div id="calculs-numériques-intégration-avec-integrate" class="section level4">
<h4>Calculs numériques : intégration avec <code>integrate</code></h4>

<p>Effectuons maintenant l’opération inverse : intégrons la fonction de densité de la loi normale standard avec la fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/integrate.html"><code>integrate</code></a>.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" title="1"><span class="kw">integrate</span>(<span class="dt">f =</span> dnorm, <span class="dt">lower =</span> <span class="op">-</span><span class="ot">Inf</span>, <span class="dt">upper =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## 0.8413448 with absolute error &lt; 1.5e-05</code></pre>
<p>Nous arrivons au bon résultat, soit la fonction de répartition de loi normale standard au point 1</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" title="1"><span class="kw">pnorm</span>(<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.8413447</code></pre>
<p>Remarque : La fonction <code>integrate</code> ne travaille pas de façon vectorielle. Elle ne peut pas calculer des intégrales numériques pour plusieurs intervalles en un seul appel de la fonction.</p>
</div>
</div>
<div id="optimisation-numérique" class="section level2">
<h2>Optimisation numérique</h2>
<p><em>(Ce sujet ne sera pas approfondi, car il est trop technique pour certains étudiants.)</em></p>
<p>En mathématiques, l’optimisation consiste à trouver en quel(s) point(s) une fonction mathématique atteint sa valeur maximale ou minimale. En statistique, ce problème est souvent abordé en ces termes : trouver les valeurs des paramètres pour lesquels une fonction atteint son maximum ou son minimum.</p>
<p>Parfois, il est possible de trouver une solution algébrique à ce problème à l’aide du calcul différentiel et intégral. Par contre, il arrive qu’il soit trop difficile, voire impossible, de dériver la fonction en question. L’optimisation numérique est une bonne solution dans un tel cas.</p>
<p>Fonctions R utiles en optimisation numérique :</p>
<ul>
<li>pour optimiser une fonction à une variable : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/optimize.html"><code>optimize</code></a>,</li>
<li>pour optimiser une fonction avec un nombre de variables quelconque : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/nlm.html"><code>nlm</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/optim.html"><code>optim</code></a>,</li>
<li>optimisation sous contrainte : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/constrOptim.html"><code>constrOptim</code></a>.</li>
</ul>
<p>Exemple d’optimisation d’une fonction à une variable en R : trouvons en quel point la fonction de densité de la loi normale atteint son maximum. La théorie nous dit que ce maximum est atteint en la valeur de l’espérance de la loi. Voyons si l’optimisation numérique saura retourner le bon résultat.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" title="1"><span class="kw">curve</span>(</a>
<a class="sourceLine" id="cb220-2" title="2">  <span class="dt">expr =</span> <span class="kw">dnorm</span>(x, <span class="dt">mean =</span> <span class="dv">3</span>), <span class="dt">from =</span> <span class="dv">-3</span>, <span class="dt">to =</span> <span class="dv">10</span>, </a>
<a class="sourceLine" id="cb220-3" title="3">  <span class="dt">main =</span> <span class="st">&quot;Maximum de la densité normale&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;densité N(3,1)&quot;</span></a>
<a class="sourceLine" id="cb220-4" title="4">)</a>
<a class="sourceLine" id="cb220-5" title="5"><span class="kw">abline</span>(<span class="dt">v =</span> <span class="dv">3</span>, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<p><img src="/calculs/calculs_stat_math_r_2020_files/figure-html/unnamed-chunk-98-1.png" width="70%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb221-1" title="1"><span class="kw">optimize</span>(<span class="dt">f =</span> dnorm, <span class="dt">interval =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">10</span>), <span class="dt">mean =</span> <span class="dv">3</span>, <span class="dt">maximum =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## $maximum
## [1] 3
## 
## $objective
## [1] 0.3989423</code></pre>
<p>Oui, pour une loi normale d’espérance 3 et de variance 1, nous arrivons bien numériquement au résultat que le maximum de la densité est atteint en la valeur 3. La fonction <code>optimize</code> nous dit aussi que ce maximum vaut :</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb223-1" title="1"><span class="kw">dnorm</span>(<span class="dv">3</span>, <span class="dt">mean =</span> <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## [1] 0.3989423</code></pre>
<p>Les fonctions <code>nlm</code>, <code>optim</code> et <code>constrOptim</code> utilisent des <strong>algorithmes itératifs</strong>. Elles ont besoin de valeurs initiales pour les paramètres (argument <code>par</code> à fournir obligatoirement). À chaque itération de l’algorithme, elles modifient ces valeurs en tentant de se diriger vers l’optimum de la fonction. Elles peuvent :</p>
<ul>
<li>ne pas converger,</li>
<li>converger au mauvais endroit (optimum local plutôt que global).</li>
</ul>
<p>Il faut être prudent lors de leur utilisation. Par exemple, <code>optim</code> est <strong>sensible au choix de plusieurs arguments</strong>, notamment :</p>
<ul>
<li>l’algorithme employé,</li>
<li>les valeurs initiales données aux paramètres.</li>
</ul>
<p>Ces fonctions sont tout de même très utiles pour effectuer une optimisation lorsque celle-ci est difficile ou impossible à réaliser algébriquement.</p>
<p>Voici un exemple d’optimisation d’une fonction à plusieurs variables. La fonction <code>lm</code> minimise le critère des moindres carrés, en implémentant des formules algébriques. Les estimations des paramètres du modèle linéaire que <code>lm</code> retourne sont les points en lesquelles la fonction des moindres carrés est minimisée. Tentons de minimiser cette fonction de façon numérique. Pour ce faire, nous avons d’abord besoin d’une fonction qui calcule le critère des moindres carrés et qui prend comme premier argument les paramètres du modèle. Nous n’avons pas encore vu dans le cours comment créer des fonctions, mais je me permets tout de même ici d’en créer une, pour illustrer l’optimisation numérique. La syntaxe pour créer des fonctions R sera vue au prochain cours.</p>
<p>Le <a href="https://en.wikipedia.org/wiki/Least_squares">critère des moindres carrés</a> est calculé en sommant les différences au carré entre les valeurs observées d’une variable et les valeurs prédites par le modèle. Pour un modèle de régression linéaire, la fonction suivante calcule de façon matricielle la valeur du critère.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb225-1" title="1">moindresCarres &lt;-<span class="st"> </span><span class="cf">function</span>(beta, y, X) {</a>
<a class="sourceLine" id="cb225-2" title="2">  <span class="kw">as.vector</span>(<span class="kw">crossprod</span>(y <span class="op">-</span><span class="st"> </span>X <span class="op">%*%</span><span class="st"> </span><span class="kw">matrix</span>(beta, <span class="dt">ncol =</span> <span class="dv">1</span>)))</a>
<a class="sourceLine" id="cb225-3" title="3">}</a></code></pre></div>
<p>Le vecteur <code>y</code> doit contenir les valeurs observées de la variable réponse et la matrice <code>X</code> est la <a href="https://en.wikipedia.org/wiki/Design_matrix">matrice de design du modèle</a>. Cette dernière contient les observations des variables explicatives pour les termes présents dans le modèle. Le vecteur <code>y</code> et la matrice <code>X</code> sont des composantes du modèle supposées connues ici. C’est le vecteur de paramètre <code>beta</code> que nous cherchons à estimer. Nous allons utiliser les données du jeu de données <code>cars</code> dans cet exemple.</p>
<p>Voyons d’abord le résultat obtenu avec la fonction <code>lm</code> pour un modèle quadratique.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" title="1">reg &lt;-<span class="st"> </span><span class="kw">lm</span>(dist <span class="op">~</span><span class="st"> </span>speed <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(speed<span class="op">^</span><span class="dv">2</span>), <span class="dt">data =</span> cars)</a>
<a class="sourceLine" id="cb226-2" title="2"><span class="kw">coefficients</span>(reg)</a></code></pre></div>
<pre><code>## (Intercept)       speed  I(speed^2) 
##   2.4701378   0.9132876   0.0999593</code></pre>
<p>Pour retrouver ce résultat par optimisation numérique, il faut d’abord construire le vecteur <code>y</code> et la matrice <code>X</code> comme suit.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" title="1">y &lt;-<span class="st"> </span>cars<span class="op">$</span>dist</a>
<a class="sourceLine" id="cb228-2" title="2">X &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="dt">intercept =</span> <span class="dv">1</span>, cars<span class="op">$</span>speed, cars<span class="op">$</span>speed<span class="op">^</span><span class="dv">2</span>)</a></code></pre></div>
<p>La fonction <code>lm</code> arrive à la valeur minimale des moindres carrés suivante</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb229-1" title="1"><span class="kw">moindresCarres</span>(<span class="dt">beta =</span> <span class="kw">coefficients</span>(reg), <span class="dt">y =</span> y, <span class="dt">X =</span> X)</a></code></pre></div>
<pre><code>## [1] 10824.72</code></pre>
<p>pour les valeurs de paramètres <span class="math inline">\(\beta\)</span> = (2.4701378, 0.9132876, 0.0999593). Quel résultat est obtenu avec <code>optim</code>?</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb231-1" title="1">op1 &lt;-<span class="st"> </span><span class="kw">optim</span>(<span class="dt">par =</span> <span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>), <span class="dt">fn =</span> moindresCarres, <span class="dt">y =</span> y, <span class="dt">X =</span> X)</a>
<a class="sourceLine" id="cb231-2" title="2">op1</a></code></pre></div>
<pre><code>## $par
## [1] 7.2212674 0.2859028 0.1191485
## 
## $value
## [1] 10848.71
## 
## $counts
## function gradient 
##      144       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>L’algorithme a convergé (car il retourne une valeur de 0 pour l’élément <code>convergence</code> dans la sortie), mais il n’arrive pas au bon résultat.</p>
<p>Solution potentielle : changer d’algorithme d’optimisation.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb233-1" title="1">op2 &lt;-<span class="st"> </span><span class="kw">optim</span>(<span class="dt">par =</span> <span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>), <span class="dt">fn =</span> moindresCarres, <span class="dt">y =</span> y, <span class="dt">X =</span> X, <span class="dt">method =</span> <span class="st">&quot;BFGS&quot;</span>)</a>
<a class="sourceLine" id="cb233-2" title="2">op2</a></code></pre></div>
<pre><code>## $par
## [1] 2.47011519 0.91329056 0.09995889
## 
## $value
## [1] 10824.72
## 
## $counts
## function gradient 
##       43        6 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>Autre solution potentielle : changer les bornes initiales.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb235-1" title="1">op3 &lt;-<span class="st"> </span><span class="kw">optim</span>(<span class="dt">par =</span> <span class="kw">c</span>(<span class="fl">2.5</span>,<span class="dv">1</span>,<span class="fl">0.1</span>), <span class="dt">fn =</span> moindresCarres, <span class="dt">y =</span> y, <span class="dt">X =</span> X)</a>
<a class="sourceLine" id="cb235-2" title="2">op3</a></code></pre></div>
<pre><code>## $par
## [1] 2.46514183 0.91414522 0.09993205
## 
## $value
## [1] 10824.72
## 
## $counts
## function gradient 
##      150       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>Ici, même en partant de valeurs initiales très proches des paramètres optimaux, l’algorithme d’optimisation utilisé par défaut avec <code>optim</code> n’arrive pas tout à fait à trouver l’optimum global de la fonction. Seule la solution de changer l’algorithme d’optimisation nous permet d’arriver approximativement au même résultat que celui trouvé algébriquement par <code>lm</code>.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb237-1" title="1"><span class="kw">coefficients</span>(reg)</a></code></pre></div>
<pre><code>## (Intercept)       speed  I(speed^2) 
##   2.4701378   0.9132876   0.0999593</code></pre>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb239-1" title="1">op2<span class="op">$</span>par</a></code></pre></div>
<pre><code>## [1] 2.47011519 0.91329056 0.09995889</code></pre>
<p>Cet exemple illustre comment la fonction <code>optim</code> s’emploie. Il faut d’abord lui donner en entrée des valeurs initiales pour les paramètres de la fonction à optimiser (argument <code>par</code>). Ensuite, il faut lui fournir la fonction R qui implémente la fonction mathématique à optimiser (argument <code>fn</code>). Cette fonction doit retourner une seule valeur, numérique. De plus, son premier argument doit obligatoirement être le vecteur des paramètres que nous cherchons à estimer par l’optimisation effectuée. Après les arguments <code>par</code> et <code>fn</code>, il faut fournir, au besoin, des arguments à passer à la fonction donnée en entrée via l’argument <code>fn</code> (les arguments <code>y</code> et <code>X</code> dans l’exemple). Finalement, nous pouvons configurer le fonctionnement de la fonction <code>optim</code> en modifiant les valeurs des arguments <code>method</code>, <code>lower</code>, <code>upper</code>, <code>control</code>, ou <code>hessian</code>.</p>
<hr />
</div>
</div>
<div id="résumé" class="section level1">
<h1>Résumé</h1>
<div id="calculs-statistiques-1" class="section level4">
<h4>Calculs statistiques</h4>

<ul>
<li>Distributions de probabilité</li>
<li>Génération de nombres pseudo-aléatoires</li>
<li>Calcul de statistiques descriptives (déjà vu)</li>
<li>Tests statistiques</li>
<li>Ajustement de modèles
<ul>
<li>Manipulation de la sortie d’une fonction d’ajustement de modèle</li>
<li>Formules</li>
</ul></li>
</ul>
<div id="distributions-de-probabilité-et-génération-de-nombres-aléatoires" class="section level5">
<h5>Distributions de probabilité et génération de nombres aléatoires</h5>

<table>
<colgroup>
<col width="21%" />
<col width="78%" />
</colgroup>
<thead>
<tr class="header">
<th>Famille de fonction</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>dxxx</code></td>
<td><strong>fonction de densité</strong> de la distribution <code>xxx</code></td>
</tr>
<tr class="even">
<td><code>pxxx</code></td>
<td><strong>fonction de répartition</strong> de la distribution <code>xxx</code></td>
</tr>
<tr class="odd">
<td><code>qxxx</code></td>
<td><strong>fonction quantile</strong> de la distribution <code>xxx</code></td>
</tr>
<tr class="even">
<td><code>rxxx</code></td>
<td>génération pseudo-aléatoirement d’observations selon la distribution <code>xxx</code></td>
</tr>
</tbody>
</table>
<p>Liste de toutes les distributions <code>xxx</code> offertes en R de base : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/Distributions.html"><code>help(Distributions)</code></a></p>
<ul>
<li>fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/sample.html"><code>sample</code></a> (ou <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/sample.html"><code>sample.int</code></a>) : tirage aléatoire d’échantillons</li>
<li>fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/Random.html"><code>set.seed</code></a> : pour fixer le germe du tirage pseudo-aléatoire</li>
</ul>
</div>
<div id="tests-statistiques-1" class="section level5">
<h5>Tests statistiques</h5>

<p>Quelques fonctions R pour faire des tests statistiques de base :</p>
<ul>
<li>tests sur une ou des moyennes : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/t.test.html"><code>t.test</code></a>;</li>
<li>tests sur une ou des proportions : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/prop.test.html"><code>prop.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/binom.test.html"><code>binom.test</code></a>;</li>
<li>tests de comparaison de variances : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/var.test.html"><code>var.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/bartlett.test.html"><code>bartlett.test</code></a>;</li>
<li>tests sur une corrélation : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/cor.test.html"><code>cor.test</code></a>;</li>
<li>tests pour une distribution : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/shapiro.test.html"><code>shapiro.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/ks.test.html"><code>ks.test</code></a>;</li>
<li>tests non paramétriques : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/wilcox.test.html"><code>wilcox.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/kruskal.test.html"><code>kruskal.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/friedman.test.html"><code>friedman.test</code></a>;</li>
<li>tests sur des fréquences : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/table.html">méthode <code>summary</code> pour un objet de classe <code>table</code></a> (produit par la fonction <code>table</code> ou <code>xtabs</code>), <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/chisq.test.html"><code>chisq.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/fisher.test.html"><code>fisher.test</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/mantelhaen.test.html"><code>mantelhaen.test</code></a>.</li>
</ul>
</div>
<div id="ajustement-de-modèles-1" class="section level5">
<h5>Ajustement de modèles</h5>

<p>Quelques fonctions R pour ajuster des modèles :</p>
<ul>
<li>modèles linéaires, dont la régression : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/lm.html"><code>lm</code></a>;</li>
<li>modèle d’analyse de la variance : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/lm.html"><code>lm</code></a> ou <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/aov.html"><code>aov</code></a>;</li>
<li>modèles linéaires généralisés : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/glm.html"><code>glm</code></a>;</li>
<li>modèles linéaires mixtes (peuvent contenir des effets aléatoires) : <code>lmer</code> du package <a href="https://CRAN.R-project.org/package=lme4"><code>lme4</code></a> ou <code>lme</code> du package <a href="https://CRAN.R-project.org/package=nlme"><code>nlme</code></a>;</li>
<li>modèles non linéaires : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/nls.html"><code>nls</code></a>.</li>
</ul>
</div>
<div id="formules-r" class="section level5">
<h5>Formules R</h5>

<p><strong>Écriture générale</strong> : <code>y ~ x1 + x2</code><br />
où <code>y</code> = variable réponse, <code>x1</code> et <code>x2</code> = variables explicatives.</p>
<p><strong>Opérateurs acceptés</strong> et leur signification :</p>
<ul>
<li><code>+</code> pour ajouter des termes;</li>
<li><code>-</code> pour soustraire des termes;</li>
<li><code>- 1</code> ou <code>+ 0</code> pour retirer l’ordonnée à l’origine;</li>
<li><code>.</code> pour représenter toutes les variables dans le jeu de données, autres que la variable mise à la gauche du <code>~</code> ;</li>
<li><code>:</code> pour les termes d’interaction entre facteurs;</li>
<li><code>*</code> pour le croisement de facteurs;</li>
<li><code>^</code> croisement de facteurs jusqu’à un certain niveau d’interaction;</li>
<li><code>%in%</code> pour les facteurs emboîtés;</li>
<li><code>|</code> pour un conditionnement ou spécifier des effets aléatoires</li>
</ul>
<p><code>I()</code> pour utiliser la signification usuelle des opérateurs et non celle spécifique aux formules.</p>
</div>
<div id="sortie-dune-fonction-dajustement-de-modèle" class="section level5">
<h5>Sortie d’une fonction d’ajustement de modèle</h5>

<p>Affichage (<code>print</code>) vs liste contenant les objets retournés</p>
<p>La liste retournée a une ou des classes <span class="math inline">\(\rightarrow\)</span> programmation orientée objet</p>
<p>Fonctions pour tirer de l’information d’un objet produit par une fonction d’ajustement de modèle :</p>
<ul>
<li><code>summary</code> : plus de résultats relatifs au modèle + affichage d’un résumé des informations;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/coef.html"><code>coef</code></a> (ou son alias <code>coefficients</code>) et <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/confint.html"><code>confint</code></a> : coefficients et leurs intervalles de confiance;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/residuals.html"><code>residuals</code></a> et <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/fitted.values.html"><code>fitted</code></a> : résidus et valeurs prédites;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/predict.html"><code>predict</code></a> : prédiction pour une nouvelle observation;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/anova.html"><code>anova</code></a> : table d’analyse de la variance du modèle;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/model.tables.html"><code>model.tables</code></a> et <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/TukeyHSD.html"><code>TukeyHSD</code></a> (pour la classe <code>aov</code>) : moyennes par niveaux de facteurs et comparaisons multiples de Tukey;</li>
<li><a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/deviance.html"><code>deviance</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/logLik.html"><code>logLik</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/AIC.html"><code>AIC</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/AIC.html"><code>BIC</code></a> : déviance, log-vraisemblance maximisée, AIC et BIC.</li>
</ul>
</div>
</div>
<div id="calculs-mathématiques-1" class="section level4">
<h4>Calculs mathématiques</h4>

<ul>
<li>Opérateurs et fonctions de base (déjà vu)</li>
<li>Calcul de distances</li>
<li>Algèbre linéaire</li>
<li>Calcul différentiel et intégral
<ul>
<li><em>(ne sera pas approfondi, car ce qui est offert en R dans ce domaine n’est pas très performant ni facile d’utilisation)</em></li>
</ul></li>
<li>Optimisation numérique
<ul>
<li><em>(ne sera pas approfondi, car trop technique pour certains étudiants)</em></li>
</ul></li>
</ul>
<div id="calculs-de-distance" class="section level5">
<h5>Calculs de distance</h5>

<ul>
<li>fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/dist.html"><code>dist</code></a> :
<ul>
<li>distance euclidienne par défaut,</li>
<li>autres distances : <code>maximum</code>, <code>manhattan</code>, <code>canberra</code>, <code>binary</code> ou <code>minkowski</code>;</li>
</ul></li>
<li>fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/mahalanobis.html"><code>mahalanobis</code></a> :
<ul>
<li>distance de Mahalanobis;</li>
</ul></li>
<li>fonction <a href="https://stat.ethz.ch/R-manual/R-patched/library/utils/html/adist.html"><code>adist</code></a> :
<ul>
<li>distance de Levenshtein entre des chaînes de caractères.</li>
</ul></li>
</ul>
</div>
<div id="algèbre-linéaire-1" class="section level5">
<h5>Algèbre linéaire</h5>

<ul>
<li>multiplication matricielle : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/matmult.html"><code>%*%</code></a>;</li>
<li>transposition : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/t.html"><code>t</code></a>;</li>
<li>inverse : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/solve.html"><code>solve</code></a> (en fait <code>solve</code> résout <code>A %*% x = B</code>, mais par défaut <code>B</code> est la matrice identité);</li>
<li>produit vectoriel (en anglais <em>cross product</em>) de matrices : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/crossprod.html"><code>crossprod</code></a>;</li>
<li>produit dyadique généralisé (en anglais <em>outer product</em>) : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/outer.html"><code>outer</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/outer.html"><code>%o%</code></a>;</li>
<li>produit de Kronecker généralisé : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/kronecker.html"><code>kronecker</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/kronecker.html"><code>%x%</code></a>;</li>
<li>matrices diagonales : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/diag.html"><code>diag</code></a>;</li>
<li>déterminant : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/det.html"><code>det</code></a>;</li>
<li>valeurs et vecteur propres : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/eigen.html"><code>eigen</code></a>;</li>
<li>décompositions : <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/svd.html"><code>svd</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/qr.html"><code>qr</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/chol.html"><code>chol</code></a>.</li>
</ul>
</div>
<div id="calcul-différentiel-et-intégral-1" class="section level5">
<h5>Calcul différentiel et intégral</h5>
<ul>
<li>Calculs symboliques : dérivation avec <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/deriv.html"><code>D</code>, <code>deriv</code> et <code>deriv3</code></a>.</li>
<li>Calculs numériques :
<ul>
<li>dérivation avec <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/numericDeriv.html"><code>numericDeriv</code></a>;</li>
<li>intégration avec <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/integrate.html"><code>integrate</code></a>.</li>
</ul></li>
</ul>
</div>
<div id="optimisation-numérique-1" class="section level5">
<h5>Optimisation numérique</h5>

<p><strong>Définition générale</strong> : Trouver en quel(s) point(s) une fonction mathématique atteint sa valeur maximale ou minimale.</p>
<p><strong>Application usuelle en statistique</strong> : Trouver les valeurs des paramètres pour lesquels une fonction (ex. log-vraisemblance ou somme des erreurs au carré) atteint son maximum ou son minimum.</p>
<ul>
<li>pour optimiser une fonction à une variable : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/optimize.html"><code>optimize</code></a>,</li>
<li>pour optimiser une fonction avec un nombre de variables quelconque : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/nlm.html"><code>nlm</code></a>, <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/optim.html"><code>optim</code></a>,</li>
<li>optimisation sous contrainte : <a href="https://stat.ethz.ch/R-manual/R-patched/library/stats/html/constrOptim.html"><code>constrOptim</code></a>.</li>
</ul>
<p>Ces fonctions prennent en entrée une fonction R</p>
<ul>
<li>dont le premier argument est le vecteur des paramètres et</li>
<li>dont la sortie est une seule valeur numérique, soit la valeur prise par la fonction mathématique à optimiser lorsque les paramètres prennent les valeurs fournies en entrée.</li>
</ul>
<hr />
<div style="page-break-after: always;"></div>
</div>
</div>
</div>
<div id="références" class="section level1">
<h1>Références</h1>
<ul>
<li>Braun, W. J. et Murdoch, D. (2007). <em>A first Course in Statistical Programming with R</em>. Cambridge University Press.</li>
<li>Hothorn, T. et Everitt, B.S. (2014). <em>A handbook of statistical analyses using R</em>, third edition. CRC Press.</li>
<li>Millot, G. (2018). <em>Comprendre et réaliser les tests statistiques à l’aide de R: manuel de biostatistique</em>, 4<sup>e</sup> édition. De Boeck Supérieur.</li>
</ul>
<p>Références web :</p>
<ul>
<li>R Core Team (2019). An Introduction to R.<br />
<a href="https://cran.r-project.org/doc/manuals/r-release/R-intro.html" class="uri">https://cran.r-project.org/doc/manuals/r-release/R-intro.html</a></li>
<li>Distributions de probabilité en R : <a href="https://CRAN.R-project.org/view=Distributions" class="uri">https://CRAN.R-project.org/view=Distributions</a></li>
<li>Sites web contenant plusieurs exemples d’analyses statistiques en R :
<ul>
<li><a href="https://stats.idre.ucla.edu/other/dae/" class="uri">https://stats.idre.ucla.edu/other/dae/</a></li>
<li><a href="https://www.statmethods.net/about/sitemap.html" class="uri">https://www.statmethods.net/about/sitemap.html</a></li>
</ul></li>
</ul>
</div>
